<?php
  include ("inc/head.php");
  $GLOBALS['interna'] = true;
  include ("inc/header.php");
?>
    <div id="centro" class="arteliteratura">
      <div id="izquierda">
        <div id="arteliteratura">
          <div class="barra_titulo">
            <span></span>
            <h1>Arte &amp; Literatura</h1>
            <span class="tail"></span>
          </div>
          <div id="header_slider">
            <img src="uploads/andres_caceido.jpg" title="Header entrevista" alt="Torre de Babel" />          </div>
          <div id="texto_entrevista">
 <p><strong>Andrés Caicedo era escritor. Nació en Cali, Colombia, en 1951. Su obra es considerada como una de las más originales de la literatura colombiana. Se suicidó  el 4 de marzo de 1977.</strong></p>
 <p><em>“EL 26 de Febrero prendimos la ciudad de la Quince para arriba, la tropa en todas partes, vi matar a muchachos a bala, niñas a bolillo, a Guillermito Tejada lo mataron a culatazos, eso no se olvida. Que di piedra y me contestaron con metralla. Que cuando hubo que correr corrí como nadie en Cali. Que no hay caso, mi conciencia es la tranquilidad en pasta, por eso soy yo el que siempre tira la primera piedra”<br />
   El Atravesado, Andrés Caicedo</em></p>
 <p><strong>Andrés Caicedo se suicidó a los 25 años. Se tomó 60 pastillas de Secobarbital. </strong>Algún tiempo antes había escrito. “Come todo lo que sea malo para el hígado: mango viche y hongos y pura sal, y acostúmbrate a amanecer con los gusanos. No te preocupes, muérete antes que tus padres, para liberarlos de la espantosa visión de tu vejez”. Cuando muere Caicedo nacen cientos de lecturas distintas de quién fue el escritor colombiano. ¿Qué clase de escritor era? Fuguet dice que era un atormentado intelectual, menos que una estrella de rock.  Fabián Casas, que era un escritor de la periferia, que nunca va estar del lado del “establishment” literario. Leí por primera vez a Caicedo estando en Bogotá, en Colombia.  Compré una edición del El Atravesado y me lo leí de un tirón en un par de horas. Atrapado por la intensidad y la sensibilidad de la escritura me preguntaba ¿Cómo un pibe de 25 años podía ser un autor gigantesco?<br />
   Mientras Roberto Bolaño “el Nuevo Gran Escritor de Latinoamérica” seguía escribiendo cuentos y novelas plagadas de referencias literarias a Borges, Cortázar y Mallarmé, Caicedo dos años más viejo dinamitaba la institución literaria y el boom latinoamericano. Caicedo y Bolaño tuvieron una edad similar. Pero el salto del colombiano en la literatura es tal que cuando Bolaño seguía discutiendo en sus conferencias contra García Márquez, el autor del El Atravesado ya había dejado una obra hace veinte años que invertía completamente el paradigma de la literatura latinoamericana.  Caicedo había liquidado a García Márquez veinte años antes, en el mismo momento en que dejó su novela “Que viva la Música”. Su escritura ya no pertenecía a “La Literatura” como Gran Institución. Es que Caicedo no escribe desde el interior de ella. <strong>Sus cuentos y novelas expanden los límites hacia las calles urbanas de Cali, penetradas por el cine norteamericano y sus variantes genéricas; el western, el melodrama, las películas de horror, las drogas, las pandillas, la salsa, el rock and roll y la cuestión marxista.</strong><br />
   Patricia Restrepo, compañera y pareja de Caicedo declaró alguna vez que ella creía que Andrés llevaba el horror por dentro, que vivía paralizado por un enorme miedo. Desde este lugar se puede entender la relación del escritor colombiano con el cine y las drogas como lugar de resistencia. El cine, un gran sueño en donde la realidad no puede lastimar. Ahí donde termina la pantalla empieza la realidad de la calle que ha sido transformada por los géneros cinematográficos.<strong> El fracaso de los personajes de Caicedo en la realidad está vinculado a no poder experimentar las matrices idealistas del cine en lo real.  La experimentación con LSD y con cocaína abrió el lenguaje de su obra a nuevos modelos perceptivos.</strong> Ésta es la dificultad que presenta “Que viva la Música”, una novela hermética que fluye no tanto por la narración sino más bien por su cadencia musical, el fluir constante del discurso alucinógeno de María del Carmen Huertas. Adolescente eterna que parece estar viviendo una gran despedida celebratoria, yéndose de rumba una y otra vez, bailando y consumiendo drogas hasta que su cuerpo y el de sus compañeros se desintegran.<br />
   La obra de Caicedo fue de avanzada como la de Manuel Puig en Argentina. Los dos abrieron la literatura a los puntos conflictivos de la invasión de la industria cultural norteamericana sobre la sensibilidad de Latinoamérica. Caicedo escribe desde la matriz violenta de Cali. Manifiesta que la violencia estaba en el lenguaje y que ese mismo lenguaje ya había sido manchado por los problemas urbanos. Su artificio construye el habla de las calles de Cali.  Sus personajes manifiestan la hibrides que cruza la violencia, la muerte, la cinefilia, el melodrama y el amor. Las coordenadas de los personajes son las calles caleñas, ahí se aprende a sobrevivir a la persecución, a la muerte injusta.  <strong>Escribir para sobrevivir. Crear mundos fantasmáticos que nos permitan resistir. De ahí la necesidad de la escritura como urgencia para expresar una fuerza.</strong> Una literatura que está en consonancia no sólo con la obra de Fernando Vallejo, sino también con la de Roberto Arlt y Pablo Ramos en Argentina.  El escritor colombiano es un espectro silencioso que ronda por el presente de la literatura de Latinoamérica.  Los libros de narrativa de Fabián Casas son un fiel reflejo del problema planteado por su obra. Los dos comprendieron la necesidad de que la literatura estuviese amalgamada por la cruza de dialectos y culturas.<br />
   </p>
 <p><strong>Si Bolaño seguía atrapado en la modernidad en el sentido de pensar a la literatura como un órgano autónomo, Caicedo ya era un autor que prefiguraba el problema posmoderno. No me refiero a que sea un escritor posmoderno. Desde el punto de vista estilístico no lo es. Pero sí es cierto que su literatura se acerca al problema filosófico de la posmodernidad, en la medida en que invierte y fragmenta los valores de la cultura.  Todo el espectro de la industria cultural se mezcla desde la cotidianeidad. Hay una nueva forma de leer y una nueva forma de construir valor literario.</strong><br />
   En el último documental sobre la vida de Caicedo, Una Noche sin Fortuna, estrenado en el último BAFICI,  Patricia leyó la carta que Andrés le escribió a ella antes de suicidarse. La carta es escalofriante. Es una carta de amor perfecta en su imperfección. Construida en una gran digresión temporal, que proviene de la desesperación del hombre que espera a la mujer que ama.  La forma en que está escrita hace detener al tiempo. A pesar de eso, Caicedo no se suicida por Patricia.  Al menos eso le dice a ella.  Su suicidio fue en realidad su triunfo ante una forma de organizar la vida. Elige matarse el día que le llega el ejemplar de su primera novela, impresa por una editorial argentina.  Su suicidio fue casi un acto budista. Un acto ético. Un renunciar a la vida impuesta y falsa, porque como el creía, vivir más de 25 años era una vergüenza. Como lo escribió alguna vez Pablo Ramos. “Porque la muerte no es lo contrario a la vida, vivir como un muerto, eso es lo contrario de la vida.” La decisión ética de Caicedo de no querer crecer es un proyecto estético que muestra que la resistencia es no dejar corromperse por el mundo adulto del conformismo. <strong>En su carta suicida el fantasma de Caicedo se escapa por las hendijas de la imagen al punto del desgarro. </strong>Al terminar de leerla Patricia dijo que la carta tiene partes que no le pueden interesar a nadie.  Se podría interpretar que para ella la carta ha perdido valor en términos afectivos.  Esa distancia entre las dos lecturas, la que hace ella y la que hacemos nosotros, es la brecha insondable de quien fue Caicedo, el fantasma misterioso que se hace carne y nos atraviesa de una vez y para siempre, con sus palabras en el cine. </p>
 <p><br />
 </p>
          </div>
     
        </div>
      </div>
      <div id="banners">
        <?php include("inc/banners.php"); ?>
        <?php include("inc/archivo_arteyliteratura.php"); ?>
      </div>
    </div>
  </div>
<?php
  include("inc/footer.php");
?>