<?php
  include ("inc/head.php");
  $GLOBALS['interna'] = true;
  include ("inc/header.php");
?>
    <div id="centro" class="arteliteratura">
      <div id="izquierda">
        <div id="arteliteratura">
          <div class="barra_titulo">
            <span></span>
            <h1>Arte &amp; Literatura</h1>
            <span class="tail"></span>
          </div>
          <div id="header_slider">
            <img src="uploads/mentira.jpg" title="Header entrevista" alt="Torre de Babel" />          </div>
          <div id="texto_entrevista">
 <p>Hoy es el último día que tengo para entregar una nota a la gente de Asesinos tímidos. Hace un mes que me la pidieron. Hace un mes que no tengo el valor de ponerme a pensar en lo que voy a escribir. No sé y sé qué es. Como no sé y sé por qué es. Entonces me dije “hacela corta y escribir sobre eso” ¿el miedo?, ¿la nada? ¿el instante anterior en el cual parece imposible la palabra? Algo así, aunque no es tan fácil definirlo, si fuera tan fácil no existiría la palabra escrita, al menos para mí.</p>
 <p>   No escribo teoría ni opinión literaria habitualmente, esta es la primera vez que lo hago, o la segunda que sería más o menos lo mismo. Será que después de que a mi primera novela le fuera tan bien a mí me fue tan mal. Sí, me fue mal: casi no escribí por un año, y cuando no escribo, la paso mal. Responder a algunos reportajes, verme obligado a sacar a la luz determinados mecanismos inconscientes (que luego por fuerza dejaron de serlo) de cómo funciona la maquinaria de mi imaginación, me hizo daño. De hecho yo ni era consciente de que tal maquinaria existía. Escribía desde las tripas, casi sin usar la cabeza. Escribía porque el silencio, la soledad y la reclusión me dictaban algo que no podía transmitir a viva voz, algo así como un secreto (no su revelación) y ese secreto se iba armando palabra por palabra en la hoja blanca que yo ponía en el rodillo de mi máquina de escribir. Nunca sospeché que era literatura, nunca sospeché que le podía interesar a alguien más allá de algunos amigos. Eso lo perdí. Ahora, unas pocas personas ajenas esperan algo de mí. Esas pocas personas tienen la dimensión de una multitud. Pienso todo el tiempo en eso, y cuando pienso no soy el que era antes de hacerlo: me margino, me corrijo antes de sacar: me re primo. Creo ahora que la literatura, en el momento de la creación, en el momento del texto primero o primer borrador debe ser un acto de libertinaje. La libertad llega en el momento de corregir lo ya escrito, pero eso es otra cosa.</p>
 <p>   Escribo ahora una novela (casi la tengo lista) y fue todo un ejercicio aparte recuperar el libertinaje de la escritura. Tuve que dejar otra novela que a duras penas venía escribiendo. Tuve que atravesar una crisis de vida, dejar de hacer cosas como atender el teléfono, contestar correos, ir al teatro al cine a la cancha. Tuve que dejar de vivir en pareja, aceptar los caprichos del insomnio, alterar los ratos de sueño con los ratos de escritura, etc, etc, etc. A veces es cansador. La tentación me invita a bajar los brazos. Y si pienso, peor. ¿Por qué me cuesta tanta vida hacer lo que hago?, ¿Por qué no puedo ser un poco menos radical, un poco más medido? ¿La soledad es un precio que tienen que pagar todos los que escriben en serio? ¿Yo soy una persona que escribe en serio? En tal caso, ¿qué es escribir enserio? Y por último, o por principio, habiendo un habla ¿por qué escribir? Estos son algunos de los interrogantes que me aplastaban antes de largarme con la novela en la cual estoy ahora embargado. Interrogantes a los cuales no estaba acostumbrado. De hecho, siempre me consideré un encontrador de respuestas. Respuestas que correspondían a interrogantes desconocidos, pero que tenían el valor de funcionar como catalizadores de la emoción. Como fermentos de la más pura de las esencias capaces de elevarlo todo, de inundar el alma sin necesitar ni una pizca más de la inteligencia necesaria para el mero entendimiento de palabras comunes y corrientes que no encierran ni segundas intenciones, ni pretensiones secretas. Es decir, que no sobraran al lector, si no que lo invitaran a llevar consigo un poco de esa carga pesada pero dulce. Carga que más allá de poder contener toda la tristeza del mundo mundo fuera una especie de alegría eterna, para usar palabras de Borges.</p>
 <p>   A veces creo que la soledad no es un precio. La soledad existe de antes, un escritor es básicamente un solitario más o menos disimulado según los casos, pero un solitario al fin. La escritura es la justificación (porque es una soledad que necesita ser justificada), la defensa de esa soledad. Si lo veo así, el círculo cierra perfectamente. Ya que la soledad le dicta la palabra al escritor, y el escritor no puede elegir sacarse esa soledad de encima como si fuera un abrigo pesado un día caluroso.<br />
   Escribo porque al hablar fracaso. Cada vez que hablo largamente (cada vez más) siento, aún antes de terminar de hablar, la contundencia de una derrota inevitable. Escribir viene a ser lo contrario de hablar. Al hablar me siento prisionero de lo dicho, las palabras se alejan de mí o yo de ellas y son irrecuperables, apurado muchas veces por las circunstancias y las exigencias (ajenas a mi ser) y por más que me ayuden a salir del apremio del momento dándome pequeñas victorias parciales termino siempre sintiendo esa derrota. Una derrota humana, no mía en particular, una derrota que desequilibra la existencia.</p>
 <p>   Escribo entonces para reconciliarme con las palabras. Porque ¿qué otra cosa puede ser más una victoria humana que la reconciliación? Nada. Hay victoria ahí donde no hay vencidos, donde sólo hay vencedores. No confundir esto con una filantropía, la literatura no es un amor impotente. Es algo que nace de todo un ser destinado a otro ser, y destinado también a ser. No entran acá ni la filantropía ni la vanidad. Hoy es-tamos acostumbrados a que el escritor sea una figura, a veces, de moda. Hay muchos casos tan solo en nuestro país. Salir en revistas, que te saquen fotos, que vendas miles de ejemplares, que ganes un premio importante (prestigioso o no) te pueden inflar el pecho. Pero la hinchazón apenas alcanza para cubrir un interior hueco, vacío. Y en las palabras que escribas te vas a delatar, vas a pagar el precio de tu estupidez.</p>
 <p>   Por último los quiero acercar a mi idea de “La arquitectura de la mentira”. Es sencillo: uno construye un texto de ficción de la misma manera en que un arquitecto construye una casa. Uno quiere transmitir intacta una emoción y elige para hacerlo el mejor camino: la mentira. Si la mentira es hermosa puede que suceda el hecho estético, si sucede hay arte, hay narrativa de calidad. Los cimientos, las paredes, los techos de esta casa no pueden ser meros adornos, meros impactos decorativos, globitos de colores, tortitas para el té. No. Tienen que sostener lo que hay que sostener, tienen que resistir lo que haya que resistir. De esa manera se construye un texto literario, cumpliendo rigores, salvando exigencias. La belleza hay que encontrarla ahí, la pintura al final, los colores como resultado de la concepción de un todo, no para tapar lo que al primer portazo se nos caería encima y nos dejaría sepultados bajo una pila de mampostería barata. Si se escribe desde lo profundo de nuestro ser (de nuestra soledad) no hay riesgos, lo garantizo. Si se escribe en una mesa de un café de Palermo imbécil, levantando la mano cada vez que alguien nos saluda como si fuéramos una especie de Papa, con nuestra notebook reluciente y nuestro ego más erecto que el obelisco, estamos listos. Nada de mierdas a la hora de escribir. Que suenen las teclas de una vieja Hermes 2000 o una Undewood. Ampollas en los dedos, hay que darle y darle a esa cosa, decía Boukowsky, y tenía razón. No se olviden que la casa que construyen no es para que el lector la mire de afuera, es para que la habite. Nada de trucos, nada de sorpresas. Hay que escribir horas y horas y si al terminar cada página uno siente que se ha quedado vacío, que no hay manera de seguir... a poner otra hoja, a mirarla un rato, que vamos por buen camino.<br />
 </p>
          </div>
     
        </div>
      </div>
      <div id="banners">
        <?php include("inc/banners.php"); ?>
        <?php include("inc/archivo_arteyliteratura.php"); ?>
      </div>
    </div>
  </div>
<?php
  include("inc/footer.php");
?>