<?php
  include ("inc/head.php");
  $GLOBALS['interna'] = true;
  include ("inc/header.php");
?>  
    <div id="centro" class="entrevistas">
      <div id="izquierda">
        <div id="entrevistas">
          <div class="barra_titulo">
            <span></span>
            <h1>Entrevistas</h1>
            <span class="tail"></span>
          </div>
          <div id="header_slider">
            <img src="uploads/entrevistas/cnolan.jpg" title="Entrevista a Juan Minuj&#237;n" alt="Entrevista a Juan Minuj&#237;n" />          </div>
          <div id="texto_entrevista">
            <p>El hijo obsesionado por el cine de un publicista Inglés y una azafata Americana, el director Christopher Nolan pegó el batacazo en el año 2000 con el film noir “Memento”. La película independiente de 4 millones de dólares de presupuesto entregó todo lo que se espera de un habitual thriller criminal, pero con una vuelta de tuerca ––la recurrente pérdida de la memoria a corto plazo del héroe era ilustrada utilizando dos narrativas entrecruzadas; una se movía linealmente para adelante, mientras que la otra lo hacía para atrás.</p>
<p>Con su narrativa no-lineal, un recurso que Nolan usaría en films posteriores, Memento presentó a un nuevo talento que respetaba la tradición de la literatura hard-boiled al mismo tiempo que rompía las reglas establecidas. Después de manejar cabalmente el drama psicológico del 2002, “Insomnia” para la Warner Bros, dicho estudio le confió la resurrección de la durmiente franquicia de Batman. Bajo su mando “Batman Inicia”, en el 2005, junto con su aún más espectacular continuación del 2008, “Batman: El Caballero de la Noche”, Nolan trajo a bordo una inquietante sofisticación y una seriedad casi Shakesperiana al popular personaje de historieta.</p>
            <p>A mitad de camino entre sus dos visitas a Ciudad Gótica, Nolan bajó un cambio y en el 2006 dirigió “El Gran Truco”, una pieza de época sobre dos magos rivales en la Londres de finales del siglo XIX. En el 2010, el hizo la visualmente desafiante y laberíntica película de robos “El Origen”, sobre un equipo de infiltradores de sueños. Pero detrás de la salvaje imaginación que libero al anárquico Guasón, dobló las calles de Paris cual orgami, y desplegó una historia entera en reversa, está un tradicionalista que evita los efectos especiales y filma todo lo que puede con una sola cámara.</p>
            <p>Nos encontramos con Nolan, de 41 años, mientras estaba editando su tercer y última película de “Batman, Batman: El Caballero de la Noche Asciende”, trabajando con sus asociados en una cómoda casa a pocos metros debajo del letrero de Hollywood. A pesar de una intensa fecha límite para juntar las numerosas piezas que conforman su corte del director, Nolan era el retrato mismo de la calma Zen, hablando suave y deliberadamente sobre su trabajo.</p>
            <p><strong>JEFFREY RESSNER: ¿Cuándo te diste cuenta que dirigir era tu vocación?</strong><br />
              CHRISTOPHER NOLAN: Para ser honesto, siempre hice películas y nunca paré del todo, empezando con pequeños experimentos en stop-motion usando la cámara de Super 8 de mi papá. Dentro de mi mente, es todo un gran continuo sobre el cine y nunca he cambiado. Solía jorobar con la cámara pero no fui a una escuela de cine. Estudie Letras en la Facultad y seguí una orientación absolutamente académica, mientras que hacia mis propias películas y queriendo hacer todavía más. Financie mi primer película, “Following”, solo y la hice con amigos. Todos teníamos trabajos de tiempo completo, así que nos juntábamos todos los fines de semana durante un año, filmando alrededor de 15 minutos de material crudo todos los sábados, una o dos tomas de todo, y tal vez sacando cinco minutos de película utilizable de todo eso. Fuimos con la película al Festival de Cine en San Francisco y Zeitgeist Films la levantó y se hizo cargo de la distribución, lo que me ayudo a que “Memento” pudiera arrancar. Me pagaron por dirigir esa película, tenía millones de dólares en camiones y cientos de personas trabajando, y todo y no miré para atrás desde entonces.<br />
              <br />
              <strong>P: ¿Qué beneficios había en ser autodidacta en vez de ir a una escuela de cine?</strong><br />
              R: Un acercamiento muy orgánico respecto del entender todas las partes que conforman el oficio. Estoy interesado en cada pedazo de la realización porque tuve que hacerla toda yo ––desde la grabación del sonido y la regrabación hasta el montaje y la música. Me siento muy afortunado en ser miembro de la que es probablemente la última generación que editó en una empalmadora Steenbeck, pegándolo todo junto físicamente y haciendo a un lado distintas tomas. Me dio una muy buena base en entender que tiene que ir técnicamente dentro de una película que fuera verdaderamente valioso. Y significó que absolutamente todo lo que hacía era simplemente porque me apasionaba y quería intentar distintas cosas. Vos nunca vas a aprender algo tan profundamente que cuando lo aprendes puramente de curiosidad.<br />
              <br />
              <strong>P: Sos un gran fanático de las novelas policiales, que a menudo utilizan flashbacks y otros mecanismos temporales. ¿De ahí viene tu fascinación por las narrativas no-lineales?</strong><br />
              R: Bueno, tuve un par de grandes influencias. Cuando tenía 16 años yo leí una novela de Graham Swift, “Waterland”, que hizo cosas increíbles con líneas de tiempo paralelas, y contó una historia en diferentes dimensiones que era extremadamente coherente. Alrededor de la misma época, me acuerdo de cuando “The Wall”, de Alan Parker, salía por la tele, que hace una cosa muy similar puramente con la imagen, usando memorias y sueños que se entrecruzan con otros sueños, etc. “The Man Who fell to Earth y Performance” de Nicholas Roeg fueron también influencias. Estas se quedaron en mi cabeza, del mismo modo que muchas otros autores del genero policial ––James Ellroy, Jim Thompson–– y películas de cine negro como “Out of the Past”, de Jacques Tourneur, que era simplemente asombrosa. Luego, de alguna manera, me hice con el guión de “Pulp Fiction” antes de que se estrenara y quede fascinado con lo que Tarantino había hecho.<br />
              <br />
              <strong>P: Dijiste bastante seguido que tu película favorita es “Blade Runner”. ¿Qué significado en especial tiene para vos?</strong><br />
              R: Cuando miras películas de chico, vos te percatas gradualmente de que hay detrás de ellas. Empezás como cualquiera, pensando que a los actores se les ocurre el dialogo y hacen la película ellos solos. Así que cuando yo era joven y miraba “Alien” y “Blade Runner”, pensé que estas eran diferentes historias, con diferentes escenarios, diferentes actores, diferente en todo––pero hay una fuerte conexión entre esas dos películas, y se trata de su director, Ridley Scott. Recuerdo el haberme dado cuenta de eso y pensé que este es el trabajo que quería.<br />
              La atmósfera de “Blade Runner” era también importante, ese sentimiento de que había todo un mundo afuera del encuadre de la escena. Realmente sentías que había cosas que pasaban afuera de esos cuartos donde la película tuvo lugar. Eso es algo que siempre intenté llevar conmigo. Toda película debe tener su propio mundo, una lógica y un sentimiento para ello que se expanda más allá de esa imagen exacta que está viendo el público.<br />
              <br />
              <strong>P: En tus primeras películas vos escribiste, filmaste, editaste y hasta diseñaste la escenografía––lo único que no hiciste fue actuar. ¿Qué proceso utilizás al trabajar con actores?</strong><br />
              R: Lo que trato de hacer es darles cualquier proceso que necesiten. Tal vez no sea lo que ellos creen que necesitan, y de hecho puede que hasta sea contraproducente, pero realmente trato de ser diferente (y adaptarme) a cada actor, trato de hacerlos sentir cómodos, trato de sacarles lo mejor. Vos escuchás historias de directores que deliberadamente hacen sentir incómodos a los actores, pero yo siempre hago que el actor sienta que tiene lo que necesita para explorar una escena. Mi tío, John Nolan, es actor y estuvo en varias de mis películas. Cuando tuve que hacer “Following”,  él estaba enseñando actuación así que le pregunte lo que yo necesitaría saber. El me dio un par de libros de Stanislavski ––“La preparación del Actor” fue uno de esos libros–– y me dijo que me enseñarían lo básico. Él también me hablo sobre algunas cosas y me dio un mayor entendimiento del oficio.<br />
              <br />
              <strong>P: ¿Qué aprendiste del haber trabajado con actores en tus primeras películas?</strong><br />
              R: Yo aprendí un montón de cosas con “Memento”, pero una cosa a la que siempre me adherí desde entonces es dejar que los actores hagan cuantas tomas quieran. He llegado a la conclusión que las luces y las puestas de cámara y el resto de las cosas técnicas consumen casi todo el tiempo. Pero tirar otra toma generalmente solo agrega un par de minutos. Estaba filmando una escena muy importante con Guy Pearce en la que su personaje está extremadamente alterado y lleva a que el personaje de Carrie Anne Moss le quite la camisa y vea los tatuajes que el lleva en el pecho. Ese día, el financiador de la película justo pasaba por el set y él estaba parado justo atrás mío. Hicimos una toma que yo pensé estaba muy bien, y yo sabía que nos quedaba muy poco tiempo. Así que le pregunte a Guy si sentía que lo había hecho bien, y él dijo “No, deberíamos hacerlo de nuevo”. Recuerdo haber tenido un momento en el que me pregunté “¿Y ahora qué hago?”. ¿Le dejo hacer una toma más y me arriesgo a arruinar todo? ¿Insisto en que tenemos que seguir, cosa que Guy aceptaría porque es flexible y profesional? Pero al final, le dejé hacer otra toma, y esa fue la que usamos en la película. Era muy especial, más allá de lo que él había logrado anteriormente, y más allá de lo que yo imaginé era posible para la escena. Me he guiado por ello desde entonces: Si un actor me dice que pueden lograr algo mas con una escena, les doy la oportunidad, porque no va a costar mucho tiempo. No puede tratarse siempre de los aspectos técnicos.<br />
              P: ¿Cómo acomodas en una misma película a aquellos actores que tienen distintos métodos de trabajo?<br />
              R: En “Insomnia”, a Al Pacino le gustaba ensayar minuciosamente, coreografiar sus movimientos y hacer muchas tomas. Su primera toma seria perfecta, pero el realmente le gustaba hablar mucho las cosas, mientras que Hilary Swank no quería ensayar demasiado. Ella quería guardárselo, y entonces hacer lo que iba a hacer en una o dos tomas, no más. Como director, tenés que encontrar la manera de balancear esas cosas, porque vos querés que ambos sientan que se les está dando una base en la medida de lo que necesitan hacer. Lo que amo sobre los grandes actores es cuando los tenés en un Plano de Dos y pensás que sus diferencias van a ser un problema y no lo es, porque se adaptan al proceso el uno del otro, se sienten el uno al otro, se escuchan el uno al otro.<br />
              <br />
              <strong>P: ¿Como fue el pasar de un presupuesto de 45 millones para hacer “Insomnia”, a disponer de tres veces esa cantidad para “Batman Inicia”? ¿Cuán intimidante fue ese salto?</strong><br />
              A: No sé si la experiencia de otros se parece a la mía, pero para mí, la diferencia entre filmar “Following” con un grupo de amigos usando nuestra propia ropa y con mi mamá haciéndonos sándwiches, a gastar 4 millones del dinero de otra persona para hacer “Memento” y tener un equipo de cientos de persona es, al día de hoy, por amplio margen el salto más grande que he hecho. Era un poco como aprender a nadar una vez que te pasas de tu profundidad: No hay mucha diferencia si estas 2 metros o 100 metros más cerca del suelo ––o te ahogás, o no.<br />
              La gran diferencia desde “Insomnia” hasta “Batman Inicia”, es, yo diría, que teníamos grandes sets. Pero había encontrado a un diseñador de producción en “Insomnia”, Nathan Crowley, que hizo mucha dirección de arte en escenarios muy, muy grandes, así que cuando el vino a bordo lo sorteamos juntos. Ese tipo de logística es muy desafiante y era la primera vez que había hecho una película de peso en materia de efectos visuales. Pero, para mí, el proceso en sí mismo siempre ha sido fundamentalmente el mismo: Te parás ahí y mirás lo que la escena va a ser y entonces todo lo demás se cae, o debería caerse si te estás concentrando adecuadamente.<br />
              <br />
              <strong>P: A Vos no te gusta filmar muchas tomas, vos solo haces storyboards de las escenas de acción, evitas tener una lista de planos, y solo usas una cámara para las escenas dramáticas. ¿Cómo tomás tus decisiones de dirección en montaje, dado a que parece que no tenés muchas opciones de cobertura?</strong><br />
              R: Bien, generalmente con los proyectos en los que trabajo, el guión está basado en alguna forma de acción paralela o puntos de vista intercambiables, aun cuando la historia es lineal. Si miras el último par de rollos en las películas de “Batman”, por ejemplo, son todos de acciones paralelas que se cortan entre sí. Lo que significa es que, aunque filmes muy específicamente y eficientemente, vos tenés opciones infinitas en la isla de edición porque no tenés que filmar en continuidad para una determinada escena de acción. Podes saltar de una línea de tiempo a la otra, o de una locación a la otra, de manera tal que tenés un enorme número de variables. No estoy buscando el hacer de ese proceso algo aún más complicado.<br />
              <br />
              <strong>P: ¿Eso significa que podes editar más rápido?</strong><br />
              R: En una película como “Memento”, yo tenía un par de días para editar el material de cada día de rodaje ––el cual promediaba la media hora de metraje. Para “Batman: El Caballero de la Noche Asciende” para llegar a ese corte del director que toma 10 semanas, tengo un día para editar tres días de rodaje ––lo que promedia una hora o una hora y media de metraje. Solamente el sentarse ahí y verlo todo es casi imposible, y Yo tengo opciones masivas, aun rodando de una forma eficiente y sencilla. Para complicarla todavía más––bien, tal vez me dé más opciones, pero voy a limitar mi tiempo de edición solo para agarrarle la mano. Tengo un editor fantástico, Lee Smith, y él está ensamblando todo mientras filmamos. Vos querés distanciarte del rodaje para poder explorar los materiales. Así que querés tener el tiempo para hacer eso.<br />
              <br />
              <strong>P: ¿Por qué preferís filmar con una sola cámara?</strong><br />
            R: Uso más de una cámara para las escenas con dobles de riesgo; para todas las escenas dramáticas uso una sola cámara. Filmar a una sola cámara significa que ya he visto cada cuadro y que ha pasado por la ventanilla de la cámara porque mi atención no está dividida en muchas cámaras a la vez. Así que lo veo todo y miro el metraje cada noche. Si estas filmando a más de una cámara, estas filmando una cantidad descomunal de metraje, y entonces tenés que meterte y empezar de cero, lo que puede ser un problema en materia tiempo.</p>
            <p><strong>P: Sin lista de planos o storyboards, ¿Cómo mantenés registro de todo?</strong><br />
              R: En mi cabeza. Siempre pude visualizar que es lo que quiero mentalmente y puedo quedarme ahí toda la noche editando la película en mi cabeza, un plano a la vez hasta que termino todo. Mirar lo filmado en el día, cosa que todo el mundo solía hacer pero hoy en día es más una opción, es un proceso importante para memorizar el material. Después de memorizarlo, podes editarlo como te venga en gana, y cuando llegas a la isla de edición sabes exactamente dónde encontrar las cosas. Yo le puedo decir a mi editor “Che, filmamos un ángulo diferente en esta toma” o lo que sea y decirle donde puede encontrarlo.<br />
              <br />
              <strong>P: Vos y tu habitual director de fotografía, Wally Pfister son ––junto con Steven Spielberg–– la última resistencia que prefiere seguir rodando en fílmico en una industria que ya se ha cambiado al digital ¿Cuál es tu atracción al medio más viejo?</strong><br />
              R: Durante los últimos 10 años, he sentido una creciente presión respecto al dejar de rodar en cine, y empezar a hacerlo en digital, pero nunca entendí por qué. Es más barato trabajar con fílmico, se ve mucho mejor, es una tecnología conocida y entendida por más de cien años y es extremadamente confiable. Yo, pienso, verdaderamente, se reduce al interés económico de los fabricantes y una industria (de producción) que hace más dinero a través del cambio que en mantener el status quo. Nos ahorramos un montón de plata rodando en fílmico y proyectando en fílmico y no haciendo intermedio digital. De hecho, nunca hice un intermedio digital. Fotoquimicamente, vos podes medir el tiempo en dos o tres pases, lo que toma de 12 a 14 horas, en oposición a las 7 u 8 semanas que toma en el Intermedio Digital. Esta era la manera que todos lo hacían hace 10 años, y yo simplemente continué haciendo películas en la manera que funciona mejor, siempre esperando que haya una buena razón para cambiar. Pero no he visto esa razón todavía.<br />
              <br />
              <strong>P: ¿Pensaste en comunicarle este sentimiento tuyo a la industria y a otros directores? </strong><br />
              R: Mantuve la boca cerrada sobre este tema durante un largo tiempo y me parece bien que todos puedan elegir, pero para mí ese derecho está en verdadero peligro de desaparecer. Así que antes de Navidad junte a algunos cineastas y les mostré el prólogo de “Batman: El Caballero de la Noche Asciende” que filmamos en IMAX, y que luego cortamos del negativo original para positivar. Quería darles una oportunidad de que vean el potencial, porque pienso que el IMAX es el mejor formato de cine que se haya inventado. Es el estándar dorado y del cual cualquier otra tecnología debe compararse, pero en mi opinión no se compara. El mensaje que quería dar es que nadie les va a quitar las cámaras digitales. Pero si queremos que el fílmico siga siendo una opción, y alguien está trabajando en una película para un gran estudio con los recursos y el poder para insistir en ello, deberíamos poder decirlo. Me sentí como si no dijera nada, y entonces empezamos a perder esa opción; sería una lástima. Cuando miro a una imagen digitalmente adquirida y proyectada, luce inferior en comparación a un positivo anamórfico original o uno de IMAX.<br />
              <br />
              <strong>P: ¿Cuáles te da el IMAX que no te da el anamórfico de 35mm o el 65mm?</strong><br />
            R: Filmamos en 65mm de 5 perforaciones para algunas escenas en El Origen y me gustaron mucho los resultados, aparte podés usar el sonido. Pero el IMAX tiene un área de negativo tres veces más grande que el de ese formato. Es todo un salto en términos de calidad que si estás trabajando en una película que es una producción a gran escala podes abrazar a la más pesada tecnología, y permitirla y construirla dentro de tu proceso de producción, así lo que obtenés en términos de calidad cuando estas filmando es extraordinario. Para “Batman: El Caballero de la Noche Asciende” estábamos en Wall Street con alrededor de mil extras, y podías verle la cara a todos en el encuadre. De alguna manera, siento que me lleva casi a la era del cine mudo, donde ellos tenían esas cámaras enormes. Tratar de hacer las cosas a modo de un tableau, cambia el modo que dirijo una película, cambia el modo que coreografío el movimiento de la cámara por el tamaño que esta tiene. La imagen resultante tiene tanto poder que ya no necesitas cortar de la misma manera, podes encuadrar el plano de un modo levemente diferente, y terminás con una sensación completamente diferente.</p>
            <p><strong>              P: ¿Filmaste todas tus películas de alto presupuesto en IMAX?</strong><br />
              R: No filmamos en IMAX para “El Origen” porque estábamos intentando retratar la realidad de los sueños más que su naturaleza extraordinaria, así que usamos cámara en mano y la filmamos de un modo más espontaneo. Por otra parte la calidad operística de “Batman: El Caballero de la Noche” y “Batman: El Caballero de la Noche Asciende” le sentaba mejor el lienzo más grande con el que contaba el formato IMAX. Así que es diferente dependiendo en que película quieras hacer. Pero, en cada caso, siendo un cineasta al que se le han dado presupuestos considerables con los cuales trabajar, siento una responsabilidad para con el público de estar filmando con la más absoluta tecnología de mayor calidad que pueda proveer y hacer la película del modo que yo la quiera hacer.<br />
              <br />
              <strong>P: Por la clase de películas que vos hacés, mucha gente asume que usás un montón de imágenes generadas por computadora, pero vos preferís usar maquetas, pinturas matte y efectos realizados en cámara. ¿Cuándo preferís usar el CGI?</strong><br />
              R: La cosa con las imágenes generadas por computadora es que es una herramienta increíblemente poderosa para hacer mejores efectos visuales. Pero yo creo en una diferencia absoluta entre animación y fotografía. Sin importar lo sofisticadas que sean tus imágenes generadas por computadora, si no fueran creadas a partir de ningún elemento físico y vos no hubieras filmado nada, se va a sentir como una animación. Hay habitualmente dos metas en una película de efectos visuales. Una es engañar al público con que está viendo algo sin fisuras, y es así como trato de usarlo. La otra es impresionar al público con la cantidad de plata que se gastó en espectáculo del efecto visual, y eso no me suscita interés. Tratamos de mejorar nuestro trabajo con dobles de riesgo y efectos en el decorado con extraordinarias herramientas de CGI tales como borrado de cables y plataformas. Si le ponés tiempo y esfuerzo para que los efectos se parezcan a lo que filmaste, la clase de mejoras que podes meter en los fotogramas realmente pueden engañar al ojo humano, ofreciéndole resultados más allá de lo que era posible hace más de 20 años. El problema para mi es que si no filmás algo con la cámara, en lo que la toma de efectos pueda basarse, dicho efecto va a resaltar en la película como si adoptaras un estilo realista o una pátina. Yo prefiero las películas que dan una sensación de ser mas como la vida misma, así que cualquier CGI debe ser cuidadosamente manejado para entrar en ese perfil.<br />
              <br />
              <strong>P: Tal vez la más famosa escena de efectos especiales en cualquiera de tus películas es la del pasillo giratorio de “El Origen”, la cual hiciste sin pantalla verde o computadoras sino que usaste un verdadero pasillo giratorio. ¿Por qué decidiste adoptar la metodología de la vieja escuela para esa escena?</strong><br />
              R: Crecí siendo un gran fanático de “2001” de Kubrick, y estaba fascinado por como el construyó ese decorado centrífugo para que los astronautas pudieran trotar alrededor y de arriba abajo. Encontré sus ilusiones completamente convincentes y alucinantes. Era una de esas raras instancias en las que, cuando averiguás como se hizo el truco, es aún más impresionante. Siempre quise hacer algo así, y con “El Origen” yo tuve la oportunidad y los recursos para hacerlo dentro del contexto de una película de acción. Tomar ese truco y llevarlo en una dirección diferente cumplió una de mis ambiciones de la infancia. Hay muchas técnicas que cambian en la realización a lo largo de los años, y muchas de las cosas que creciste admirando ya no presentan las oportunidades de ser realizadas otra vez. Pero ese efecto físico a gran escala era aun así la mejor manera de hacer la secuencia, y era realmente divertido.<br />
              <br />
              <strong>P: Hablando de cambios técnicos, ¿Hubo presión alguna para filmar “Batman: El Caballero de la Noche Asciende” en 3-D?</strong><br />
              R: Warner Bros. hubiera estado muy feliz, pero yo le dije a los muchachos que yo quería que fuera estilísticamente consistente con las primeras dos películas y realmente queríamos avanzar con el formato IMAX para crear una imagen de alta calidad. Halle que la imagen estereoscópica es muy pequeña e íntima en su efecto. El 3-D es un engaña-pichanga. Las películas son en 3-D. Uno de los razonamientos principales de la fotografía es su tridimensionalidad. La cosa con la imagen estereoscópica es que le da una perspectiva individual a cada miembro del público. Es más adecuado para los juegos de video y otras tecnologías más inmersivas, pero si buscas una experiencia con un público, el estereoscópico es difícil de asimilar. Prefiero un gran lienzo, mirando hacia una enorme pantalla y hacia una imagen que se siente más grande que la vida misma. Cuando encarás eso estereoscópicamente, y mirá que hicimos muchas pruebas, reducís el tamaño de manera tal que la imagen se convierte en una ventana mucho más pequeña posicionada en frente tuyo. Así que el efecto de eso, y la relación de la imagen con el público, debe ser considerado cuidadosamente. Y siento que la primera ola que adoptó esto, no lo consideró en lo más mínimo.<br />
              <br />
              <strong>P: ¿En términos de visuales y estilo, dirías vos que hay alguna constante que recorre a todas tus películas?</strong><br />
              R: Una absoluta preocupación respecto al punto de vista. Ya sea en la puesta de cámara o siquiera de la escritura del guion, todo es sobre el punto de vista. No puedo editar una escena sin antes tener claro desde que punto de vista lo estoy encarando, y no puedo filmar la escena de un modo neutral. He tratado de usar técnicas de cámaras más objetivas –una lente más larga, achatando las cosas, usando más de una cámara–– pero no funcionan. Es gracioso, vos me preguntabas sobre el 3-D y una de las cosas que pasaron cuando se volvió a poner de moda fue que había varios aspectos a considerar a la hora de la conversión. La manera en la que filmo es en realidad muy proclive a ser convertida a 3-D porque siempre estoy pensando en la cámara como un participante. No uso zoom, por ejemplo, así que no reencuadro usando el zoom. En vez de eso, siempre movemos la cámara físicamente más cerca y le ponemos una longitud focal diferente. Estilísticamente, la constante que se repite en mis películas es el plano que entra dentro de una habitación junto con el personaje. Creo que esas cuestiones sobre el punto de vista son muy importantes.<br />
              <br />
              <strong>P: Vos trabajaste con el mismo equipo de dirección ––Asistentes, Segundos Asistentes y Continuistas–– en varias de tus películas. ¿Qué esperás de ellos?</strong><br />
              R: Yo espero que mis asistentes pongan las cosas en orden y puntuales, así como de asegurarse que todas las piezas del rompecabezas encajen. Casi nunca logro irme del set. A veces tengo que orinar, por supuesto, pero de cualquier otra forma estoy ahí junto a la cámara todo el tiempo, así que dependo mucho de mi asistente de dirección para que ronde todos los elementos. Porque también me gusta trabajar rápido y a una sola cámara, tengo que mantener las cosas moviéndose suavemente. Dependo de mi asistente para mantener el set en silencio, sin celulares y, con algo de suerte, sin tensionar tanto las cosas. Él hace un gran trabajo tranquilizando a la gente, mientras que por otro lado deja en claro que vamos a estar extremadamente concentrados en el trabajo en cuestión.<br />
              <br />
              <strong>P: Otra cosa que hace de tu estilo algo único, en especial para películas tan grandes, es que elegís trabajar sin una segunda unidad. ¿A qué se debe eso?</strong><br />
            R: Dejáme que te lo diga de esta manera: Si no necesito estar dirigiendo las tomas que van en la película, ¿Por qué tengo que estar ahí en absoluto? La pantalla es del mismo tamaño para cada plano. Ese pequeño plano de, digamos, un reloj en la muñeca de alguien, va a ocupar el mismo tamaño de pantalla que un plano de miles de personas corriendo por las calles. Todo es medido igualitariamente y debe ser considerado con el mismo cuidado, realmente creo en eso. No entiendo ese criterio de subdividir las cosas. Muchas películas de acción involucran una segunda unidad tomando toda la acción. Para mí, eso es raro porque entonces ¿Por qué querés hacer una película de acción en primer lugar? Dicho esto, hay directores fantásticos que usan con mucho éxito segundas y terceras unidades. Así que todo vuelve a la cuestión de definir qué es lo que hace un director. Cada uno trabaja de diferentes maneras. Realmente me ayudo a mantener mi personalidad en estas películas grandes. Hay un peligro con las películas de mucha acción y es que la presencia del cineasta es diluida, puede convertirse en algo muy neutral, así que intente mantener mi punto de vista en cada aspecto de estas películas.</p>
            <p><strong>P: Sos conocido por ir directo al grano en el set. ¿Cuántas puestas de cámara te gusta hacer por día?</strong><br />
              R: Un numero bastante grande, dado el rodaje a una cámara. En Memento me acuerdo que un día hicimos 53 puestas con una sola cámara. Eso surgió por necesidad, pero también fue muy inspirador, muy vigorizante el hacer distintos pedazos de narrativa en un solo día. Me gusta moverme rápido y puedo llegar a ser muy impaciente, pero creo que la energía ayuda al proyecto. No me gustan los días en el set donde no tenés suficiente que hacer. Pasa muy raramente. Generalmente, nunca tenés suficiente tiempo.<br />
              <br />
              <strong>P: Vos tampoco haces retomas. ¿Cómo evitás eso?</strong><br />
              R: Nunca hice una retoma, toco madera. Todo se reduce a editar, solo el oficio, solo el trabajarlo con el editor cada día, intentando cortes radicales, sacando cosas, haciendo a un lado pedacitos de exposición, diciendo “Esta bien, ¿El público realmente necesita entender esto? ¿Qué tal si no?” Yo siempre sobrescribo la exposición en mis guiones así tengo múltiples maneras de dejar en claro las cosas. Si le decís al público algo tres veces, no lo van a entender, pero si se lo decís solo una vez, lo van a entender. Es una cosa rara. Así que muchos de los cortes son por cuestión de tiempo, para mi es cortar por una cuestión de claridad. Es encontrar donde podes solamente sacar un dialogo que no sirve y encontrar esa manera sencilla de que el público te entienda.<br />
              <br />
              <strong>P: ¿Cuáles son aquellas cuestiones de la industria que te preocupan?</strong><br />
              R: El hurto de Propiedad Intelectual es un asunto muy importante. Si bien los estudios se dieron cuenta un poco tarde, me complace que el Gremio haya tomado una posta verdadera. Pienso que es importante que ambos, cineastas y estudios, entiendan la importancia de proteger sus derechos intelectuales. Yo trabajé a ambos lados de la moneda y si, podés juntar un grupo de amigos y hacer una película sin gastar tanta plata. Pero si te van a pagar, y vivís de eso y si empleas a gente talentosa que también vive de eso, siempre va a haber una metodología cara de hacer las cosas. La única manera de que se te pague es a través de controlar la venta y distribución del material registrado por Copyright. Cualquiera que se beneficie monetariamente a través del robo, y desde luego cualquiera que obtenga ganancias por publicidad a costillas de los derechos de autor de alguien más, debería ser detenido, hecho responsable y juzgado. Muchas de las leyes ya están en su lugar, así que es una cuestión de ejercerlas. Los jueces y jurados deben entender de qué se trata el robo de material protegido por derechos de autor.<br />
              <br />
              <strong>P: Te uniste al “Directors Guild of America” justo después de “Memento”. ¿Qué le dirías a un director novel que está considerando en unirse a esta asociación?</strong><br />
              R: El DGA me nomino a un premio por “Memento” y me acuerdo de haber estado impresionado con la confianza en sí mismos y los valores que tiene el gremio, acerca de que a ellos no les importaba si no era miembro cuando hice esa película. Me uní a ellos para hacer “Insomnia”, que fue mi primera película para un estudio. Creo que la protección que ofrece el Gremio es muy importante, particularmente por que los directores están en una relación creativa bastante complicada con los ejecutivos cuando hacen una película para los estudios. Después de todo, los estudios tienen el poder ya que están financiando la película. Pero es increíblemente importante el tener esas 10 semanas para armar el corte del director, en privado, sin interferencias y poder decir “Dejáme armar esto de manera tal que puedas ver qué fue lo que se filmó y como se supone que debe ser visto”. Eso solo es una de las razones clave para ser parte de la hermandad.<br />
              <br />
              <strong>P: Una última cosa: Noté que mientras muchos de tus pares se visten de forma casual y usando gorras de baseball, no es inusual verte a vos vistiendo un traje oscuro en el set. ¿Para qué vestirse de forma tan elegante?</strong><br />
              R: [risas] Yo fui a un internado donde teníamos que usar uniforme, y me acostumbre a usar todos los bolsillos de mi saco. Me resulta muy cómodo. No me gusta pensar en cómo me voy a vestir, así que uso lo mismo todos los días. Cuando empecé a filmar con un equipo técnico en “Memento” me acuerdo de querer levantar un saco de arena y todo el mundo me gritaba que no lo tenía permitido ya que había gente específica para ese trabajo. Por mucho que me guste ensuciarme las manos, usualmente no llego a hacerlo. Así que me visto del modo que lo haría para irme a la oficina. Es más fácil de esa manera.<br />
              <br />
              (Traducido del artículo “El Tradicionalista” de Jeffrey Ressner, publicado originalmente en la revista del “Directors Guild of America”)<br />
            </p>
          </div>
        </div>
      </div>
      <div id="banners">              
        <?php include("inc/banners.php"); ?>
        <?php include("inc/archivo_entrevistas.php"); ?>
      </div>
    </div>
    <div class="push"></div>
  </div>
<?php
  include("inc/footer.php");
?>