<?php
  include ("inc/head.php");
  $GLOBALS['interna'] = true;
  include ("inc/header.php");
?>
    <div id="centro" class="arteliteratura">
      <div id="izquierda">
        <div id="arteliteratura">
          <div class="barra_titulo">
            <span></span>
            <h1>Arte &amp; Literatura</h1>
            <span class="tail"></span>
          </div>
          <div id="header_slider">
            <img src="uploads/cine_decibeles.jpg" title="Header entrevista" alt="Torre de Babel" />          </div>
          <div id="texto_entrevista">
 <p>Es como si el director-guionista se encontrara frente a una gran consola de sonido, un panel de control donde puede ecualizar todos  los recursos cinematográficos, tanto técnico-formales como los mecanismos propios de la narración, asignándoles valores determinados acorde a su preponderancia en la totalidad del film o en una escena particular. Agudos, graves, medio tonos, efecto. Ajustando los niveles de cada perilla, el director-guionista crea una curva ecualizadora que regula el mundo diegético y el funcionamiento de la película. Entonces, si una determinada canción conlleva una determinada curva de ecualización que la vincula a un determinado estilo –sin insinuar analogías, como el pop, el rock, o la música alternativa son a la comedia, el terror, el melodrama o el cine de autor- el escucha, el espectador, puede establecer sus propios parámetros de ecualización sobre el material en bruto y así distorsionar la percepción de lo recibido. Por ejemplo, aplicar una curva de ecualización preseteada del género pop a una canción que estipula una curva de ecualización representativa del hardcore. 

</p>
 <p>Esta ecualización individual que ejerce el espectador cinematográfico, se encuentra  supeditada a unas determinadas condiciones de existencia que imponen determinados valores culturales que marcan el ritmo de la percepción de una época. Podría hablarse de la necesidad de una historia de la percepción para trabajar la cruza, no únicamente la cruza estilística, también la cruza dimensional.
   
   </p>
 <p>Berger trabaja en “Usos de la fotografía”, la profecía fotográfica, es decir, la necesidad de equiparar hasta lo posible el uso de la fotografía con la memoria. Lo que en definitiva propone Berger, casi a modo de deseo, es ir en busca de una memoria social y política que “acoja cualquier imagen del pasado en el seno de su propia continuidad”, no como momentos separados o fragmentos. Es que Berger trabaja con toda una corriente de estado ya manifestada por autores como Susan Sontag, para establecer que la fotografía se utiliza de manera unilineal –sea para ilustrar un argumento- o tautológica –repetir lo dicho en palabras-. Es esta obstinación por hacer de la visión una garantía de conocimiento. Berger impulsa un uso radial de la fotografía -similar al de la memoria- para generar asociaciones que conduzcan a un mismo acontecimiento. Que el contexto sitúe la fotografía en el tiempo narrado, que se haga histórico una vez asumido por la memoria y acción social. Toda esta búsqueda teórica de Berger, que más que una indagación es una expresión de deseo, busca señalar un camino y poner en evidencia un cierto malestar ante las dificultades de adaptación perceptivo-cognitivas de las nuevas categorías espacio-temporales impuestas por la posmodernidad. Me gusta leer a Berger como si hablara de un proyecto que modifique directamente la percepción. Como si de alguna manera insinúe la necesidad de reevaluar todas las esferas de conocimiento a partir de un ad infinitum de asociaciones que vuelva histórico los acontecimientos. Esto implicaría la eliminación de la memoria individual y su reemplazo por una memoria social. No como dos memorias separadas -una personal e individual y una oficial y colectiva- sino como la síntesis disyuntiva de una nueva memoria capaz de originar mapas cognitivos que nos permitan conocer el mundo en su totalidad abstracta. 
   
   </p>
 <p>El modelo de análisis del panel de control del director-guionista, propone a través del pensamiento creativo, poner en práctica esta máquina radial de asociaciones que no tendría como objetivo un sentimiento de entender lo sucedido. Como si el lector pudiera hacer uso de una especie de máquina de tiempo interna para retrotraerse al contexto en que determinado acontecimiento tuvo lugar y así generar todo un tejido de pensamiento histórico para volver al presente, sean veinte años después o dos siglos después, y contentarse con el botín de su pesquisa individual. Lo que debería ponerse en tensión son los modos de percepción de una época y el presente desde el cual percibo. Una historia de los modelos perceptivos para construir asociaciones que no impongan una linealidad cognitiva ni movimientos separatistas; sino, contrastes, tensiones que generen un sentimiento de desasosiego e incertidumbre. La mezcla no debería entenderse como un órgano nivelador del capitalismo tardío, donde es posible tatuarse el escudo de River Plate y el prisma de Pink Floyd, como si se tratara de una pérdida de identidad local ante las potencias compensadoras de la globalización. De la mezcla a la cruza. La cruza como programa que reúna, en sus diferencias asociativas, un nuevo entendimiento de la geografía cognitiva. Centenares de focos radiales liberados de un programa totalizador.</p>
 <p> Al proponer este modelo como una herramienta de pensamiento creativo, la elección de los valores y categorías a potenciar es una elección puramente arbitraria. Las categorías seleccionadas juegan el papel de diferentes frecuencias, de variables  incrustadas en la matriz ideológica. Quizás en la matriz ideológica de un tiempo y espacio imposible de acceder en su totalidad. Por poner un ejemplo, vamos a tomar  la escuela del neorrealismo italiano para establecer dos curvas de ecualización perceptivo dimensionales y superponerlas en un mismo gráfico. Por seleccionar valores al azar para construir la curva de ecualización, nos vamos a limitar a las siguientes categorías: actualidad, historia, iluminación, el niño actor. Lo siguiente es potenciar cada una de estas categorías acorde a la percepción actual que se tenga de una percepción pasada, de las condiciones de producción y existencia del neorrealismo. Este es un trabajo de contextualización que implica situar en el tiempo narrado a la actitud vanguardista neorrealista, sus causas inmediatas y de largo plazo. Un trabajo de investigación, de comparación, de contraste, de acotar el campo de lectura para establecer asociaciones relativas. Vamos a tomar cada categoría por separado y otorgarle un valor –por elegir una escala- del 1 al 10 acorde a su preponderancia en el movimiento. 
   
   </p>
 <p><strong>Actualidad</strong>: Una de las principales irrupciones que planteaba el neorrealismo, era ser un movimiento que escriba la actualidad. Un cine de post-guerra que trataba con los problemas inminentes de su época. Las ruinas de una Italia devastada, el fervor de resistencia y liberación, un paso para acortar la distancia entre los tópicos de ese pasado y la producción cinematográfica. Podríamos decir que esta es una de las principales características del neorrealismo italiano, lidiar con problemas temáticos directamente extraídas  de su presente. Por lo que vamos a otorgarle a esta categoría un  valor de 9. 
   
   </p>
 <p><strong>Historia</strong>: Ya André Bazán escribió sobre la imagen-hecho, ya  Gilles Deleuze sobre la crisis del tópico y el aflojamiento de los nervios sensorio motrices. La historia como una cobertura para decir aquello otro que se quería decir. Por lo que vamos a asignarle a la importancia de la historia en los filmes y movimiento neorrealista un 5.   </p>
 <p><strong>Fotografía</strong>: Las condiciones técnicas del neorrealismo eran precarias. Trabajaban en su mayoría en exteriores con iluminación natural. Así la imagen se cargaba con los restos espectrales de la devastación producida por la Segunda Guerra Mundial. Un valor de 3 para esta categoría.</p>
 <p> <strong>El niño actor:</strong> el neorrealismo italiano fue uno de los primeros movimientos en incluir niños en su amalgama actoral, más allá de que otros movimientos como el impresionismo o el cine clásico americano también había echado mano a este recurso. La inclusión de los niños se encuentra estrechamente vinculada con la negación del principio del star y utilización indiferente de actores profesionales o eventuales. Vamos a asignar a esta categoría un valor de 5.
   La siguiente curva ecualizadora para el neorrealismo italiano: </p>
 <p><img src="curva01.jpg" width="500" height="293" img align="middle"/> </p>
 <p>&nbsp;</p>
 <p>Con la primera curva de ecualización y el trabajo de contextualización para potenciar las perillas del tablero del panel control, lo siguiente es tomar las mismas categorías desde lo percibido  y otorgarles nuevo valores acorde a la idea de una percepción actual. </p>
 <p><strong>Actualidad</strong>: El 11 de septiembre del 2001, muchas personas me dijeron al pasar, “no va a tardar mucho en que hagan la película”. Y así fue, a los pocos meses Nicolas Cage hacía de bombero atrapado entre los escombros en una película de Oliver Stone, películas del vuelo 93, películas de la guerra contra Irak, incursiones fílmicas estadounidenses en sublevaciones y dictaduras africanas. Toda una producción cinematográfica avocada a las guerras del presente. Guerras, crisis económicas, otra vez Stone filmando un documental sobre Bush. Y a diferencia del neorrealismo, los propulsores de esta actividad son representantes de las grandes productoras hollywoodenses que cuentan con la supremacía económica para poder llevar adelante proyectos de tal magnitud. Hollywood, a diferencia del neorrealismo, no propone ninguna ruptura perceptiva, ningún nuevo orden estético que estimule un quiebre en la percepción cinematográfica. Es más bien una apropiación, una adueñación de todo un mercado avocado a las crisis del presente. Se puede debatir las razones ideológicas, políticas, culturales, sociales, sociológicas, económicas por las cuales el capitalismo y el capitalismo tardío se han abalanzado sobre este mercado emergente, pero como no es suficientemente necesario para nuestro propósito, vamos a otorgarle a esta categoría un valor de 4. </p>
 <p><strong>Historia</strong>: Centenares de historias repetidas, de historias y modelos. Estructuras copiadas como enlatados. Los grandes contadores de historias ocupan los lugares más altos en la producción cinematográfica, que se recicla y solventa el reciclaje como una operación necesaria para preservar sus recursos. La habilidad para contar una gran historia –en estrecha relación con la imaginación muscular- y el cómo contar esa historia –una trabajo que se acerca un poco más a la fantasía-, siempre disputaron su lugar desde extremos opuestos. Por más de que después de los noventa haya toda una reconfiguración en los modelos narrativos que tiene como foco principal la historia, donde comienzan a ponerse al mercado los manuales de guión, hay películas que buscan una suerte de equilibrio  integral. Un lugar donde dirigir la virtualidad sin sublimarse al vacío ni caer en lo más achacoso. El valor para esta categoría es de 8.</p>
 <p><strong>Fotografía</strong>: El cine que necesita de los avances técnicos, seleccionando, inadmitiendo, reemplazando. HMI por todos lados en las grandes producciones, Vision 2 y 3, emulsiones que primero restan grano y vuelven a ponerlo, el digital, el HD, el fílmico y la alta definición. Producciones independientes, estudiantiles, sin un peso, preocupadas por la calidad de la imagen, porque se vea bien, por repetir o buscar nuevos encuadres manipulando la iluminación, sean interiores como exteriores. El comentario al salir del cine: <br />
   -¿Te gustó?<br />
   -Tiene buena fotografía.<br />
   El boom fotográfico donde todos hicieron un curso de fotografía con altas cámaras y teles. La iluminación y la manipulación de la luz crecieron en su importancia más allá de las condiciones de producción, sea por los avances técnicos o por una propensión al esteticismo. El valor para esta categoría es de 7. </p>
 <p><strong>El niño actor: </strong>todo un mercado de infantes, de niños estrellas, de “Kids” (1995) con droga, HIV y sexo puberto. De pastillas y rehabilitación para Dakota Fanning. Los niños no sólo han ingresado en el mercado laboral cinematográfico, sino que han incrustado nuevos problemas morales y nuevos dilemas a desarrollar. Así, el valor para esta categoría, es un valor de 7.</p>
 <p><br />
   La Curva Ecualizador Segunda es la siguiente:</p>
 <p><img src="curva02.jpg" width="516" height="313" /></p>
 <p>Ya con las dos Curvas Ecualizadoras con variables  funcionales a las frecuencias de la matriz ideológica. La primera curva se  construye a partir de un ecualizador virtual   que se ajusta a determinados parámetros para practicar una redirección  virtual a los restos de un mundo pasado, para crear a partir del pensamiento  imaginativo, un tejido de referencias y asociaciones, una ficcionalización con  fuerzas referenciales precisas y relativas que estimulen nuevas posibilidades  discursivas.   <br />
   Si superponemos los dos gráficos:</p>
 <p><img src="curva03.jpg" width="500" height="296" /></p>
 <p>El espacio sombreado responde a las cruzas obtenidas  entre los dos valores de cada categoría. Un recorte de presente que invoca un  pasado y un futuro espectral. Un ejercicio <em>historizante</em> que sitúa el acontecimiento o varios acontecimientos en un tiempo narrado –pero  no ya un tiempo total-. En el tiempo narrado pueden surgir necesidades de  modificar las valoraciones, de vincular las categorías entre sí y volver a la  Curva Ecualizadora Primera y Segunda, para modificarlas al infinito. Por  ejemplo, entre los valores de actualidad de 4 y 9, está todo lo que separa a la  categoría actualidad en la frecuencia ideológica aparente de la Curva  Ecualizadora Primera, y la frecuencia ideológica perceptiva de la Curva  Ecualizadora Segunda. Si se quiere trabajar los cambios valorativos en las  categorías de actualidad, se puede abrir una nueva curva que tome nuevas  categorías relacionadas al concepto de actualidad que se quiere trabajar. Por  ejemplo: Medios de comunicación, Macro-economía, La Historia actual, La  tradición.  </p>
 <p>El ecualizador es esta especie de chip que llevamos  aguerrido al sistema nervioso central, que maneja señales estéticas para  construir ondas infinitamente compuestas. La imaginación ofrece una mediación  entre lo teórico y lo práctico en el momento que emerge un nuevo significado.  Esta colisión metafórica entre valoraciones categóricas asociativas pretende la  invención de nuevos campos semánticos y fuerzas referenciales situados en una  continuidad. La operación no tiene el objetivo de  alcanzar una verdad o construir un  pensamiento hermético, sino más bien proponer nuevas asociaciones desde la  cruza como programa operativo. Por ejemplo, tomando de la categoría de  actualidad el espacio sombreado entre ambas valoraciones. Si la perspectiva de  análisis, es una perspectiva avocada a la historia del cine; entre ambas  valoraciones, cómo pasar de un 9 –que carga con toda una dimensión de pasado- a  un 4 –que carga con toda una dimensión de futuro-, se esconde toda una  dimensión de presente artificial. Como si el guionista supiera el inicio y final  de una película y le faltara escribir el desarrollo. Partiendo de un  determinado lugar para alcanzar un lugar distinto, todos los giros y  movimientos que permiten ese traspaso valorativo. Entonces, para lo sombreado  de la categoría actualidad se podría trabajar toda una nueva teoría emergente  hacia el horror que por ejemplo enfrentó a Lanzmann y Spielberg, el mundo  bipolar de la Guerra Fría, el vivo y el directo de la televisión, <em>&ldquo;Greetings&rdquo;</em> (1968) de Brian De Palma y  toda una cultura de cine bélico basada en el simulacro y la parodia. Todas  puertas posibles para hilar asociaciones y situar ese cambio valorativo en un  tiempo narrado que admite diferentes dimensiones, que admite una continuidad  suprema pero internamente múltiple. </p></div>
     
        </div>
      </div>
      <div id="banners">
        <?php include("inc/banners.php"); ?>
        <?php include("inc/archivo_arteyliteratura.php"); ?>
      </div>
    </div>
  </div>
<?php
  include("inc/footer.php");
?>