<?php
  include ("inc/head.php");
  $GLOBALS['interna'] = true;
  include ("inc/header.php");
?>
    <div id="centro" class="arteliteratura">
      <div id="izquierda">
        <div id="arteliteratura">
          <div class="barra_titulo">
            <span></span>
            <h1>Arte &amp; Literatura</h1>
            <span class="tail"></span>
          </div>
          <div id="header_slider">
            <img src="uploads/critica_academia.jpg" title="Header entrevista" alt="Crítica en la Academia" />          </div>
          <div id="texto_entrevista">
<p>En el espacio de la crítica cinematográfica se polemiza mucho entorno a una división entre crítica y análisis. Entre propuestas más personales y el análisis académico del plano por plano. También sobre la reseña, como si la reseña emanara directamente de lo que necesita el mercado. Una reseña de revista popular, en la contratapa de un dvd, en la voz de Catalina Dlugi alentando ir al cine para calentarse con una película de Richard Gere y un perro, o en una página de internet que se hace base de datos universal y cobra de publicidades y redirecciones. Muchas divisiones para la crítica, como si cada formato tuviera una lista de reglas a seguir para poder colocar el artículo-texto en el mercado. Muchas variantes con distintos nombres: reseña, comentario, crítica, ensayo, análisis. El problema es que estas especificaciones entraron de lleno en el ámbito académico, y más que cultivar el debate, el encuentro, el autoreconocimiento, se suprime toda voz extraña, toda simpatía. La crítica debería ser una parte fundamental en el devenir artístico, casi terapéutica, y más que someterse a los mandatos del mercado que se infiltran en las voces de los profesores universitarios, debería establecer un intercambio, un juego placentero con las condiciones actuales de producción.</p>
<p>
Se habla de la reseña como un texto que debe contar la película excluyendo valoraciones de tipo personales. Para eso existe la sinopsis que es un paso constitutivo en el desarrollo de un proyecto cinematográfico. Si se habla de reseña como un recurso para contextualizar o proveer de mayor información al futuro espectador,  es una operación tendenciosa, una actividad que debería relacionarse con los técnicos de la premiere, con las campañas publicitarias; o, fácilmente sustituible por unos segundos de indagación en internet. Porque muchas veces escuché que aquello que hace una buena reseña es deslizar con elegancia, con sutileza, las valoraciones personales que se puedan tener del filme. Como si debiéramos eludir a la policía de pensamiento de 1984 –George Orwell-, y expedir mensajes subliminales, mensajes codificados, esperando tener un lector como John Nash capaz de descifrarlos. Todo lo que hacen estas ideas que seducen con el espionaje, es proponer una vía de escape subversiva que termina siendo peor que la enfermedad. Como si hubiera un único camino para la sublevación, predigitado y temeroso, calado de antemano. Es perjudicial para el crítico adoptar una posición derivada, definitiva –esto corresponde más a la tarea del traductor-. La búsqueda del crítico debería ser intuitiva, primitiva. Bajo estos términos es imposible hablar de una buena reseña, la reseña sería buena si silencia todo lo valorativo, si mete gente en el cine, para todo el resto está la sinopsis, o internet, que en unos pocos clicks uno selecciona, sintetiza, pega, elimina, hasta conseguir lo buscado. Un autoboicot más honorable que obedecer a los mandatos de una voz desconocida que seguramente responde a los intereses de las grandes productoras. </p>

<p>Una de las ventajas de internet es poder decir “esto no”, “esto está mal”, “esto va mejor”.  Y es que antes de decidir ver una película tienen gran importancia el título del film y el afiche publicitario. Siempre generan una mezcla de valoraciones preconcebidas y deseos angustiosos, una mezcla de intriga o rechazo ante lo desconocido. Para indagar en la búsqueda personal siempre está la sinopsis o rehuirle si lo que se busca es la sorpresa cinematográfica. Es que el cine, en primera instancia, satisface una necesidad anterior en el espectador. Veo cine porque busco algo, y el primer acercamiento a ese algo perdido son estos elementos –por remitirme a algo estrictamente industrial- el título del film, el afiche publicitario, la sinopsis, el tráiler, etc. Todo aquello que no se vincule directamente con procederes de mercado – el boca en boca, las recomendaciones- imponen una valoración un poco más honesta. Existen grandes recomendadores de películas y campañas de murmullo desastrosas. Y es que antes de ver una película, una vez recorrido el afiche, el título, la sinopsis, el tráiler, el director, los actores; aspectos informativos  que suponen una etiqueta de calidad o no, aquello que termina por definir un acercamiento dubitativo, son el deseo de aventura o valoraciones del tipo Cuevana “no vean esta basura”, “demasiado lenta”, “las tetas de Jessica Alba tiran para una semana de paja”. Todos estos medios, atravesados por la lógica del mercado, vienen a desempeñar dos funciones poco concisas, intercambiables, casi dialécticas, en la aventura cinematográfica: embravecer el deseo de búsqueda o tirarlo a menos. </p>

<p>Con respecto a la crítica y el análisis. Es como si fueran dos polos opuestos, una mayor subjetividad contra una mayor objetividad. En la crítica, una mezcla de valoraciones personales justificadas o en intentos de justificación. Una gran lista de referencias e intertextualidades diseminadas, comentarios tirados al aire con afirmaciones y sobreentendidos peligrosos. Y el análisis cinematográfico, el agotamiento de cada plano como si no hubiera nada más allá de la semiótica, como si la diferencia fuera escasa, contada. Un análisis hermético que conlleva disputas intelectuales contra eruditos de la cinemania, que quiere hacerse pasar por ciencia, que rechaza todo programa de interpretación diferente. El objetivo de este radicalismo es proponer nuevas categorías para la crítica basadas únicamente en la extensión: la reseña crítica y el análisis crítico. </p>

<p>El Séptimo arte, una arte de masas, abre toda una nueva forma de pensar la crítica. Sea la psicología, la música, el teatro, la sociología, la historia, la economía, etc., todas son puertas posibles para abrir campos de lectura en lo relativo a un filme, pero, es imperativo que toda interpretación se nutra de elementos constitutivos de la cinematografía. Acá entraría en juego el análisis. De esta manera se establece la cruza entre distintos tipos de saberes que pueda llevar incorporado el sujeto-crítico, asociado de forma radial, al núcleo del lenguaje cinematográfico. Se propone un intercambio entre todos los recursos estructurales del cine, sean sus elementos técnicos, como narrativos, y todos aquellos saberes superestructurales. A la par que hibrida el lenguaje, a la par debería modificarse la relación con el Conocimiento.</p>

<p>La reseña crítica debería proponer una única idea, justificada y desarrollada de forma precisa, con el fin de pasarle la bola al espectador. Una buena reseña crítica marca una perspectiva de lectura y hace del espectador-lector un espectador activo, participativo, en busca del ajustamiento de las afirmaciones propuestas. Como si se convirtiera en un detective que sigue una pista primordial para resolver el caso. En cambio, el análisis crítico debería llevar al espectador de la mano, a recorrer una minuciosidad, un detallismo, una visión propia. El trabajo del espectador-lector, ya no radica en poner a prueba las hipótesis largadas por el escritor como en la reseña, ya no es un trabajo de búsqueda y rastreo; sino, una labor de verificación, de conformidad o negación. La actitud del espectador-lector sería más cercana a la de un juez, a la de un funcionario que evalúa y reevalúa las pruebas hasta dar con un veredicto.</p>


<p>A grandes rasgos considero que existen dos tipos de críticos, para hablar un poco de estilo, que más que con la cadencia o la estética de la escritura, tiene que ver con operaciones de proceder, de acercamiento al texto y al objeto de análisis. Ambas operaciones válidas acorde a sus condicionamientos. Críticas que funcionan a modo centrípeto, donde la voz del escritor atrae toda periferia para someterla a los mandatos estilísticos individuales. Una actitud que se critica mucho a directores que en lugar de dar vida a personajes que podrían ser verdaderos, que podrían existir, funcionan como una extensión de la voz del autor. Esta actitud da preeminencia a la individualidad, al escritor por sobre el objeto de análisis. Como si lo más importante sería que puedo decir “yo” de la película en vez de que me ofrece la película, de qué forma me cambió, de qué forma incluí el objeto de análisis en mi existencia. Acá está una de las claves centrales de cualquier proyecto artístico. Es un intercambio equitativo donde incorporo la obra, donde nunca más voy a volver a ser el mismo, es una relación afectiva con el texto. Es por eso que considero, que en la medida de lo posible, el crítico debería dejarse atravesar por la estética del filme en su escritura, un intercambio entre iguales. Aquí sí habría una mayor cercanía al lugar que le otorgaba Walter Benjamin al traductor, intentando despertar un eco de sentido profundo del original. Y acá hay algo de erotizante en la relación con el filme. Susan Sontag, en su artículo Recordando a Barthes, parrafraseaba al pensador para hablar del "placer del texto". Hay que saber hacer el amor con una película antes de sentarse a escribir.</p>

</p></div>
          </div>
      </div>
      <div id="banners">              
        <?php include("inc/banners.php"); ?>
        <?php include("inc/archivo_arteyliteratura.php"); ?>
      </div>
    </div>
  </div>
<?php
  include("inc/footer.php");
?>