<?php
  include ("inc/head.php");
  $GLOBALS['interna'] = true;
  include ("inc/header.php");
?>
    <div id="centro" class="arteliteratura">
      <div id="izquierda">
        <div id="arteliteratura">
          <div class="barra_titulo">
            <span></span>
            <h1>Arte &amp; Literatura</h1>
            <span class="tail"></span>
          </div>
          <div id="header_slider">
            <img src="uploads/equi.jpg" title="Header entrevista" alt="Torre de Babel" />          </div>
          <div id="texto_entrevista">
 <p>“Equilibrium” estrenada en el año 2002, protagonizada por Christian Bale, Sean Bean, Emily Watson y Taye Diggs y dirigida por Kurt Wimmer, explora la ciencia ficción futurista. La película amalgama tres clásicos del genero literario “1984” de George Orwell, “Un mundo feliz” de Aldous Huxley y “Fahrenheit 451” de Ray Bradbury. Construye una sociedad distópica después de una Tercera Guerra Mundial donde las emociones han sido proscriptas gubernamentalmente para gestionar un estado donde reina la “paz”. Se es negada la emoción como fuente de la decadencia humana, en pos del bien común haciendo uso de todos los medios necesarios (ciencia, tecnología, drogas) para el condicionamiento total de los individuos.</p>
 <p>   El hombre ha logrado lo imposible: erradicar el odio y la guerra, pero a costa de resignar todo condicionamiento propiamente humano, como es sentir. No hay asesinatos, robos, secuestros, etc. El crimen ha sido erradicado, pero con ello la humanidad como la conocemos ha sido reducida. Recluidos en Libria, una ciudad amurallada aislada del mundo, las personas transcurren en un estado automatizado. Se erradica la individualidad mediante el conformismo de un estado pretendidamente igualitario, pero en su esencia totalitario. Contenido por el borramiento de la identidad, sustituido por un molde único, el de la maquina.</p>
 <p>   Para llevar a cabo el proyecto se escoge la figura del Padre omnipresente. Especie de Gran Hermano que desde innumerables pantallas se hace presente para predicar al pueblo su mensaje de paz, recordando las aberraciones que ejerció el ser humano en tiempos pasados, la guerra y el odio. Esta primer intertextualidad refiere a Orwell y a su libro 1984, el dominio totalizador de las pantallas y el líder. El panóptico foucaultiano. Al control político se le suma el control físico, para ello se recurre al Prozium, una droga sintética que permite anular los sentimientos y con ello la agresividad de los ciudadanos. Cada individuo debe ingerirla en dosis diarias y es penado en caso de olvidarlo (incluso se dispone de relojes cronometradores que informan cuando debe de consumirse). Esta segunda intertextualidad refiere a Huxley y su Mundo feliz. La farmacología como medio de dopamina espiritual. Por último se toma a Bradbury haciendo alusión a Farenheitt 451, todo el arte es destruido. No pueden permanecer lazos con la antigua sociedad y las obras de arte son puentes temporales con esa emocionalidad que pretende ser erradicada, así es como arde la “Gioconda” en los minutos iniciales del film. La iconoclasia se erige, la ruptura de la imagen, la deliberada destrucción de la cultura. El ascetismo visual.</p>
 <p>   La película se concibe como un drama interno que muestra la transformación y la deconstrucción del régimen a través de la mirada de uno de los popes del sistema. Esta construida bajo el punto de vista de John Preston (Christian Bale), un clérigo. Al comienzo del film, Preston se muestra como uno de los grandes exponentes del sistema autoritario. Es considerado como referente, dada su aptitud maquinica en el exterminio. A medida que la trama avanza Preston empieza a doblegarse ante la belleza, la felicidad, las emociones, el amor. Concientiza de igual modo que estos sentimientos implican también dolor, miedo y perdida. Al recobrar su lado humano el logra recordar su pasado traumático borrado. Asume el sacrificio, el dolor de volver conciente la perdida para contraer un objetivo mayor, la búsqueda de la libertad. <br />
   El padre (líder) cuenta con una articulación policial, un grupo de elite, “Los Clérigos del Tetragrámaton”. Esta congregación cuenta con hombres altamente cualificados en el combate de Gun Kata (arte marcial que recuerda las danzas coreográficas de los hermanos Wachowski), su función es detectar los individuos susceptibles de cometer un crimen sensorial. Por crimen sensorial se entiende que el mismo comprende la violación de la ingesta de Prozium, la posesión de objetos con carga sentimental, la presencia emotiva por el incumplimiento de lo anterior. Identificado el infractor se pasa a la captura para su posterior proceso condenatorio e incineración final.<br />
   Ante el autoritarismo se conforma la Resistencia que busca terminar con el régimen, recobrar las emociones, su libertad y con ello el pensamiento crítico. El automatismo es negado. A través de este pensamiento se oponen las categorías del bien común y la libertad individual. La consumación de la utopia de manera negativa. La utopia como la realización de un sacrificio inhumano, la perdida de la carne por la maquina. <br />
   Mary O'Brien (Emily Watson) es la encargada de arremeter contra el régimen abriéndole los ojos a Preston. Su papel es fundamental porque expone la perdida, ella representa lo prohibido, la belleza. John Preston da con ella a través de  Partridge (Sean Bean) su compañero, que es el primero en demostrarle todo lo que el ha perdido. Mediante el reflejo especular que genera en Preston, él va en busca de su esposa Mary. A partir de su encuentro fortuito, comienza la transmutación. En contraposición ingresa Brandt (Taye Diggs) que ira a ocupar el lugar de Preston luego de su baja. En él, Preston encuentra todo aquello que ha sido y que quiere dejar de ser. Una persona carente de sentimientos, con aspiraciones a una autosuperación fisica que lo equivalen a una especie de terminator.</p>
 <p><strong>   Rousseau y “La resistencia”</strong></p>
 <p>Rousseau a través del ”Contrato Social”, hizo surgir una nueva política, basada en la voluntad general. La voluntad general suponía la soberanía del pueblo. Según Rousseau: “Cada uno de nosotros pone en común su persona y todo su poder bajo la suprema dirección de la voluntad general; y cada miembro es considerado como parte indivisible del todo.” La asociación de los hombres no es algo dado naturalmente (la libertad es lo natural) sino que es una consecuencia de la búsqueda de supervivencia. No es natural pero si es voluntario, el hombre se vincula para el desarrollo de la moral y la razón en pos de asumir las necesidades impuestas por la naturaleza. Para constituir una normativa capaz de generar un orden social que evite la dominación de unos sobre otros, involucrando una representación participativa de los individuos en donde la moral y la razón se erigen.  “El Contrato Social” constituye la democracia, los miembros se reconocen en la autoridad de la razón para unirse en una ley común en un mismo cuerpo político. Este estado social supone la creación de reglas de conducta creadas en función de la voluntad general. Así se verifica que es el pueblo mediante la voluntad general el soberano.</p>
 <p>El ideal político de Rousseau se basa en la autonomía racional. La asociación supone el reino de la ley común. Cada uno de los asociados, al entregarse al pacto social, se obedece a sí mismo debido a que las leyes se fundamentan en la voluntad general, en la cual cada ciudadano es a su vez legislador, al deliberar públicamente la creación de las reglas, y súbdito, al someterse libremente a la obediencia de las mismas. El pueblo ejerce una doble dimensión es sujeto y objeto del poder soberano.</p>
 <p>La democracia  se concibe como un gobierno directo del pueblo. El sistema se basa en que todos los ciudadanos, libres e iguales, puedan manifestar su voluntad para llegar a un acuerdo común, a un contrato social. No puede existir una distinción entre soberano e individuo y se debe legislar bajo la voluntad general.</p>
 <p>La filosofía rousseauniana se basa en la antitesis opresión-libertad. Se proyecta una relación de autonomía que excluye la jerarquización. Los rebeldes en “Equilibrium” asumen este ideal político. Buscan recuperar los derechos que un ente superior “Tetragrámaton” les quito. El bien fundamental es la libertad, que a través de un estado totalitario es negada. La excusa de la recuperación ante la crisis supuesta por la última gran guerra permitió al régimen abolir el bien común por el poder propio. Lo colectivo fue disuelto en la figura del Padre, que en lugar de luchar por el interés común, lucho para erradicar el pensamiento e instituirse con su interés personal de dominio. </p>
 <p>En relación a la conformación urbanística de la sociedad distópica propuesta, se puede vislumbrar lo irreverente que es con el pensamiento de Rousseau, ya que el promulgaba una necesidad del individuo de relacionarse con la naturaleza, aquí destruida. El hombre desnaturalizado, privado de instintos pierde su capacidad contemplativa, lo orgánico es ultrajado por la primacía de lo monocromático innatural. La estructura de la urbe toma sus formas del art deco y de la corriente futurista. Marinetti, máximo exponente del movimiento,  intervino en la creación de la estética fascista. La decisión de asociar estas edificaciones con la estética futurista, actúa a modo ejemplificador de la política que en la misma se desarrolla. </p>
 <p>La paleta cromática es trabajada por contrastes. Prima a lo largo de toda la película los colores oscuros y opacos, lo monocromático funciona para dar mayor valor a las escenas donde arremete el color calido relacionado con la emoción.</p>
 <p>La película hace alusión a un tipo de pedagogía autoritaria. Rousseau concebía su paradigma del hombre encadenado en Emilio. Con Emilio se proponía apartar la formación del hombre bajo una doctrina educativa opresiva. El pensamiento educativo rousseauniano proponía: “asignar a los niños más libertad y menos imperio, dejarles hacer más por sí mismos y exigir menos de los demás” “La educación debe tener su lugar dentro de la naturaleza para que el potencial del niño pueda desarrollarse según el ritmo de la naturaleza y no al tiempo de la sociedad”. Lo primero que debe tenerse en consideración es la formación del hombre, luego se debería de pensar en la formación del ciudadano, estas no son simultaneas. Al niño debe dejárselo en libertad para que experimente, no restringirlo a una estricta disciplina que no permita la formación humana y natural. </p>
 <p>Las ideas políticas de Rousseau se ven traspuestas en el grupo de la Resistencia. En su momento estas ideas influenciaron a la Revolución francesa, en la película inciden en el pensamiento de una apertura y destitución del régimen vigente. “Renunciar a la libertad es renunciar a la cualidad de hombres, a los derechos de humanidad e incluso a los deberes”.</p>
 <p><strong>Hobbes y “El Tetragrámaton”</strong></p>
 <p>   Hobbes considera la sociedad compuesta por una multiplicidad de seres individuales conducidos por sus pasiones, explicando luego la transición de este individualismo atomista a la construcción de un cuerpo social artificial, o estado, de carácter absolutista. </p>
 <p>   El estado natural era considerado el previo a la organización de la vida social. Los seres humanos son considerados iguales por naturaleza en facultades mentales y corporales, produciéndose, también de una forma natural, la compensación entre las deficiencias y las cualidades con las que la naturaleza ha dotado a cada cual. Cada ser humano busca su propia conservación, lo que da origen a la competición. Al no existir en este estado previo distinciones morales objetivas, se produce un estado permanente de guerra de todos contra todos, dado que no se poseen limites para controlar las pasiones, e incluso juzgarlas. &quot;El hombre es un lobo para el hombre&quot;.<br />
   Ahora las causas que mueven a los seres humanos a unirse en un cuerpo social señalan la inseguridad a la que se ven sometidos los seres humanos en estado de naturaleza, que comprende la existencia de leyes. Las leyes de la naturaleza no se cumplen, dada su oposición a nuestras pasiones, a menos que haya un poder coercitivo con capacidad suficiente para imponernos su cumplimiento. Por lo tanto es necesario un poder coercitivo, público, respaldado por la fuerza y capaz de castigar a los infractores.<br />
   La organización en sociedades responde fundamentalmente a la preservación de la propia vida y a la garantía de una existencia dichosa. Los seres humanos sólo pueden alcanzar una convivencia social estable por medio de un pacto, en el que se genera, simultáneamente, la sociedad civil y un poder común capaz de obligar a todos al cumplimiento del pacto suscrito. Para llevarlo a cabo los seres humanos deben asumir la transformación de sus derechos que consiste en la renuncia a los mismos, con el fin de aunar todas las voluntades en una sola. Elegir un representante que será el detentor de todos los derechos a los que ellos han renunciado, lo que supone la creación de una persona artificial o ficticia, que, al poseer todos los derechos, no podrá estar sometida a ninguna restricción. Esta transformación de derechos se realiza mediante un pacto en el que cada cual renuncia a sus derechos en favor de un tercero. Ese tercero recibirá el nombre de soberano y los demás serán los súbditos.<br />
   La soberanía emanada del contrato es inalienable una vez concedida, no se puede cambiar la forma de gobierno ni repudiar la autoridad. El soberano, no podrá ser castigado por sus súbditos, ya que no hay ninguna relación contractual entre los súbditos y el soberano. El soberano queda &quot;fuera&quot; del contrato. El poder es absoluto, el soberano asume todos los poderes en general.</p>
 <p>   En el caso de “Tetragrámaton” se puede ver el ejercicio del poder según los preceptos de Hobbes. Hay una relación heterónoma entre el soberano “El padre” y sus súbditos. Los súbditos son tratados como una generalidad, el delito vale por sí no en relación al infractor, todos son iguales ante el consejo. El consejo se configura como el Leviatán, posee un poder absoluto que infringe una ley a cumplir y en caso de no hacerlo un castigo que cuenta con la muerte. <br />
   En esta sociedad distópica la libertad esta devaluada en detrimento del derecho a la conservación de la vida. Así es como se coartan las emociones en pos de una supervivencia de la raza autómata. El poder es concentrado para generar una figura que imponga el miedo y el control. <br />
   Finalmente las dos fracciones se enfrentan para dar lugar a la transformación del estado. El poder autoritario cae ante la demanda de la sociedad por recobrar su estado natural de libertad.<br />
 </p>
          </div>
     
        </div>
      </div>
      <div id="banners">
        <?php include("inc/banners.php"); ?>
        <?php include("inc/archivo_arteyliteratura.php"); ?>
      </div>
    </div>
  </div>
<?php
  include("inc/footer.php");
?>