<?php
  include ("inc/head.php");
  $GLOBALS['interna'] = true;
  include ("inc/header.php");
?>
    <div id="centro" class="arteliteratura">
      <div id="izquierda">
        <div id="arteliteratura">
          <div class="barra_titulo">
            <span></span>
            <h1>Arte &amp; Literatura</h1>
            <span class="tail"></span>
          </div>
          <div id="header_slider">
            <img src="uploads/escritura.jpg" title="Header entrevista" alt="Torre de Babel" />          </div>
          <div id="texto_entrevista">
 <p>Una de las características esenciales de la escritura borgiana es, sin duda, la intertextualidad. Esta disposición a exhibir la presencia de un texto dentro de otro, o de la revisión de un mito, también es propia de Aballay. La pluralidad discursiva, que emplea tanto Borges como di Benedetto, impone la reescritura dentro de la literatura. Una reescritura que enlaza una tradición de textos constitutivos de determinados espacios culturales con la literatura actual y existente, en un diálogo inagotable que mantiene como premisa recrear la literatura a partir de un nuevo orden. A través de una revisión de la literatura, que abarca todo género y tradición, proveer una nueva lectura de aquella región pampeana constituida como mito.</p>
 <p>El Sur, exhibe la condensación de dos linajes en su protagonista Juan Dalhmann. Cada una de estas estirpes concentra un espacio cultural  particular.  El mundo paterno de Dalhmann toma forma en su abuelo alemán, pastor de iglesia evangélica, simbolizando aquel espacio de orden vinculado estrictamente al Libro. El mundo materno, el mundo de los Flores, se asocia con el criollismo de aquellas primeras colonizaciones, que imprime una visión singular del Nuevo Mundo como lugar utópico y de lo maravilloso, que se impuso a lo largo del descubrimiento de América y sus primeras islas. Francisco Flores muere en la frontera de Buenos Aires lanceado por los indios. Flores reivindica el mito del heroísmo a través de la construcción heroica de un pasado del cual sólo se conserva el casco de una estancia en el Sur. Los restos de esa “larga casa rosada que alguna vez fue carmesí”, nos acercan a una fecha específica, donde tras derrotar a Lavalle, Juan Manuel de Rosas accede al gobierno de la provincia de Buenos Aires  y logra constituirse en el principal dirigente de la Confederación argentina (1835-1852).  Para este entonces, la llanura pampeana bonaerense había estado sometida al dominio blanco apenas en una franja estrecha junto al Paraná y el Río de la Plata. Desde entonces, la frontera se  adelanta hasta una línea que pasaba aproximadamente por las actuales ciudades de Balcarce, Tandil y Las Flores . Durante los primeros años de su segundo gobierno, la política de Rosas para con los indios alternaría tratados de paz y donaciones con campañas de exterminio. Se puede aducir que la estancia que hereda Dalhmann pertenece a este período, en el cual las casas se pintaban de colorado con sangre de toro para ahuyentar enemigos. Este dato indica que fue construida posterior a un desplazamiento indígena y da fe de conquista, donde las tierras eran repartidas entre los soldados y financistas de campaña, que posteriormente, al no poder sostenerlas, eran vendidas a ingleses.  De este modo, Borges recupera un mito pampeano, no como factor económico, pero sí desde el lugar del heroísmo. </p>
 <p>Entre la confluencia de linajes Dalhman elige “ese antepasado romántico, o de muerte romántica” que se nutre de la tradición criollista. Borges pasa a enumerar una lista de elementos que son parte de mitificaciones pampeanas anteriores, a las cuales adhiere Dalhmann. En primer lugar menciona un daguerrotipo, primer procedimiento fotográfico que data del año 1839. Existen evidencias, que marcan la aparición del primer daguerrotipista en España, el abate francés Louis Compte, que viajaba de la fragata mercante Oriental, que se encontraba en viaje dando la vuelta al mundo. Las demostraciones de Compte en Río de Janeiro y Montevideo en 1840 son una referencia en la historia del daguerrotipo en América del Sur . El daguerrotipo representa una invención que incursionó con soberana importancia en la construcción mítica de América del Sur por parte de Europa. Borges también menciona la espada, la barba y estrofas del Martín Fierro que  remiten directamente a tradiciones gauchescas anteriores. En el cuento también sobrevuelan referencias a otras obras literarias como Los cielitos de Bartolomé Hidalgo, en cuyos cielitos impera el tono agresivo contra los enemigos de la patria, o el Facundo: Civilización y Barbarie,  donde Sarmiento absorbe la imagen de los viajeros ingleses del siglo XVIII y XIX que atraídos por las imágenes que les llegaban, enviaban hombres con motivos de negocio y exploración. Tanto en El Sur, como en El evangelio según Marcos, encontramos La Pampa descripta como un espacio sin límites, emparentada con el océano. </p>
 <p>El oficio de Dalhmann como secretario de una biblioteca municipal, evidencia su afán erudito y su corte letrado. Este afán se intensifica con la ansiedad por leer Las Mil y una Noches de Weil para compararlo con la traducción popular. Omitiendo intereses particulares del autor, se transparenta la relación entre el gusto popular, entre Flores como prototipo romántico de la cultura nacional argentina de los últimos siglos, y los letrados; aquellos que sostienen el gusto popular. Distraído por su lectura, sufre un accidente y termina hospitalizado. Este es el instante del relato donde comienzan a confluir el mundo urbano y el mundo rural (el mundo del deseo). “A la realidad le gustan las simetrías y los leves anacronismos”, frase que despierta sospecha en el lector y abre el texto a una doble interpretación, comprendiendo una retórica realista y una fantástica que se expresa en el manejo de la temporalidad. El narrador se involucra en un doble proceso. Por un lado da cuenta de una dilatación temporal, donde “ocho días pasaron, como ocho siglos” y por otro, remite a horas y momentos exactos del día. En el viaje en tren hacia la estancia, es donde se manifiesta con mayor claridad esta duplicidad  retórica de dos hombres, aquel “que avanza por el día otoñal y por la geografía de la patria, y el otro, encarcelado en un sanatorio y sujeto a metódicas servidumbres”. La descripción de los paisajes que Dalhmann observa a través de la ventana, se acerca a aquella mítica tradición pampeana. Frases como: “sueños de la llanura”, “su directo conocimiento de la campaña era harto inferior a su conocimiento nostálgico y literario”, “todo era vasto, pero al mismo tiempo era íntimo y de alguna manera, secreto”, son ejemplos de esta vacilación semántica que nos permite abordar el texto desde una  doble retórica y al mismo tiempo dar cuenta de una tradición romántica que circunda  El Sur. Cuando Dalhmann ingresa al almacén testigo de su duelo, algo “en su pobre arquitectura le recordó un grabado en acero, acaso de una vieja edición de Pablo y Virgina”.  Pablo y Virginia, escrito por Jacques-Henri Bernardin de Saint-Pierre, autor francés prerromántico, narra un idilio que transcurre en la isla de Santa Elena, en el que se puede apreciar con claridad su ideología rousseniana que pretende volver al hombre a su estado primitivo y natural. Este tipo de referencias nos envuelven en una sensación de melancolía y refugio en un pasado mitificado, en relación con la isla como espacio utópico por excelencia. “Dalhmann pudo sospechar que viajaba al pasado y no al sur”. Borges escribe: “estaba como fuera del tiempo, en una eternidad”. El sur de Dalhmann responde a una idealización del Sur en la cual confluyen tradiciones anteriores. <br />
   Dentro del almacén, Dalhmann registra al viejo sentado y encuentra en éste todas aquellas peculiaridades de la literatura gauchesca. Dalhmann se dice: “gauchos de esos ya no quedan más en el sur”. El viejo materializa la idea mítica del gaucho aguerrido y el culto al coraje. En este espacio Borges aborda la construcción del duelo.  Dalhmann lo asume  y cumple con su estirpe romántica. Las razones por las que Dalhmann accede son precisas. Por un lado el reconocimiento por parte del pulpero que lo llama por su nombre obligándolo a hacerse cargo de su destino e identidad. Por otro, el cuchillo que le arrojan para pelear, arma que “no serviría para defenderlo, sino para justificar que lo mataran”. Es el Sur idealizado de Dalhmann aquel que resuelve que debería pelear y hacerse cargo de su destino, de su pasado. Es en este preciso instante donde se evidencia una relectura del Martín Fierro.</p>
 <p>El evangelio según marcos, toma lugar en la estancia de Los Álamos, en el partido de Junín. Una estancia  grande y abandonada de fines del siglo XIX, similar a la estancia de El Sur. Una vez más, su protagonista Espinosa,  representa el punto unión de dos linajes adscriptos a espacios culturales dispares. Su padre, un librepensador, instruido en la doctrina de Herbert Spencer y su madre que antes de marcharse le pide que rece el Padrenuestro y haga la señal de la cruz. Esta ascendencia enfrenta dos teorías en continua pugna, el evolucionismo y el creacionismo; sin embargo, Espinoza expresa una indiferencia casi absoluta y poca atracción por la competencia. <br />
   En el tercer párrafo del texto, Borges narra como Espinosa comienza a instruirse en cuestiones del campo. El contenido y la estética es similar a los recorridos autobiográficos del naturalista y escritor Hudson, nacido en Argentina que luego emigró a Inglaterra. El recuerdo de éste opera para construir una referencia explícita cuando Borges escribe “…la metáfora que equipara la pampa con el mar, no era, por lo menos esa mañana, del todo falsa, aunque Hudson había dejado escrito que el mar nos parece más grande…”. A través de Hudson, Borges indaga en un clima descriptivo particular y por supuesto contribuye a reevaluar la extensión de La Pampa como aquél espacio sin límites, al igual que en El Sur en relación con el Facundo. </p>
 <p>Un desborde del Salado, a causa de la lluvia, desemboca en una inundación que lleva a los Gutre a convivir junto a Espinoza. La conversación con los Gutres es pobre. No son meramente analfabetos; sino que se ven privados de  poder explicarse verbalmente. En una Biblia familiar en inglés (típica de países protestantes), Espinosa encuentra una crónica de la vida de Gutres que termina en 1870. La crónica revela que los Gutres, antes Guthries, inmigran a Argentina desde Escocia, se posicionan como labradores y se relacionan con los indígenas de la región. En este punto, el autor hace resonar el mito de la Odisea.  Borges también hace mención de un libro presente en la biblioteca de la estancia, Tabaré, de Juan Zorilla de San Martín. Poema épico uruguayo que trata del idilio amoroso del indio Tabaré y la española Blanca teniendo como fondo la dura guerra trabada entre castellanos y charrúas en el territorio del actual Uruguay en el final del siglo XVI. Los Gutre encarnan este mito que como colonizadores se funden entre la población indígena. Pierden su Inglés y gran parte de su Español. Colonizados en Escocia y convertidos en colonizadores en el Nuevo Mundo, ahora representan un hibrido que no se corresponde ni con el hombre moderno ni posmoderno. <br />
   Mientras que la inundación avanza, Espinosa decide leerle a la familia. Elige Don Segundo Sombra, pero esta elección es desafortunada debido a que el padre afirma que él “había sido tropero y no le podía importar las andanzas de otro”. De este modo Borges aniquila el mito, el gaucho ahora es recero, es parte del sistema capitalista de producción. Espinosa entonces decide leerles  el Evangelio según San Marcos “para ejercitarse en la traducción y acaso para ver si entendían algo”. Especula que el entusiasmo de los Gutres se debe al “duro fanatismo del calvinista” que dejaron en Escocia pero que todavía “llevan en la sangre”, y a las “supersticiones de la Pampa”. <br />
   Los sucesos que narra el relato a continuación tienen como referente los textos bíblicos: la mencionada inundación, el uso de la medicina para curar el cordero de la hija menor, el propio gesto de la oratorio que ejerce Espinosa, la barba que se deja crecer, sus treinta y tres años. Espinosa personifica a Cristo bajo los ojos de los Gutres. La posibilidad de confundir la realidad y la ficción, se debe a que Espinosa lee desde un espacio cultural y la familia percibe de otro, desde el abismo. Espinosa surge como un ser omnipotente que recuerda a otro anterior.  De esto lo advierte su padre: “los gauchos suelen ignorar por igual el año en que nacieron y el nombre de quien los engendró”. Los gauchos tienen una memoria tan pobre que confunden historias distantes que tomaron lugar en tierras extranjeras con su propia memoria inmediata. Con la aspiración de ser salvados por el agua, los Gutre nos hacen espectadores de dos sacrificios, la muchacha virgen que se acuesta en la cama de Espinosa y el propio sacrificio de éste. El cuerpo y la sangre. </p>
 <p>La particularidad de Aballay, radica en la revisión de dos mitos, uno cristiano y otro clásico, que confluyen en la constitución del propio mito de Aballay. Como en Borges, predominan referencias tácitas a tradiciones anteriores del mito pampeano, inclusive el texto lee: “Se nombra a Facundo, por una acción reciente. (“¿Qué no es que lo habían muerto, hace ya una pila de años?...)”. Esta referencia explicita del Facundo invoca la constitución y reconstitución del mito pampeano. El propio espacio por el que Aballay deambula montado a caballo, también da cuenta de la avasallante extensión pampeana que se manifiesta en los cuentos borgeanos. </p>
 <p>El disparador de acción del relato, parte de una interpretación literal de una historia basada en los estilitas contada por el cura a Aballay. Presenciamos una cercanía con los Gutres de la estancia Los Alamos, salvo que mientras Borges exalta la diferencia de dos mundos, Aballay crea preguntas en el sacerdote sobre el modo de vida de estos estilitas, que nunca se preguntó. Esto se percibe como un intento de acercar los dos mundos. Los estilitas eran monjes cristianos solitarios que vivían en el Medio Oriente a partir del siglo V y tenían la particularidad de transcurrir su vida de oración y penitencia sobre una plataforma colocada en la cima de una columna (stylos en griego) permaneciendo allí durante muchos años e incluso hasta la muerte, con el objetivo de alejarse de las tentaciones. Aballay es un hombre de a caballo y decide montar como penitencia por dar muerte a un hombre frente al hijo de la víctima. </p>
 <p>El primer punto de conflicto se presenta cuando Aballay, atraído por el humo, recibe “el bocado hospitalario que nunca se le niega al que hace camino”. El protagonista cobra conciencia que aquel gesto podría volverse necesidad de todos los días. El orgullo gauchesco, propio de tradiciones literarias anteriores, choca con Dios. Aballay aprende la diferencia entre la hospitalidad y mendigar. Es el propio orgullo de un gaucho el que lo evade de la situación de mendigo, pero por necesidad deberá pedir todos los días. En diversas ocasiones paga con los cobres de su rastra para no mendigar o practica el trueque. <br />
   En la pulpería ç se repite la misma lógica del duelo de El Sur. El asador lo desafía: “el que no se pone, no come”. Aballay asume el riesgo, apuesta y gana, pero no desciende del caballo para cobrarse sus monedas porque rompería su penitencia y tampoco pide a alguien que lo asista, ni se corre por la barriga del animal, debido a que sería humillante y provocaría risas. Nuevamente el orgullo gauchesco se hace manifiesto, y nos remonta al mismo hybris que presenta Martín Fierro. Este episodio es aquel que le hace nacer famas que “el no se entera” y que inicia la constitución del mito de Aballay. En su siguiente encuentro con un grupo de indios se cristaliza la mirada del indio respecto del blanco, y las palabras “hombre-caballo” de la boca de estos indios, traen a colación aquel mito clásico del Centauro que también refleja la llegada de los españoles a América montando a caballo. Nace el mito de Aballay como hombre a caballo y gaucho que no mata, gaucho que se opone “resistencia a los malentendidos”. El texto da cuenta de su creciente popularidad que recorre la región, alcanzando el estatuto mítico: “le reconocen sus famas, que le han crecido, sin él saberlo…”. </p>
 <p>En su encuentro con el hijo de aquel padre que asesinó, Aballay  ya tiene el aspecto de un estilita, di Benedetto escribe: “podría parecer un santón”, “está en harapos”, “trae templados los ojos, pero decididos”. Está conversión, tanto física como espiritual asemejándolo con los estilitas y anacoretas, expone la apropiación de un mito para reconstituirlo bajo una nueva forma.  El niño que viene a enfrentarlo cierra perfectamente este círculo donde uno paga y el otro venga. Aballay “sabe que el niño, hecho hombre, viene a cobrarse”. La mención al testigo nos da cuenta de una idea de Sino que atraviesa la obra, al igual que en El Sur, done Aballay debe hacerse cargo de su destino, y  que aquella penitencia a caballo, no era más que una larga espera y purgación, antes de asumir su final. El niño lo reta: “Señor, eche pie en tierra”, máximo desafío para Aballay, un Aballay que  lo “padece”  y  no pretende evidenciar los motivos de su negación debido a que parecería “un disimulo del miedo”. El orgullo gauchesco se mantiene latente a lo largo de toda la obra. El duelo se lleva a cabo a caballo, al igual que aquellos retos del medioevo y Aballay enfrenta un dilema, no querer volver a matar, es por ellos que pelea con una caña, y al lastimarlo superficialmente termina bajando por culpa y abrazando la muerte. </p>
 <p>La conciencia histórica y cultural en estos textos es de vital importancia, los mitos o pasajes, como en El evangelio según Marcos,  son recreados en el aquí y ahora de modo original, bajo la pauta de que el uso frecuente y la revisión y relectura de viejos motivos, antiguos mitos y tradiciones, son un forma de poner de manifiesto que el quehacer literario no es una búsqueda de lo nuevo, de alcanzar una originalidad como se entiende tradicionalmente; sino, en explorar nuevas formas de percibir lo viejo, el ser creativo con la literatura existente. Este trabajo lleva al lector a sumergirse en lo no dicho del texto. A encontrar el sentido oculto de las palabras y su conjunto. La reescritura de mitos y tradiciones pampeanas predecesoras, adquiere formas reflexivas, donde no se explica ningún misterio, sino se lo resalta. Estos cuentos permiten una ponderación del lector, estableciendo una función comunicativa particular con el lector, donde le tipo de narración hace reflexionar sobre la escritura y lo narrado, en cual la alusión presenta cualidades reveladoras, en cuya trasfondo, el tema principal es la creación de literatura basada en la literatura misma, tomando como artificio el acto de reescribir lo ya escrito. La extensión pampeana que configuran estos mitos no es únicamente literal, la construcción remite a una prolongación de la pampa a través de tradiciones, mitos, géneros, culturas que se constituyen y reconstituyen bajo nuevas formas para dar cuenta de esta extensión inagotable que presenta el mito pampeano y la literatura. </p>
</div>
     
        </div>
      </div>
      <div id="banners">
        <?php include("inc/banners.php"); ?>
        <?php include("inc/archivo_arteyliteratura.php"); ?>
      </div>
    </div>
  </div>
<?php
  include("inc/footer.php");
?>