<?php
  include ("inc/head.php");
  $GLOBALS['interna'] = true;
  include ("inc/header.php");
?>
    <div id="centro" class="arteliteratura">
      <div id="izquierda">
        <div id="arteliteratura">
          <div class="barra_titulo">
            <span></span>
            <h1>Arte &amp; Literatura</h1>
            <span class="tail"></span>
          </div>
          <div id="header_slider">
            <img src="uploads/fritz_lang.jpg" title="Header entrevista" alt="Torre de Babel" />          </div>
          <div id="texto_entrevista">
 <p>Es como si los personajes de Lang estuvieran rematados por la triste búsqueda de una redención inaccesible. Como si algo les faltara, algo exterior que logran apresar sólo de manera aparente y provisoria. Los protagonistas caminan este devenir borracho que tropieza con puertas y ventanas de falsas salidas. Lang es un gran arquitecto de la impureza, capaz de sostener una escena entera coreografiando el abrir y cerrar la puerta de una nevera. Me remito a la escena de Clash by night (1952) en la que participan Jerry D´Amato, su padre y su tío, en casa de Jerry. El conflicto familiar se extiende a la materialidad de la cocina. La puerta de la heladera es una prolongación dramática que marca el ritmo, las interrupciones y sobresaltos que estructuran la secuencia. Las verticales separan y dividen el cuadro en compartimientos estancos. Toda una geometría del cuadro. Ya sean las redes de pescadores o las ropas colgadas al sol, entre las cuales emergen Marilyn Monroe y Barbara Stanwyck en Clash by night, el cuerpo es agente de segmentación y embrollo algebraico. El ambiente geométrico-formal mina contra la asunción perceptiva singular del Uno perdido. Estos dos personajes surgen de un medio arácnido. Dos potencias en complicidad, la fuga  de la isla en Marylin Monroe, el repentino asentamiento disconforme de Barbara Satnwyck. Fuerzas que desarrollan una virtualidad a futuro, a seguir, imposibilitada por las constricciones lineales del entorno. El ciudadano medio avanza a los tumbos, eludiendo la ley y atosigado por las consecuencias morales de una pesquisa pasional. Tanto en Edward G. Robinson -en Scarlet Street (1945) y The woman in the window (1944)- como en Paul Douglas -en Clash by night-, Fritz Lang complejiza un personaje arcaico y laxo. El primero en busca de aventuras neuróticas  que lo conducirán a la perdición. El segundo, en caza de la familia prototipo del sueño americano. Robinson y Douglas son las dos caras de una misma moneda. En ambos la nacionalización de una quimera intransitable acarrea las mismas secuelas erosivas. Aquella inocencia madura se agudiza cuando las mujeres eidéticas son el centro de atención. El juicio moral que pesa sobre las señoritas langeanas despunta en temeridad compasiva cuando actrices como  Anne Baxter –en The Blue Gardenia (1953)- se convierten en víctima irresoluta; pero, se dilata en perversidad al asumir el rol de femme fatale, sea Joan Bennett en Scarlet Streets o Barbara Stanwyck en Clash by night. La mujer siempre es víctima, ya de los impulsos homicidas o traumas secretos de su consorte, ya de las telarañas amorosas de Dan Duryea, o del desencanto de sueños evanescentes. </p>
 <p>¿Qué es lo que hay tras la puerta? En Secret beyond the door (1947), la esperanza de un triunfo provisional del hombre sobre su mundo por medio de ocasionales reconciliaciones con las fuerzas en juego. Entendimiento de hombres con hombres, con su experiencia y sociedad. De esta forma Celia Barret se reconcilia con su reciente conyugue Mark Lamphere, a pesar de descubrir su presente sociópata y sus arrebatos homicidas. Todo por medio de una liberación psicoanalítica espontánea de un trauma de la infancia. En Scarlet Street,  la concientización de leyes eternas que gobiernan la existencia humana. El hombre resignado y extraviado en lo sombrío. Christopher Cross fue engañado, estafado y extorsionada para sellar su destino asesinando en emoción violenta. No importan los reveses que sufra la carne floja de Edward G. Robinson, el crimen a sangre fría es condena ético-moral eterna. </p>
 <p>Abundan los reflejos espejados a lo largo del primer acto de The Blue Gardenia. Espejos que proyectan como pantallas de LCD la contracara de la imagen. Una imagen múltiple y consonante compuesta por fragmentación dentro de la unicidad. Ya no basta con ver el rostro de personajes grises, los espejos enmarcados amplifican  y espacializan un campo tridimensional de nucas, espaldas y movimientos ocultos. Todo está ahí al alcance de las superficies cristalinas. Veinte kilómetros de visibilidad. En La Gardenia Azul, Nat Cole King interpreta y canta al piano “Blue Gardenia, bajo un espejo que devuelve desorientación y marea. Como si Lang prefigurara el “quiero ver todo” televisivo. Esta transfiguración estilística se quiebra cuando Anne Baxter hace estallar en añicos el espejo de la casa de Harry Prebble luego de ser atacada. El trasfondo de la escena es ahora secreto, un fondo de horror y asesinato sobre el cual se despliega la belleza de las divas hollywoodenses. Quizás sea el horror de la guerra y los fantasmas de los campos de concentración los que acechan el aura mesiánica de promesas de ensueño clarividente. </p>
 <p>David Oubiña, escribe en Puro cine discutiendo con A favor de un cine impuro de André Bazin: “Es el cine el que desborda sobre otras artes y abre surcos para desarrollar en ellas una idea de lo cinematográfico”. Hay una relación estrecha entre la cinegenia de Lang y otras disciplinas artísticas. La pintura es disparador narrativo de fantasía en The woman in the window cuando Edward G. Robison, hipnotizado por el retrato de Joan Bennett en una vidriera pública, se entrega a un sueño de aventura y asesinato. Condena e incomprensión en un medio que evoluciona con independencia de su consumidor, en Scarlet Street  -a través de las pinturas que John Decker  confeccionó con cierta reminiscencia a las obras de Henri Rousseau-. El talento creador en las pinceladas de Christopher Cross, es razón de ignorancia y motivo de fraude en un mercado del arte preocupado más por una historia a vender que por lo que se esconde detrás del genio. Motivo de seducción y homicidio de un retratista, en The Blue Gardenia. Todo lo que queda en la escena del crimen son los retratos espectrales que vigilan un principio de justicia divina socavado por la noticia periodística ¿Serán los fantasmas del exilio los que colman el mundo de Lang? En La Gardenia Azul todavía nos encontramos en la época de la pequeña ciudad amenazada por la existencia de enemigos cercanos que provocan la vigilancia del ciudadano por el ciudadano. Un pueblo de personalidades lucha contra la presión interna desindividualizadora de la pequeña ciudad. La noticia y el periódico son agentes de expiación. Emisarios de vigilancia que comercializan el color poético y el tono intimista del retrato y la hazaña. Toda aquella tradición insular utópica es invertida en Clash by night. La isla es principio de miseria y condena humanitaria.  Los barcos pesqueros que suscitan las vistas de Saintes-Maries de Willem Vincent  van Gogh; y, los paisajes vaporosos al estilo de Claude Monet, hacen que, en palabras de H. Belting en La transparencia del medio, “la imagen que surge en el espectador sobrepase las fronteras mediales y se componga de una síntesis entre imágenes de la percepción e imágenes del recuerdo”. Lang libera los 24 cuadros por segundo a una imagen en continua comunicación y reelaboración estético-mediática. </p>
 <p>Si una de las osadías del cine moderno es la interpelación por medio de la mirada para suscitar aquel fuera de campo imposible de actualizar –la sala de cine-, Lang espectaculariza la sala oscura provocando en el espectador la mirada hacia atrás, la mirada por sombre el hombro  y el miedo a la foto sorpresa. En The Blue Gardenia, Norah Larkin se sienta a contemplar la fotografía de su amado ausente antes de leer la carta que firma su abandono. Como si después de intimidarnos con un llamado directo a la autoconciencia espía, nos refugiara en una complicidad habitacional penosa con el personaje-espectador fotográfico. Este juego inter-espacial que abre Lang en The Blue Gardenia, lo profundiza en Clash by night. Si en la secuencia comentada, el espacio se repliega y análoga a la situación espectatorial, Clash by night  fomenta un principio de abducción. Lang filma la sala de proyección de un cine pueblerino donde Earl  Pfeiffer manipula un proyector de 35 mm mientras conversa con Mae y Jerry; por la ventana podemos ver parcialmente la película proyectada en la pantalla diegética. Es la sala del espectador la abducida a un espacio fantasmal en donde el filme es antesala virtual y pantalla-presente. Un vacío de Haluros de plata que el espectador se ve forzado a suplir. La carne granulada.</p>
 <p>Fritz Lang es un éxodo sideral al espacio de la Tierra perdida. <br />
 </p>
 <p>Corpus seleccionado:</p>
 <p><strong>“The woman in the window” (1944)<br />
   “Scarlet Street” (1945)<br />
   “Secret beyond the door” (1947)<br />
   “Clash by night” (1952)<br />
   “The Blue Gardenia” (1953) </strong></p>
 <p></p>
          </div>
     
        </div>
      </div>
      <div id="banners">
        <?php include("inc/banners.php"); ?>
        <?php include("inc/archivo_arteyliteratura.php"); ?>
      </div>
    </div>
  </div>
<?php
  include("inc/footer.php");
?>