<?php
  include ("inc/head.php");
  $GLOBALS['interna'] = true;
  include ("inc/header.php");
?>
    <div id="centro" class="arteliteratura">
      <div id="izquierda">
        <div id="arteliteratura">
          <div class="barra_titulo">
            <span></span>
            <h1>Arte &amp; Literatura</h1>
            <span class="tail"></span>
          </div>
          <div id="header_slider">
            <img src="uploads/hermanos_dardenne.jpg" title="Header entrevista" alt="Torre de Babel" />          </div>
          <div id="texto_entrevista">
 <p>La importancia del cine de los hermanos Dardenne radica en su necesidad por mostrar el contraplano de los países centro-occidentales de Europa, cohesionados y a la vez fortalecidos por la creación de la unión europea. Unión que propicia y acoge la integración en común de los pueblos y de los estados de Europa, pero a la vez deja un resabio de personajes marginales en lucha constante por ser parte de un sistema que hace de la exclusión la base de su funcionamiento. Irónicamente en el 2011 la Unión peligra en desaparecer, mientras países como Alemania se vieron beneficiados generando esta utopía de unión, otros quedaron endeudados con las potencias que tan gentilmente otorgaban créditos para la subsistencia de estos. Como un deja vu de lo sucedido con la convertibilidad y el posterior default del 2001 en la Argentina, Europa hoy atraviesa la misma situación. Los Dardenne ya vislumbraban estas diferencias inasibles desde el 99 con su primer largometraje “Rosetta”. Sus tópicos están trabajados a modo de denuncia de lo diametral de las relaciones sociales en la nueva Europa.</p>
<p>Estos realizadores arremeten con los problemas tácitos y urgentes de los que son parte gran número de europeos: la desocupación y la falta de oportunidades laborales en “Rosetta”, la inmigración ilegal y las mafias que se hacen detrás en “El silencio de Lorna”, todos tópicos propios de la marginalización de las grandes ciudades.</p>
<p>El siguiente ensayo se pretende un estudio sobre la filmografía de los hermanos Dardenne tratando de evaluar su impronta en el cine, buscando un lugar para una estética y retórica que no esta del todo categorizada ni evaluada. Si bien su cine ya tiene más de una década no hay una teoría concreta para pensarlo. Su cine irrumpe con una problemática de tipo narrativa tanto como estética. ¿Dónde puede posicionarse el cine de los Dardenne? ¿Se trata de ficción o documental? ¿Qué relación construyen con la realidad? ¿Cómo pensar el cine de los Dardenne en relación a un neorrealismo tardío? ¿Estamos ante una nueva imagen?</p>
<p><strong>Entre la ficción y el documental, puja por una nueva imagen</strong></p>
  <p>El documental más que un género es una modalidad discursiva histórica. Con el correr de los años fue mutando hacia una primera persona y hacia una subjetividad propia del autor, lejos quedaron los documentales pretendidamente objetivos que se definían por establecer un saber sobre el mundo. El documental en primera instancia se definió por oposición a la ficción. El saber del documental surge de la conciencia fotográfica que presupone que aquello que vemos es huella de lo real, conciencia del haber estado ahí de las cosas, por el carácter indicial de la fotografía. Esta conciencia fotográfica no se presta a la ficción, en la ficción el carácter indicial de la imagen esta en función de la historia que se nos narra, y la potencia que puede tener la imagen como testigo de lo real sirve sólo para dar mayor verismo al universo ficcional, pero claramente no lo define. Justamente la ficción se presta a la ilusión donde lo real puede ser olvidado en pos de un ingreso en la diégesis propuesta. Así es como mientras el documental explota el carácter indicial de la imagen la ficción lo niega.</p>
<p>  En sus inicios el documental se presentaba como una forma de estudio de un objeto determinado. A través del documental se nos presentaban una serie de imágenes-registro de lo real, que servían de estudio de determinados fenómenos. La imagen era pulcra en términos técnicos, la intervención estaba clausurada en pos a la necesidad de transmitir una sensación de que eso que estábamos viendo realmente había sucedido frente a la cámara. Este es el caso de “Nanook el esquimal” (Robert Flaherty 1922) a través de sus imágenes el espectador obtenía una noción del hombre en la naturaleza, forjando una mirada sobre el otro y su mundo. Posteriormente con el documental de la escuela inglesa, se termina de conceptualizar a través de lo propuesto por Grierson que el documental es “interpretación y creación de realidad”. Grierson ingresa a la figura del trabajador en el documental. Ya no se trata de los grupos étnicos propuestos por Flaherty sino  que el proletario emerge como necesidad de configurar la imagen de la sociedad presente. Ambos igualmente hacían de la imagen un lugar desprovisto de esteticismos, donde la sobriedad era la modalidad justa para representar el mundo, noción clásica del documental.
  Con la llegada de la modernidad la concepción positiva de lo documental en su capacidad de atestiguamiento es puesta en tensión. Godard cuestiona el documental positivo clásico, poniendo en duda el valor de la imagen como real, exponiéndola como construcción ideológica-política. El documental no puede pretenderse imagen transparente de su objeto, porque esa imagen es producto y productora de una impresión de realidad atravesada por la ideología. Así es como la imagen resulta de una mediación conciente, opaca con respecto a su objeto. El cuestionamiento de la imagen justa propuesta por Godard hace que el documental pierda ese matiz de veracidad y objetivismo, la figura del autor como constructor de esas imágenes viran al documental hacia una primera persona que con el correr de los años se iría exaltando hasta llegar a su máximum en “Tarnation” (Jonathan Caouette 2003).Lejos quedo el idealismo baziniano de la imagen, Caouette pone fin al documental clásico ubicándolo en su polo opuesto, el autor no sólo es el encargado de construir la imagen sino que se ha vuelto la misma imagen.</p>
<p>  Paralelamente la ficción fue haciéndose de la retórica y la estética del documental. Con el surgimiento del neorrealismo ya no seria igual la manera de filmar lo real dentro de la ficción. Los Dardenne deudores de esta corriente explotan la estética y retórica  documental como modo de atestiguar lo más fidedignamente posible una realidad adversa que es necesario denunciar para así cambiarla.</p>
<p>  La temática parte de una realidad desconocida, la parte de Europa que no goza del modelo económico y político planteado por la Unión Europea. El objeto de estudio es la otredad negada ¿Cómo retratarla? ¿Cómo ser justo con la imagen? La justesa aflora con los recursos documentalistas que explotan: el plano secuencia, la cámara de video, el seguimiento constante de sus personajes, el sonido directo; la menor intervención posible en el universo a registrar. Estas decisiones estéticas se asocian al neorrealismo, y también la ética a desarrollar en sus personajes puede leerse desde el mismo código. Sin pecar de idealistas bazinianos, concientes de los efectos de la imagen transparente, construyen con su imagen una denuncia que repercute directamente en la política social belga, su cine encuentra así su causa y consecuencia. </p>
  <p><strong>Del neorrealismo italiano al cine de los hermanos Dardenne 
    </strong></p>
  <p>Cuando Gilles Deleuze se preguntaba por el cine neorrealista en su introducción a la imagen-tiempo, daba con que este cine apuntaba a una nueva forma de realidad, donde no se representaba o reproducía lo real sino que se apuntaba a él. Un real a descifrar ambiguo, de ahí la preferencia por el plano-secuencia. Deleuze toma la secuencia de “Umberto d” (Vittorio de Sica 1952) para desarrollar la teoría de la “situación óptica pura”, situación corriente que en el transcurrir de una serie de gestos maquinales que obedecen a esquemas sensoriomotores simples, hacen surgir a esta imagen desprovista de reacción y respuesta. A través de esta teoría se puede pensar el cine de los Dardenne. En el caso de Rosetta la vemos a ella obedecer a una serie de rituales automatizados que transmiten ese apatismo y maquinismo con la que ella se desenvuelve en el medio. Justamente en este automatismo la situación se vuelve susceptible de perder su equilibrio, cuando Rosetta recibe afecto de su compañero de trabajo ella no sabe como actuar y lo arroja al piso. Tanto en los personajes del neorrealismo como en los personajes de este cine la reacción esta clausurada por ese automatismo en el que se desarrollan habitualmente, en el momento que emerge algo que no corresponde a esta cotidianeidad los personajes se quiebran, en el caso de los Dardenne esto es llevado al extremo dado que sus respuestas adquieren carácter primitivo. 
    </p>
  <p>Ya Bazin en 1948 advertía la importancia de esta corriente en el cine, por su adherencia a la actualidad. Y definía a los films italianos como documentales reconstruidos, donde en esa relación con la realidad estaba su valor excepcional. Con respecto a la técnica daba cuenta que la misma podía utilizarse al servicio del realismo o a sus expensas, pudiendo aumentar o neutralizar la eficacia de los elementos de realidad capturados por la cámara. En este aspecto los Dardenne pueden ser leídos como bazinianos ellos recrean esta corriente en la actualidad para dar cuenta de una Europa atravesada por una marginalización negada.
    </p>
  <p>A nivel estético es clara la consonancia que hay entre estos dos cines, pero a nivel temático también se condicen. La ética y la moral de estos personajes a la deriva es similar, y una de las películas con las que se pueden generan ejes de análisis similares es “Ladrón de bicicletas” (Vittorio de Sica 1948). La película se desarrollaba en un clima hostil, un trabajador se veía imposibilitado por la perdida de su bicicleta, si bien el robo de la bicicleta no estaba tratado de modo extraordinario si suponía un cambio radical en su vida. La bicicleta era su instrumento de trabajo y sin ella no podía subsistir. En el caso de Rosetta sucede lo mismo, el despido supone un estancamiento social y un seguir siendo parte de un estado precario de subsistencia, cuando ella se enloquece porque le quitan el trabajo, se ve la misma situación que cuando la bicicleta es robada. El acontecimiento no posee en si un valor dramático, sino que lo obtiene en función de la coyuntura social de la victima.
    </p>
  <p>Ambos cines se pretenden imágenes fieles de una realidad a descifrar para luego cambiarla. Ambos encuentran en la retórica documental el vehiculo para transmitir el mensaje a quien mira. Cuanto más austera la imagen, mayor el verismo y mayor la primacía del mensaje que transfiere. 
    </p>
  <p><strong>Cine de denuncia
    </strong></p>
  <p>Los Dardenne trabajan la depuración del plano como ya los neorrealistas lo hacían a fines de la segunda guerra mundial. Este ascetismo a la hora de filmar, anulando la puesta en escena y haciendo del plano secuencia su sello característico, logra recrear un tiempo siempre presente. La velocidad y el rigorismo de esa cámara apegada a su objeto de estudio anula la lógica narrativa haciendo emerger un realismo propio de la sucesión, en palabras de Bazin: “La acción no preexiste como una esencia, sino que brota de la existencia previa del relato, es la integral de la realidad”.
    Otro rasgo característico es que en su cine el contexto espacial donde se desarrolla la acción no esta puesto en primer plano, es más no existen especificidades del lugar. La indefinición de los espacios traslada el discurso a todas las ciudades posibles. Así es como la empatía con los personajes se nos impregna, su realidad no es ajena, no es lejana, es posible y es real. La neutralidad carga a los seres de una universalidad que los vuelve espejo de una sociedad que se halla en la penumbra, pero que esta presente.
    </p>
  <p>La manera de conectar con lo real es dejándolo ser, atenerse a lo mínimo y necesario, ser lo más austero posible para transmitir los estados inalterados de esos mundos negados. Cuanto más cercano a su objeto, más contundente su denuncia. </p>
  </p>
          </div>
     
        </div>
      </div>
      <div id="banners">
        <?php include("inc/banners.php"); ?>
        <?php include("inc/archivo_arteyliteratura.php"); ?>
      </div>
    </div>
  </div>
<?php
  include("inc/footer.php");
?>