<?php
  include ("inc/head.php");
  $GLOBALS['interna'] = true;
  include ("inc/header.php");
?>
    <div id="centro" class="arteliteratura">
      <div id="izquierda">
        <div id="arteliteratura">
          <div class="barra_titulo">
            <span></span>
            <h1>Arte &amp; Literatura</h1>
            <span class="tail"></span>
          </div>
          <div id="header_slider">
            <img src="uploads/insidejob.jpg" title="Header entrevista" alt="Torre de Babel" />          </div>
          <div id="texto_entrevista">
 <p>“Inside Job” es un documental norteamericano realizado por Charles Fergusson sobre las causas originarias de la crisis económica global del 2009 iniciada desde el centro de la industria financiera. La tesis central del relato es que la crisis fue el resultado de la complicidad del estado norteamericano en la desregulación del mercado financiero y el proceso inmoral con que los grandes bancos de inversión (Lehmann Brothers,  Goldman Sachs, Morgan Stanley) y los conglomerados financieros (Citigroup, JP Morgan Chase)  produjeron grandes ganancias a partir de una elaborada estafa en donde se impulsaban productos en el mercado pero no se consideraban los enormes riesgos que ese producto contenía. Sumando la complicidad de las calificadoras de riesgo que determinaban las calificaciones más altas a pesar de la inminente explosión de la burbuja financiera.<br />
   <br />
   Uno de los núcleos esenciales de la enunciación de la película es marcar el procedimiento corrupto con que las grandes corporaciones financieras vendían a sus clientes productos que ellos mismos sabían que iban a fracasar. No importaban los riesgos, el único fin era percibir grandes utilidades en el corto plazo, aun yendo en contra de su propia firma en el largo plazo. </p>
 <p>El fin de este artículo no es reflexionar sobre la tesis del relato sino elaborar una serie de interpretaciones que nos permitan comprender hasta que punto la crítica a la ideología es posible en la actualidad. Tomamos “Inside Job” como punto de partida porque la consideramos típica manifestación sintomática del capitalismo tardío y totalizador que aun en una fase “crítica”, es incapaz de pensar afuera de las formas de producción capitalistas. </p>
 <p>   En ese sentido el filme resulta paradigmático para el pensamiento de la crítica de la ideología. Tal cual lo expresa el filósofo Slajov Zizek para la imaginación colectiva es posible pensar el fin del mundo por una catástrofe natural o cósmica pero no concebir una sociedad pos capitalista, aun reconociendo los efectos devastadores de la crisis.  “Inside Job” es el limite de tolerancia crítica que la industria cultural permite hacia el interior del la hegemonía mercantilista. </p>
 <p>   El enmascaramiento de las operaciones ideológicas consiste justamente en el énfasis del problema moral. Según la tesis de Charles Fergusson los fundamentos de toda la crisis se remiten a una serie de conflictos de intereses en donde el estado cómplice de la industria financiera desregulo porque estaba compuesto por directivos y ex directivos de Wall Street. A eso se le agrega las vinculaciones financieras entre los sectores políticos y la industria financiera, el rol de los académicos norteamericanos y economistas que defendían las medidas desregulatorias al mismo tiempo que tenían beneficios económicos del sector financiero y la incorporación de la metáfora de la cocaína y el dinero a un nivel literal. Todos estos núcleos narrativos enunciados responden a una misma operación ideológica que relaciona la crisis económica al fracaso de los preceptos morales del capitalismo. Un fallo originario que deviene en una serie de fallos, que incluye la falta de regulación estatal, la falta de normativa empresarial, etc. </p>
 <p>Nuestra intención es justamente posibilitar una crítica a estos fundamentos y reflexionar sobre la aparición de enunciados que niegan los núcleos ideológicos del capitalismo y desarrollan una crítica a partir de una falsa cadena de reconocimientos.</p>
 <p>   En ese sentido la definición central de la ideología de Louis Althusser nos permite deconstruir las articulaciones discursivas de “Inside Job”. Para el filósofo argelino francés la ideología no funciona como un engaño a partir de una ilusión imaginaria. Sino que es la relación imaginaria del sujeto con las condiciones materiales existentes. Aquella ampliación de Althusser de la definición de la ideología propuesta por Marx transformo profundamente su estatuto.  Ya no se trata de la definición de una falsa creencia sobre la realidad, similar al sueño freudiano.  La relación fetichista propuesta por Althusser es efecto de las formas de reproducción ideológicas.  Es decir los Aparatos Ideológicos de Estado (AIE religiosos, AIE escolar, AIE familiar, AIE jurídico, AIE político, AIE de información, AIE cultural). El concepto de la materialidad ideológica en términos de aparatos de poder es clave para comprender que las operaciones de la industria financiera y de la economía capitalista global no concentran un problema moral externo a la estructura económica, como postula “Inside Job”, que produce la crisis. Por el contrario el núcleo ideológico es estructural al sujeto y a la punción determinante de los AIE. Esta presente como espíritu en cada uno de los sujetos alienados por el deslumbramiento de la mercancía desde antes de ser sujetos. <br />
   Esta superación teórica de Althusser nos permite dilucidar la relación dialéctica de los AIE y las formas de producción.  Althusser define “Se puede decir que los pisos de la superestructura (los AIE) no son determinantes en ultima instancia sino que son determinantes por la eficacia básica; que si son determinantes a su manera (no definida aun), lo son en tanto están determinados por la base (<strong>modos de producción capitalistas</strong>)” </p>
 <p>   La crítica de Zizek a la teoría marxista de la ideología se articula en base al concepto cientificista de objetividad planteado por Althusser. El supuesto posicionamiento “no ideológico” que enuncia desde la ciencia y logra un supuesto análisis de la realidad “sin sesgos”.  Para Zizek el único espacio no ideológico es el espacio ocupado por lo Real en la estructura y el antagonismo reprimido de la lucha de clases como motor de la historia. La posición de Zizek es clara, no es posible llegar a un análisis de la realidad en un grado cero. Toda posición es ideológica en tanto la función por excelencia de la ideología es negar su contenido ideológico y acusar de ideológico el discurso de oposición.<br />
   Podríamos analizar esta operación ideológica en cualquier agente que se declare neutral o científico. Por ejemplo un economista político capitalista que cree que maneja conceptos de una “ciencia objetiva” y no da cuenta de la operación ideológica que le preexiste penetrando la estructura simbólica del lenguaje. El capital define las funciones del lenguaje y el pensamiento. Determina los límites y las excedencias de las posibilidades cognoscitivas referenciadas siempre a un núcleo central: la expansión de la mercantilización del mundo. No hay posibilidad de salir de la ideología. El punto endeble de la teoría althuseriana es comprender esta articulación a medias, en tanto si bien por un lado la reconoce en la determinación del AIE en la estructura de sujeto, por el otro lado la niega desde la posición que declama una zona “protegida” de los efectos ideológicos. </p>
 <p>Para ser mas claro sobre este punto me gustaría hacer referencia a una anécdota. Recientemente tuve una discusión con un amigo relacionado a la industria financiera.  Discutíamos sobre la inflación y su argumento principal era que la inflación actuaba como una ley objetiva.  Su explicación mencionaba que la desvalorización de la moneda por el alzamiento de los precios era el resultado del crecimiento excesivo de la oferta de la mercancía madre de todas las mercancías, es decir el dinero. Esta interpretación refleja la operación ideológica que neutraliza un enunciado y lo afirma como descripción de un postulado objetivo y universal pero que no interpreta las relaciones contextualizantes que le dan una forma determinada previamente; la matriz férrea de una forma de producción.  La interpretación fetichista de esta respuesta radica en la denominada búsqueda del sentido oculto de las leyes de la mercancía. </p>
 <p>Uno de los aspectos paradigmáticos de la teoría marxiana es ir mas allá de la interpretación fetichista que intenta llegar al sentido oculto. Por el contrario explica la forma en que la burguesía se articula y se piensa a través de un relato.  Como explica el profesor Eduardo Gruner “Pues el “fetichismo” que promueve el discurso de la economía política consiste en hacer pasar la parte por el todo, la mercancía sustituyendo las relaciones sociales y la retotaliza reinscribiéndola en el conjunto de la formación social es decir devolviéndole su “profundidad” histórica sin necesidad de salir de la “superficie” del texto de la economía política… no es una “ilusión” que basta despejar para que toda vuelva a su lugar: es una ficción que produce efectos materiales decisivos; sin fetichismo de la mercancía no hay capitalismo.” </p>
 <p>Este movimiento ideológico está vinculado claramente al lenguaje financiero utilizado por Fergusson en su película. En tanto todas las críticas están desarrolladas por un lenguaje financiero que busca desentrañar un “sentido oculto”, un enigma al cual el espectador solo puede acceder adquiriendo el lenguaje de la economía política.  Una explicación que dice atacar pero que en realidad es reforzada al momento en que retoma el lenguaje financiero. Esta operación articula como reales los supuestos funcionamientos complejos y profundos del mercado financiero. Aunque sean también un engaño, este no se encuentra en el contenido oculto.</p>
 <p>El fin es destotalizar aquella teoría de “Inside Job” que toma como premisa de la industria financiera y declama la profundidad inaccesible de las operaciones financieras. Como si el núcleo traumático de la explotación estuviese en ese lugar central al cual solo puede acceder el discurso de la economía política. Pero como muy bien interpreta Foucault a Marx “El concepto de superficialidad en Marx es muy importante; en el comienzo de El Capital él explica como a diferencia de Perseo, debe sumergirse en la bruma para mostrar con hechos que no hay monstruos, ni enigmas profundos, porque todo lo que hay de profundidad en la concepción que la burguesía tiene de la moneda, del capital, del valor, etc, no es en realidad sino superficialidad”   En el caso de “Inside Job” esta proposición tiene un serio efecto en la articulación política que el relato dice querer posibilitar cuando en realidad es una negación de cualquier política afuera de la lógica del capital. Así la contradicción atraviesa la enunciación. Si bien el relato reconoce por un lado que la argumentación discursiva de la industria financiera es parte de la estafa, también cede ante su propio lenguaje que intenta explicar el mundo y las estafas que ocurren en él a través de herméticas operaciones financieras. Como revela Zizek respecto a la actitud a tener ante el lenguaje de la mercancía, “La respuesta es que hay una homología fundamental entre el procedimiento de interpretación de Marx y de Freud. Para decirlo con mayor precisión, entre sus análisis respectivos de la mercancía y de los sueños. En ambos casos se trata de eludir la fascinación propiamente fetichista del “contenido” supuestamente oculto tras la forma: el “secreto” a develar mediante el análisis no es el contenido que oculta la forma (la forma de las mercancías, la forma de los sueños) sino, en cambio, el “secreto” de esta forma.” </p>
 <p>La teoría zizekiana va más allá de Althusser y explica como la ideología no es solo una operación de mistificación en un nivel interno, sino que ya esta presente como fantasía ideológica en la mercancía. <br />
   “Aunque en el capitalismo los sujetos están emancipados y se perciben a si mismos como si estuvieran libres de las supersticiones religiosas medievales, cuando tratan unos con otros lo hacen como utilitaristas racionales, guiados únicamente por sus intereses egoístas. El rasgo característico del análisis de Marx es, no obstante, <em><strong>que las cosas (mercancías) creen en el lugar de ellos, en vez de los sujetos, es como si todas las creencias, supersticiones y mistificaciones metafísicas, supuestamente superadas por la personalidad racional y utilitaria, se encarnaran en las relaciones sociales entre las cosas. Ellos ya no creen, pero las cosas creen por ellos” </strong></em><strong></strong></p>
 <p>Althusser mostró como la ideología penetraba la estructura simbólica que establecía la materialidad del AIE a través de una relación imaginaria que ocurría en el sujeto. Pero no da una explicación de cómo el AIE internaliza la ideología a partir de una realidad regulada de antemano por una fantasía ideológica. La encarnación de la fantasía ideológica en la mercancía revela que ya no importa la creencia o no creencia en el postulado ideológico. Aunque se acabe la creencia y rompamos con la relación imaginaria con las mercancías la ideología sigue estando funcionalizada en el campo social. Este aporte lacaniano de Zizek explica como el significante (soporte material) determina el inconciente, ya no es necesario que el sujeto “crea” de forma conciente, sino que sencillamente actúe a pesar de no que no lo “crea”. Así funciona el cinismo posideologico de los empleados de Wall Street mencionados en “Inside Job” que a pesar de saber lo que hacen lo hacen igual. Reconocen el interés particular detrás de la relación universal establecida pero el mandato esta cristalizado como núcleo traumático sin sentido en el inconciente. Esto que supuestamente “Inside Job” crítica ocurre en su relato de forma muy similar, en tanto se reconoce el malestar causado por la explotación y sufrimiento del capitalismo, pero el discurso no puede afrontar el antagonismo reprimido de lo Real que muestra que el problema no esta concentrado en la moralidad de la industria financiera o del Estado sino en las mismas formas de producción capitalistas.</p>
 <p> Zizek insta a interpretar a lo Real lacaniano, aquello a lo cual no podemos acceder nunca a través de la simbolización,  el centro mismo de toda insatisfacción, en términos del antagonismo reprimido de la lucha de clases en el cuerpo social. Althusser nunca explicó la internalización del AIE a través de la determinación del significante que ya representa de ante mano una versión ideologizada de lo material. Esto implica una imposibilidad de cualquier formación discursiva ante la ideología. La imposibilidad de lenguaje de acceder a  lo Real, a una instancia extra ideológica de representación absoluta de la realidad. Por lo tanto la única operación posible de la crítica de la ideología es reconocer esta imposibilidad y dar cuenta que el antagonismo reprimido de la lucha de clases que no fue simbolizado tiene un constante regreso espectral. Para la teoría marxista lacaniana esgrimida por Zizek la clave es intentar acceder al núcleo traumático y no a la realidad objetiva. El problema del supuesto análisis de  “realidad objetiva” es que no reconoce el elemento traumático de la relación problemática del sujeto y su estructura simbólica y el antagonismo reprimido de la lucha de clases. Esto permite llegar a una serie de conclusiones acerca del peligro argumentativo de “Inside Job” en tanto  relato sintomático de ciertas articulaciones políticas que declaman ser críticas pero no hacen frente a lo reprimido de su deseo consevardor que sostiene aun la fantasía ideológica del capital. Al mismo tiempo que se reflejan discursivamente como expresión transparente del discurso neutral, racional, lógico que intenta desentrañar el enigma a partir de explicaciones financieras objetivas. </p>
 <p>Deleuze y Guattari enunciaron este mismo problema en donde el mecanismo ideológico estuviera más localizado en la relación entablada por el soporte material para mostrar hasta que punto la maquinaria lograba un efecto de autonomía y omnipotencia sobre los agentes. “La sociedad construye su propio delirio al registrar el proceso de producción; pero no es un delirio de la conciencia, más bien la falsa conciencia es verdadera conciencia de un falso movimiento, verdadera percepción de un movimiento objetivo aparente, verdadera percepción del movimiento que se produce sobre la superficie de registro.” <br />
   … y sobre el capital se enganchan las máquinas y los agentes, hasta el punto que su propio funcionamiento parece milagrosamente producido por aquél. Todo parece objetivamente producido por el capital en tanto que cuasi causa”. <br />
   Este concepto es central para analizar la forma en que Inside Job esquiva el efecto mistificador y omnipotente del mercado financiero y la mercancía, al universalizar estos particulares y reinscribiéndolos en el centro del poder social a partir de la queja. La denuncia de “Inside Job” sobre las decisiones delictivas de los empleados de Wall Street falsea hasta que punto la maquinaria capitalista ha penetrado los espíritus haciéndoles creer su impotencia ante la lógica del capital. </p>
 <p>A través de las operaciones ideológicas mencionadas, Fergusson enfatiza la problemática del poder del capitalismo y su crisis en un proceso de inmoralidad que ocurre en una zona de exterioridad secreta (el impenetrable funcionamiento de la industria financiera). Lo ideológico del enfoque de Fergusson es justamente que es verdadero en lo particular pero erróneo en la totalidad del problema. Cristaliza un problema moral que nos lleva a dos opciones de externalización. Someter a un sistema de juicios a un tercero encarnado en entidades malignas maquinales (las corporaciones) o someter a un sistema de juicios a los capitalistas codiciosos dueños de las corporaciones. Los dos escenarios son erróneos en tanto no comprenden que el problema no es externo sino que el resto de los agentes políticos eludidos por la narración son parte del ensamble de la maquinaria. Son los agentes que actúan “libremente” transformados en agentes impotentes en tanto victimas.  El problema de la industria financiera no es ajeno al resto de los agentes ideológicos que sostienen las formas de producción. La internalización de esas formas de producción como universales y necesarias son la piedra fundamental de la catástrofe del capitalismo tardío.  Como explica Zizek “el verdadero horror no esta en el contenido particular que se esconde tras la universalidad del capital global, sino en el hecho de que el capital efectivamente es una maquina global anónima que sigue su curso ciegamente, sin ningún agente secreto que lo anime. El horror no es el espíritu (viviente particular) en la maquina (muerta universal), sino la maquina  (universal muerta) en el corazón mismo de cada espíritu (viviente particular).” <br />
   “Inside Job” es un proceso de expiación que niega la culpa y la desplaza hacia fuera. Según Fergusson la única posibilidad de redención esta en acceder al lenguaje (prestado) de la economía política. Esto constituye una impotencia política generada por la idea de que solo accedemos a un vistazo del funcionamiento “secreto” de la industria que nos domina. Visión fetichista que no accede a la forma y si al contenido. </p>
 <p>   La impotencia política que Fergusson articula para su espectador termina cristalizando una suerte de expiación del problema que termina por reforzar los <strong>AIE</strong> a partir de una regulación ética. Inside Job es en su matriz productiva parte de lo que dice criticar. En realidad es peor en tanto su posición es parte de la regulación del capitalismo para la supervivencia a partir de un auto ajuste ideológico. </p>
 <p>“Inside Job” niega el núcleo traumático que establece la relación fundamental de mistificación del capitalismo encarnada en las mercancías. Pero al mismo tiempo necesita encontrar un culpable externo. Claro esta que con esto no pretendo expiar la condena de las grandes corporaciones a la cuales “Inside Job” ataca. Por el contrario se trata de mostrar hasta que punto el éxito del discurso de la industria financiera en términos particulares y del capitalismo global en términos generales es el resultado del cinismo y la resignación posideologica. La falacia fundamental que atraviesa “Inside Job” es su falsa crítica.  Su tesis es conservadora, no ataca los fundamentos del capitalismo, los elude por completo. Por el contrario proclama nuevas funcionalizaciones de un capitalismo cultural, humano, ético, que refuerce la relación de dominio del capital para que no conozca su crisis nunca. </p>
 <p>   “El estado “normal”  del capitalismo es la revolución permanente de sus propias condiciones de existencia: desde el principio el capitalismo se “pudre”, está marcado por una contradicción mutiladora, por la discordia… lejos de ser constrictivo su limite es pues, el ímpetu mismo de su desarrollo. En ello reside la paradoja propia del capitalismo, su ultimo recurso: … es capaz de trasformar su limite, su impotencia misma, en el origen de su poder – cuanto mas se “pudre”, mas se agrava su contradicción inmanente, mas ha de revolucionarse para sobrevivir.” </p>
 <p>   Acaso la compresión de esta articulación nos permita una forma de autorreflexión analítica que nos permita reconocer las formas discursivas que alegan la critica como una forma de expiación y que refuercen el fortalecimiento ideológico. El reconocimiento de las formas discursivas que nieguen la necesidad fundamental de impulsar nuevas caminos de revolución que ataquen las formas de producción capitalistas, tendrá que ser acompañado por un replanteamiento del problema de la ideología y sus alcances. <br />
 </p>
          </div>
     
        </div>
      </div>
      <div id="banners">
        <?php include("inc/banners.php"); ?>
        <?php include("inc/archivo_arteyliteratura.php"); ?>
      </div>
    </div>
  </div>
<?php
  include("inc/footer.php");
?>