<?php
  include ("inc/head.php");
  $GLOBALS['interna'] = true;
  include ("inc/header.php");
?>  
    <div id="centro" class="entrevistas">
      <div id="izquierda">
        <div id="entrevistas">
          <div class="barra_titulo">
            <span></span>
            <h1>Entrevistas</h1>
            <span class="tail"></span>
          </div>
          <div id="header_slider">
            <img src="uploads/entrevistas/leonardofavio.jpg" title="Entrevista a Juan Minuj&#237;n" alt="Entrevista a Juan Minuj&#237;n" />          </div>
          <div id="texto_entrevista">
            <p><br />
            Martel: Me gustaría comenzar con algunas preguntas sobre “Nazareno Cruz y el lobo”, cosas que me dan mucha curiosidad. En “Nazareno…” ¿Cómo fue que se llegó a que el chiquito que está con la lechiguana tuviese los ojos pintados?</p>
            <p>              Favio: En realidad, era una chiquita, venía a representar a la enana Fidelia, que es un ser liliputiense, chiquitito, que está como en un frasquito, no cambia de estatura nunca y permanece siempre fiel a Nazareno, lo sigue en todas sus circunstancias. Ahora, por qué lo hemos pintado… Supongo que de la misma manera en que un supuesto lobo se transforma en hombre… porque lo requería la historia.</p>
            <p>              M: Tengo otras curiosidades que son como regalos que me quiero hacer en la entrevista. Una de las escenas que más me conmueve del cine que he visto es cuando el Diablo le dice a Nazareno que está solo, que por favor hable con Dios. Lloro poco en el cine, pero esa escena me conmueve mucho.<br />
            F: Creo que conmueve más por la gran interpretación de Alfredo, que le dio ese carácter. En cuanto a su soledad, ya la atribuyo a que el demonio es una cosa, algo que uno tiene instalado en la memoria, que uno tiene reposado en el corazón esperando la oportunidad para ponerse a joder, que es intangible, que existe dentro de uno mismo. También conmueve el personaje en sí. No debe haber un ser más solo en el universo. Un tipo que le vio la cara a dios, que es lo máximo a lo que uno puede aspirar y que después lo perdió todo.</p>
            <p>              M: Yo leí que a usted le gusta mucho leer La biblia, el Antiguo testamento, y para mí el Libro de Job es una lectura, diría, anual. El diablo de Nazareno… me hace acordar a ese diablo en el Libro de Job, que le pide a Dios que ponga a prueba a Job, que lo castigue. Es un ser muy celoso. Me parece que se trata de una imagen del mal que es mucho más útil para el hombre. Un diablo solo y triste.<br />
            F: Le estás dando una lectura muy linda, que no fue la intención original. Pero es hermoso que a la gente le pueda llegar de esa manera y, particularmente, a gente de tu sensibilidad.</p>
            <p>              M: Pero está en la película, no creo que sea un invento mío.<br />
            F: Sí, está en la película, pero andá a saber cómo es realmente el demonio. Insisto en que es algo que está dormido adentro nuestro y que de repente abre un ojito… Hay mucho para explotar, y me atrevo a sugerírtelo si te interesa, del imaginario teológico. Desde hace milenios, desde el principio de los tiempos, son ellos los grandes especialistas de la puesta en escena.</p>
            <p>              M: La cuestión teológica siempre estuvo presente en su obra, desde el comienzo.<br />
            F: No la teología en sí, me expresé mal, me refiero a la puesta en escena de los ritos. En rigor, en los internados en los que estuve, aunque era pequeño ya percibía cómo se dirigían a nosotros, cómo se ponían detrás de un púlpito para hablarnos, por ejemplo. Después, a los diez años, pasé fugazmente por Don Bosco, y ahí me fui dando cuenta de lo que era una puesta en escena. No te puedo explicar bien cómo. Pero observaba cómo se movían esto o aquel cura. Miraba cómo daban la misa uno y el otro. Cómo un cura llevaba la copa de una manera y otro de otra, cómo, en definitiva, el sermón de uno me llegaba más que el de otro. Había algunos muy buenos actores entre ellos. ¿Acaso existe alguna puesta en escena más maravillosa que cualquier misa o acto importante en el Vaticano? Mirá el gran actor que era Juan Pablo II. El de ahora no tiene tanta gracia, no está dotado. Pero esa estética a mí siempre me marcó, siempre me gustaron las estampitas por ejemplo.</p>
            <p>              M: Todo “Nazareno…” parece una pinturita de estampitas.<br />
            F: Es un tema en el que no se profundizó y que es muy lindo. Porque te permite volar… Y a veces es necesario volar. Yo estuve muy limitado por la técnica en esa época, pensá que fue hace 34 años. En un momento quería que salieran volando con una escoba y lo tuve que resolver poniéndolos en el agua. Pero todo eso es también algo que me acompaña desde mi más lejana niñez, cuando vivía en Luján de Cuyo con mi tía y con mi abuela.</p>
            <p>              M: ¿Con su madre no?<br />
            F: No, yo viví con mi madre hasta los cinco años. Después, cuando ella se separa, me llevó a vivir con bisabuela, una tía y un tío, Arturo, en Luján de Cuyo. Ahí, los cuartos en los que dormíamos estaban abarrotados de velas, rosarios e imágenes religiosas. Pero lejos de asustarme, o de provocarme rechazo, todo eso llegó a gustarme más que jugar. Me hacía sentir acolchonado, protegido, como debajo del ala de una gallina.</p>
            <p>              M: Leí que su mamá escribía radioteatro.<br />
            F: Sí, y era muy talentosa. Todavía conservo todos sus libros. Ella comenzó a escribir cuando yo tenía unos quince años. Antes era actriz. Y muy buena directora de radioteatro también. Muchos dicen que esa fue mi primera formación. Sobre todo en cuanto a la marcación de los actores. Eso lo aprendí observando a mi madre en Mendoza, en donde tenía su propia compañía. Mirándola aprendí casi todos los secretos de cómo marcar a los actores sin hacerlos sentir incómodos, porque ella lo hacía mientras estaban al aire, en vivo, como una directora de orquesta.</p>
            <p>              M: ¿Qué edad tenía usted en ese momento?<br />
              F: Unos catorce años. Ahí empecé a hacer radioteatro.<br />
              M: ¿Y ella escribía las obras?<br />
            F: Sí, era autora. Acá en Buenos Aires se hacían muchas obras también. En radio El Mundo, en el Teatro de las dos carátulas, se podía escuchar a las grandes figuras del momento. Fui muy afortunado.</p>
            <p>              M: Se puede decir que usted es el único director que tiene a dios en su equipo de trabajo. Me refiero sobre todo a lo que se fue dando, a la cantidad de cosas azarosas o aparentemente azarosas que lo fueron ayudando en su carrera.<br />
            F: Sí. Soy un tipo de mucha, mucha suerte. Y sin ninguna duda que dios está permanentemente a mi lado. A veces lo siento cuando estoy empantanado en un rodaje, cuando tengo la cámara y no sé qué hacer con ella -vos sabes bien lo doloroso que es eso…- Me aparto, y me quedo solo y la cosa simplemente viene. O como siempre me pasa con los actores. Sin ir más lejos, el Perón de “Gatica, el mono”. Me acuerdo que viene un tipo con rulos y yo no sabía bien a quién podría interpretar, pero lo quería usar para algo y no terminó de bajar del edificio en donde estábamos, que me di cuenta que era Perón. “¡Perón!” le gritaba desde el balcón, “¡Señor actor (Armando Capo), venga, venga!” Y era Perón, nomás. Así tengo un montón de anécdotas. Por ejemplo, el encuentro mágico que se dio con Piquín y con las chicas de esta última película “Aniceto” (Natalia Pelayo y Alejandra Baldoni). A qué se lo podés atribuir sino a un milagro… No hice casting, yo nunca hice casting. Margarita Fernández, la coreógrafa, me traducía las técnicas de los movimientos y otros detalles de las transmisiones de ballet que yo me grababa y a partir de ella surgió el nombre de Hernán Piquín. Enseguida pregunté si podíamos llamarlo y me dijeron que estaba a tres cuadras y ni bien entró en casa me di cuenta de que el Aniceto era él.</p>
            <p>              M: Pero cómo llegó a esto de volver a filmar “El romance del Aniceto…” y con este formato, Me parece increíble.<br />
            F: Pasa que en los últimos tiempos se me dio por retocar viejas películas, “Crónica de un niño solo”, “El dependiente”, y también miraba mucho “El romance del Aniceto y la Francisca…” Intentaba ver cómo darle otro giro, y sobre esos prolongados silencios ponía música y los miraba… Después, un día fui al último cumpleaños de Niní Marshall y me encontré con Patalano. Fue él quien me dijo: “¿nunca se te ocurrió hacer un ballet?” Y me quedé pensando en eso. Al otro día me puse a trabajar con la vieja versión y empecé a recordar viejas ideas.</p>
            <p>            M: ¿Pero sin música?<br />
              F: No, con música: ponía Beethoven, Bach, Tchaikovsky, cosas así. Y después cómo no voy a pensar que interviene dios en todo esto, cuando tengo a mi lado a esa especie de milagro que es Iván Wyszogrod, ni bien entró en el proyecto tomó los demos y empezó a volar haciendo una música espectacular. Al principio pensamos que se trataba de una obra de teatro, pero después nos dimos cuenta de que podía ser una película, y una muy linda. Y con las chicas pasó lo mismo, no necesité ver a nadie más. Son de una belleza y un nivel actoral extraordinario. Vos decís que dios asiste a los equipos que yo dirijo, pero también hay que saber buscarlo.<br />
              M: Leí algo que a mí me hace mella directamente. Cuando habló del pudor en el cine, usted dijo que no había que filmar con pudor. Y justamente cuando uno ve el cine de Leonardo Favio, eso es lo primero que uno puede decir, aun sin saber nada: este hombre no tiene pudor.<br />
            F: Es porque el cine es amor, tenemos una relación amorosa con él. Por eso duele tanto, por eso uno queda tan vacío cuando se termina y hay que pasar urgente a otro proyecto.</p>
            <p>              M: Pero me gustaría entender a qué se refiere cuando habla de pudor en esa instancia.<br />
            F: Todo es bueno para lograr la emoción, el cine no es otra cosa que lograr la emoción. En última instancia somos beduinos contando un cuento en el desierto. Si tengo que filmar una escena clásica yo no tengo ningún problema en decir que quiero fotografiarla como lo hacía tal o cual director y, aunque me digan que no, yo insisto: “hacela y después vemos”. Eso es no tener pudor. Cuando uno hace el amor con su pareja y es feliz, ¿por qué se va a privar? No somos ángeles, somos seres humanos. Salvo, claro, en cuanto a las limitaciones morales, sobre todo, en cuanto a no dañar al otro. El cine es lo mismo. Si veo algo que a mí me gusta de determinada película no la voy a calcar, pero puede ser el disparador de una escena descomunal. Qué me importa si me dicen que se parece a Nilsson o que es muy Truffaut, si logro la emoción, ya está. No hay que preguntarse tanto. Siempre aplico la frase de San Agustín, “Ama y haz lo que quieras”.</p>
            <p>              M: Sí, pero también entiendo el pudor en otro sentido, el que usted ilustra lo comprendo, pero a mi me parece que estoy siendo desleal con los actores y con los personajes si me meto demasiado a escudriñar en sus emociones. Por el contrario, me conmueve mucho cómo la gente es capaz de disimular sus sentimientos para no molestar. Ese instante en que una persona muy enamorada llega a pensar que su amor puede incomodar al otro.<br />
              F: Pero en ese caso estás planteando el pudor que te genera estar frente a una pareja que finge una escena de amor.<br />
              M: No, me refiero a que si yo tengo que elegir (lo digo como un defecto y no una virtud), entre todas las posibilidades que ofrece un diálogo: el llanto, el grito y el momento en que no se sabe cómo comenzar con todo eso, yo elijo este último momento. Porque lo otro me inhibe un poco. Me inhibe a mí. Pero cuando lo veo al diablo llorando en “Nazareno…”, no lo puedo evitar y lloro. Pero cuando yo tengo que plantear la escena, elijo siempre el momento en que los sentimientos están más enmascarados.<br />
              F: Bueno, yo no digo que lo mío es “blas”, punto redondo. Estoy contando mi experiencia, que no necesariamente es la de todos.<br />
              M: Pero su experiencia es señera…<br />
              F: Entonces, si sirve de algo, diría que ahondes en eso. En mi caso, creo que la función de uno es esa, es lograr la emoción. Si no, ¿para qué…?<br />
              M: ¿Y qué pasa cuando se logra la emoción?<br />
            F: La emoción, la alegría, o lo que fuere. Se debe transmitir. Todo lo que pueda sacar de la imagen que estoy fotografiando es lo que voy a brindarme a mí y al público. O sea, ¿cómo nace y se concluye una película? Nace eligiendo materiales, los actores y todo aquello con lo que uno va a narrar la historia pero ¿cuándo se termina esa historia? Cuando es espectador la capta en su cabeza y en su corazón, porque si no, tenés un proyector y una pantalla y fotografías que se suceden, pero tu película existe recién a partir de la aparición del espectador. El que termina tu obra es el espectador en su cerebro, en cada uno de sus cerebros.</p>
            <p>              M: Coincido completamente.<br />
              F: Entonces, al ser así, tenés que brindarle todos los instrumentos necesarios para que esta persona la piense y la elabore. Si vos te guardás algo, primero que estás en pecado. No hay que guardarse nada. Todo lo que tenés no es tuyo. Después, que tengas talento o no lo tengas es otra cosa. Es cuestión de genes, de dios, de lo que sea.<br />
              M: ¿Pero hay a quien no le haya tocado nada?<br />
            F: Sí, hay gente que muere sin haber recibido un beso en toda la vida… No conoció quién le diera un beso, imaginate. Pero no hay nada peor que un necio convencido de una vocación que no le pertenece. Porque siempre se va a sentir un incomprendido y se va a dar un porrazo detrás de otro: pero por suerte, son los menos. En cuanto al pudor, hablo de no herir.</p>
            <p>              M: Entre “Soñar, soñar” y “Gatica, el mono” pasaron muchos años. ¿No extrañaba el cine durante ese período?<br />
              F: No. Yo podría dejar de filmar mañana. Mi vida no gira en torno a eso. Claro, tengo la canción, que me sirve para descargar, para exteriorizar.<br />
              M: Y tiene el cariño del público…<br />
              F: Sí, y también me pasa al revés, tampoco ahora extraño la música porque estoy abocado a otra cosa. Soy polígamo…<br />
              M: ¿Usted es de Luján de Cuyo de nacimiento?<br />
            F: No, nací en un pueblito muy chiquito a dieciocho kilómetros de Luján de Cuyo. Y a Buenos Aires llegué a los diecisiete años.</p>
            <p>              M: Y volvió para filmar en su tierra, ¿no es cierto?<br />
              F: Sí, “El Romance del Aniceto y la Francisca…” lo filmamos en Luján de Cuyo y en Godoy Cruz. También ahora estoy preparando un guión que se llama “El mantel de hule” y que transcurre en Mendoza.<br />
              M: Le pregunto esto porque a mí me pasa una cosa muy particular con mi ciudad natal. ¿Cómo siente que se arma ese terruño original, ese lugar en donde uno se inventa la historia y por lo tanto se inventa también lo que la ciudad natal? ¿La pasa algo así?<br />
              F: En mi caso no, todo eso fue muy fuerte para mí, me quedó marcado a fuego. Si mirás mi oficina vas a ver fotos de cuando era un poco más grande que adolescente o con mis amigos. Es en mis insomnios en donde esos recuerdos lo dominan todo. Me acuerdo que compré un disco con ruido de agua para pensar en la acequia. También puse un techo para poder oír cómo golpea la lluvia.<br />
              M: ¿Pero no hay un lugar en donde se junten todas las épocas, toda la gente, de manera desordenada, los amigos?<br />
              F: En el amor. Amigos, realmente amigos, fueron los de mi niñez. Yo no tengo amigos. Tengo gente que quiere mucho, que me alegra ver. De lo más dispar. Me encanta charlar con Felipe Solá y de golpe me enamora estar con Horacio Verbitsky. Yo creo que ese lugar al que te referís es el amor o los recuerdos del amor que se disparan como petardos y que no se pueden controlar. A esta altura de mi vida son sólo recuerdos, que con el tiempo uno los embellece.<br />
              M: Me parece increíble que pueda volver a revisar con la misma pasión películas que ya hizo. ¿No se cansa?<br />
            F: No es tan así, tal vez exageré, le di una falsa entonación. No es que yo vuelva a modificar… Dentro de unos años te va a suceder que vas a estar mirando una película tuya y vas a ver un cuadrito o dos cuadritos en donde vas a decir “eso no lo filmé yo”, “eso lo filmó otro”. “¿Cómo pude poner estos cuadritos al pedo ahí?” En esa época, modificar el negativo era más complicado. Además, me perdieron muchos negativos. Hoy las puedo ver e identificar las tomas de porquería, esas que no dirigí yo, y sacarlas. Después, con el nuevo armado, la película se embellece, adquiere más potencia. Y de paso disimulaste un traspié que surgió hace cincuenta años.</p>
            <p>              M: ¿Y si hay que agregar algo cómo se hace?<br />
              F: No, agregar no, eso ya sería un pecado. Una cosa es sacar las desprolijidades, recortar los flecos… Para agregar, la hago entera, ahí está “Aniceto”. Pero me gusta mirarlas. Estudiarlas. No para regodearme con la obra, sino para entender por qué lo hice, por qué hice este travelling. Por ejemplo, en “Crónica…”, me preguntaba por qué corté un adaggio que tendría que haber continuado. Después me di cuenta que en esa época los rollos duraban diez minutos, y que era por eso que se cortaba abruptamente. Ahora quiero volver a colocarle la música como yo soñé en aquella época. No modifico la película, le estoy poniendo aquello que no le puse en su momento por un problema técnico.<br />
              M: ¿Pero cuánto tiempo después de realizadas comenzó a ver sus películas, o lo hizo siempre inmediatamente después?<br />
            F: Yo cometo suicidios a diario… A veces hago tremendas metidas de pata durante el rodaje y me doy cuenta en el momento, pero si me preguntás por qué no lo arreglé en aquel entonces, tengo que decirte que porque soy un boludo, soy muy tímido. Si repetí demasiadas veces una toma, me ha pasado de decir que ya estaba cuando sabía perfectamente que no era así, es que a veces me da un no sé qué…</p>
            <p>              M: ¡A mi me pasa igual!, todo el tiempo.<br />
              F: Pero si lo ves, lo tenés que hacer… Eso es algo que aprendí recién ahora, en esta última película.<br />
              M: La cuestión de la tecnología, que hoy va cambiando tan rápidamente ¿es algo que le preocupe?<br />
              F: No, porque zapatero a sus zapatos. Sé delegar. Busco al cameraman que realmente vibre con lo que hace. Cuando charlo con la gente me doy cuenta enseguida si es así, y después trato de no meterme en los vericuetos particulares de cada técnica. Eso es responsabilidad de él. Yo sé que quiero usar tal lente, que el día de mañana puede venir robotizado, pero no es lo importante. La cuestión es saber elegir las cosas. Si se inventara una nueva pintura, no por eso voy a bañar el cuadro con esa puntura solamente.<br />
              M: ¿Cómo percibe la historia o la sucesión del cine argentino? Me pegunto si las generaciones que se fueron sucediendo no están muy cortadas entre sí. No podemos aprender, ni de lo bueno ni de lo malo.<br />
            F: No sé a qué atribuirlo. Yo tengo un problema, a mí la cosa me gusta de tú a tú. Cuando me tratan de “maestro” y esas cosas, ya me cortan, como que me ponen en un rincón y ya no se puede mantener un diálogo. Por ejemplo, a mí me encanta Pablo Gaggero, pero yo no estoy para hablar con él, a mí lo que me fascina es su cine. Antes nos reuníamos a hablar de cine. El que hace cine tiene que hablar de cine; los pintores, de pintura, el periodista se tiene que juntar con otros periodistas; así era el café de los 50. No puede ser que nos estemos comunicando a distancia.</p>
            <p>              M: ¿Ustedes hacían eso?<br />
              F: Sí. Igual se sacaba el cuero, había celos y todas las pavadas que hay ahora. Aunque no lo sufrí tanto, porque tenía una gran capacidad como espectador. Nos juntábamos en un bar que estaba cerca de las oficinas de Argentina Sono Film. Me encantaba estar con Leopoldo Torre Nilsson y con su padre (Leopoldo Torres Ríos), también con Lucas Demare. Me reía como loco con ellos y ellos se reían conmigo, y me hacían cantar. Yo aprovechaba y absorbía todo lo que podía. Sentía una admiración de locos, todos ellos, eran titanes para mí y yo para ellos era un pendejo.<br />
              M: Pero ¿y con los de su generación?<br />
              F: Eran viejos, nacían viejos esos tipos. Yo no tenía gente de mi generación cerca. No había. El que me gustaba a mí era David Kohon. Me gustaba mucho lo que hacía. Pero con el resto estábamos divorciados porque yo veía otro tipo de cine.<br />
              M: ¿Cuál?<br />
              F: El nuestro. Cuando estaba preparando “El Romance…” quería contratarlo a Palito Ortega para el protagónico. Gracias a dios no aceptó. Pero quería ganar plata. Hacía ruido el estómago… También quería armar una productora para hacer películas con Luis Sandrini, y no me importaba si las dirigía otro. Tal vez yo debía parecerles un turquito comerciante a todos ellos.<br />
              M: ¿Pero no es muy así la historia de esta actividad en nuestro país, de divorcios y distancias?<br />
              F: Después, siempre se armaban broncas. Recuerdo todos esos discursos, sin que nunca se llegue a nada. Porque al final, el que tiene la verdad es el que tiene la mosca. Todos decíamos lo mismo: hay que hacer un cine que haga que la gente quiera ir a verlo. Como lo repito hoy en día, hay que seducir a la gente de nuevo, hacerla que vea cine argentino. Con el valor de la entrada o con lo que sea. ¿Cómo vamos a competir nosotros con los norteamericanos, que te ponen dos tanques con la cara de Al Pacino en el afiche? En cuanto al costo de la entrada me refiero. No es cuestión de que tu obra sea buena o regular, es que la persona llega al cine y ve que la entrada está a veinte pesos. Y terminan yendo a ver la de Al Pacino. En cambio, si ponemos tu película y la mía durante tres semanas a diez pesos, tres semanas nada más… con ese dinero ya vas recuperando lo invertido, pero además es una promoción fabulosa, y va armando la posibilidad para un verdadero boca a boca. Después, si tu película es mala, ya no le podés echar la culpa a nadie. Ahí sí, el espectador tiene para la Coca Cola, el pochocho y el viaje de vuelta. Y además, comienza a descubrir a sus realizadores, a conocerlos por sus nombres. Hay estupendas películas con las que el público se engancharía y otras que van a perder como en la guerra. Habría que sentarse a hacer bien todos los cálculos y probar. Tal vez en la segunda semana ya cuesta veinte pesos, como todas las otras películas, pero porque ya el público conoce la obra y sabe por qué la va a ir a ver.<br />
              M: Igual me parece que es bastante complejo, porque aunque la entrada sea más barata, creo que igual van a ir a ver la de Al Pacino. Pero de todas formas, algo hay que hacer, porque si sigue a veinte pesos no va a ir nadie al cine.<br />
              F: Que no te quepa la menor duda. Hay que pensar en algo. Nuestro cine no es malo. Hay películas estupendas, pero el público se va a la sala de al lado, porque no las llega a conocer.<br />
              M: ¿No estamos jugando en cancha de otro también? A veces me da la sensación de que el sistema está armado para otro tipo de cine y uno termina peleando en inferioridad de condiciones. Por ejemplo, las expectativas de éxito están en otra escala, no todas las películas pueden hacer millones.<br />
            F: Lo que yo te digo ya se hace en el mercado. Madonna saca ahora un DVD y las dos primeras semanas está a la mitad de precio, entonces todos se vuelcan a comprarlo. Después, el precio pasa a ser el doble.</p>
            <p>              M: Es cierto. Pero también hay otra crítica que se hace mucho al cine argentino, se dice que le falta esto o le falta lo otro. Se critica que no se hacen películas de tal clase…<br />
              F: Eso es una verdadera pavada, cada uno tiene que hacer su cine.<br />
              M: También estuve pensando que, como hasta ahora, nosotros no vamos a tener segundos de publicidad en la televisión, va a ser aún más difícil que el público se entere del estreno de nuestras películas. Frente a la llegada que tiene la televisión, los diarios o Internet no tienen tanto peso. Pero los anuncios en televisión son carísimos, te dan 2000 segundos, que no sé cuantos spots pueden ser, y uno tiene que dejarles de por vida la película para que la exploten.<br />
            F: Hay que usar todo lo que sea útil. No hay que tener pudor en esto tampoco. Por ejemplo, nadie les da bola a estos chicos como Polino y demás, o a Crónica. Yo sí, ellos tienen su público y es mucho. Yo no quiero que me hagan un monumento, ni nada por el estilo, pero sí que a la película le vaya lo mejor posible. Eso es lo que después me permite continuar exhibiéndola y mantener a mi gente. También hacer un trailer bien comercial.</p>
            <p>              M: Vi el trailer de “Aniceto”, y me pareció muy delicado. ¿Le parece que es muy comercial?<br />
            F: Sí, es muy comercial. Pero tampoco tiene por qué ser una porquería. La gente también rechaza la porquería. Yo he puesto lo mejor de mí y con la conciencia de lograr una comunicación comercial. Yo puse aquello de lo que estoy convencido, si a mí no me moviliza, va a fracasar. Porque hemos perdido la capacidad de ser espectadores. Yo voy y observo. ¿Cuánto tiempo he estado escuchando esos llamados telefónicos al programa de Baby Etchecopar, para ver quiénes hablaban, cómo hablaban, hacia dónde está dirigido el público? A partir de ahí encaro la publicidad. Si uno se pone a buscarle la quinta pata al gato e intenta deslumbrar con un afiche, ahí es cuando pierde. Tu obra está en tu obra, todo lo demás, venga, vea, compre… Eso hay que metérselo bien en la cabeza. En una oportunidad, tenía que hacer publicidad y no tenía ningún elemento fuerte como para convocar a los medios. No bien terminé el guión lancé un aviso pidiendo gente de distintas alturas, unos muy altos y otros enanos. La vereda se llenó de enanos y de gigantes. En realidad no los iba a usar para el film, pero vinieron todas las cámaras de televisión a ver qué estaba pasando. Para mí eso no está mal. Siempre hay que ir maquinando, paralelamente a la escritura del guión, cómo hacer para alimentar a la prensa. Pero también hay que tener cuidado de no pasarse o te puede ocurrir como a mí con “Gatica…”. ¡Fue tan tremenda la promoción que llegó un momento en que la gente ya no sabía si la había visto a no! Juro que fue así, por eso hay que ir midiendo la cantidad de información. Con “Gatica…” saturamos a la gente.</p>
            <p>              M: ¿Hay algún tema o algún personaje de los que diga “yo nunca haría una película sobre esto”, o “esto no es para mí”?<br />
              F: Sobre los acontecimientos de los últimos años en el país… Sobre la dictadura. No lo soportaría. Me haría mucho daño y ahora siento que tengo que preservar mi salud. Además, hay otros que lo están haciendo y lo hacen muy bien.<br />
              M: Usted pasó de hacer películas con temas contemporáneo a hacer películas de época, o fantásticas. ¿Dónde y por qué se dio este salto?<br />
              F: El salto estuvo cuando empecé a recibir premios de todos lados y seguía viviendo en el departamento que me pagaba mi madre. Eso no era lo que yo quería, yo quería ver la sala llena. Por esa época estuve en Mendoza y vi Juan Moreira en teatro. Enseguida me puse a trabajar en eso, porque sabía que iba a dar dinero. Recuerdo que la quería hacer con Toshiro Mifune, en esa época daba el físico, incluso su rostro achinado. Pero la gente de Aries Cinematográfica se asustó. Pensaron que estaba loco y me quedé sin productora, no la entendieron. Después hice “El dependiente”, y después me dediqué a cantar…<br />
              M: Pero alguna vez sintió: “acá me estoy yendo para el otro lado”.<br />
              F: No, yo voy para donde quiero, a mí no me obliga nadie.<br />
              M: Yo siento igual.<br />
              F: Se nota en tu cine. No podrías hacerlo…<br />
              M: De todas formas no siento que haya algo que no haría.<br />
              F: Hay 20 millones de cosas que yo no haría. Tampoco haría un cine procaz, un cine vulgar…<br />
              M: Yo lo intentaría, pero creo que me saldría mal.<br />
            F: Una vez vino un chino que tenía una distribuidora muy importante en los Estados Unidos. Me compró “Nazareno…” y un día me visita en el hotel y me empieza a decir que teníamos que hacer películas bien “chenchual”, “le agregamo cosita a película Nazareno…” “pero usted tiene que filmar escena bien chenchual, chica linda…”. Yo estaba preparando “Gatica…” y le dije “váyase, por favor, porque le acepto todo ya”. El cine puede ser también muy impudoroso. Pero no sé, puede haber mil cosas que no haría, nunca me puse a pensar en eso. Siempre he tenido mucha suerte. He filmado todo lo que soñé, y lo que descarté, lo descarté por algo. En otra oportunidad le había comprado a Héctor Olivera el libro de Severino di Giovanni, gasté un montón de plata en aquel momento. Pero un día me di cuenta de que no la quería hacer. La gente se iba a enamorar de un personaje que vive en una época con circunstancias muy distintas, y después va a sufrir cuando lo fusilan. Pensé que no quería inspirar al a gente joven a que se destruyera y por eso lo descarté. Pero además de eso, hoy en día hay películas que no haría porque es necesario tener toda la energía de la juventud; en ese sentido, para muchas películas el director tiene que estar en muy buen estado físico.</p>
            <p>              M: Sí, es cierto, yo corro todos los días dos kilómetros.<br />
              F: Es muy bueno eso, los rodajes pueden ser muy exigentes físicamente.<br />
              M: Pero esta película era muy grande también.<br />
              F: Pero la hice toda en un galpón, al estilo Méliès, muchos de los soles que aparecían de fondo son telones del teatro Colón, todo lo hice con cosas así… En un momento estuve por filmar la guerra de la Triple Alianza -una idea que después me quedó para toda la vida-, pero ¿cómo lo hago? Ya no puedo, no estoy en condiciones físicas, sería un insensato. Tengo que hacer un cine que mis condiciones físicas me permitan. “El mantel de hule”, por ejemplo. Para esa época voy a estar caminando más o menos bien ya. El físico impone un tipo de limitación, pero después hay que ser consciente de que la utilización de la cámara es siempre una cuestión moral, como bien lo dijeron los maestros europeos. Uno tiene que saber lo que va a hacer con ese instrumento. Y tratar siempre de que sea una maravilla.<br />
              M: ¿Pero existe algún director que no lo intente?<br />
              F: Lo intentan. Pero no saben. A esa gente, esos chicos o esos viejos, uno tiene que sacarlos de la conversación, porque ensucian la charla y no aportan nada. Uno tiene que charlar con la gente que tiene cualidades para esto, que no tienen complejos idiotas. A todos los demás hay que ignorarlos. Qué vas a hacer, si se equivocaron de vocación, es imposible explicárselos. Yo, por ejemplo, soy alguien que goza de sus insomnios… En general me acuesto a eso de las nueve. Pero a eso de la una y media ya estoy despierto. Entonces me pongo a leer, a garabatear, a pensar, y si el sueño no aparece, sigo garabateando, hasta las nueve de la mañana y ahí me acuesto hasta las dos de la tarde más o menos. O sea, le obedezco al cuerpo y también respeto los tiempos de mis sueños. Supongamos que en esos momentos tengo ganas de pensar en “El mantel de hule”. Pongo una música bajita para no molestar y ahí se me van ocurriendo las cosas, las escribo, trabajo determinado personaje, vivo en mi mundo. A veces me dicen: “che, viejo, pero estás solo”. No, estoy conmigo, y estoy contento conmigo. También estoy cada día más con dios. Pero hay gente que, como no tiene eso, no lo puede entender.<br />
              M: Me parece que todo el mundo está bienintencionado. El esfuerzo de hacer una película es muy grande: es caro y es difícil conseguir la plata, hay que juntar a la gente, convencerla. Lo que sí siento es que a veces uno puede estar equivocado y no tener ningún mundo personal. Eso es terrible y me da pena.<br />
            F: Pero pueden ser visitadores médicos…</p>
            <p>              M: Sí, claro, pero cuando son colegas da pena.<br />
              F: Por eso nunca habrás oído que ya hablara mal de una película. Porque sé que les va la vida en eso. Aunque crea que se han equivocado de vocación. No creo que sea ninguna crueldad. ¿Qué gano yo con decirle “che, qué porquería que hiciste”? No, no puedo. Si me dicen “¿Qué le pareció?” “Inmejorable…”, contesto, y me voy.<br />
              M: Yo lo abrazo y le digo “¡qué hijo de puta…!” (Risas)<br />
              F: Esa es muy buena, es muy buena… ¿Che, no vas a volver agrandada de Cannes, no?<br />
              M: Qué voy a volver agrandada de allá, por dios. Si hay un lugar en donde uno no se puede agrandar es ahí.<br />
              F: ¿Te inhibe?<br />
              M: No. Pero creo firmemente que hay un momento en que uno vive como una monja, cuando está dedicada al proyecto, y después hay otro en que una debe transformarse en una bataclana, ese momento es el de ir a los festivales. Le sirve a la película, porque hay muchos vendedores, muchos distribuidores. Pero después, ¿quién se acuerda? Cuando uno piensa en las películas que ama, nunca recuerda en qué festival estuvo o qué premio ganó.<br />
              F: No. Pero en ese momento te sirve porque la colocás y de paso te das a conocer. Conseguís coproductores, etc.<br />
              M: Sí, pero no hace ni mejor ni peor a la película.<br />
              F: Por supuesto.<br />
              Hernán Guerschuny: Está bien, pero mientras tanto el cineasta es una persona ¿no? Imagino que le gusta que lo acaricien, que lo traten bien, que lo premien… Los festivales funcionan mucho en ese sentido también.<br />
              M: En un festival como el de Cannes te aseguro que no se la pasan acariciándote. Es una tensión enorme. Estás enfrentado tanto al tipo que le gustó tu película como al que no. Es exposición pura y es muy tenso. Te divertís solamente si organizaste muy bien con quién ir. Si no, no hay manera. Ni las fiestas son tan divertidas. No es el carnaval de Gualeguaychú.<br />
              F: Siempre me preguntaron por qué no iba a los festivales a competir por un premio. Y debo decir que es porque soy cagón. Si me garantiza que me llevo el premio mayor, entonces sí voy, pero si no, prefiero ir a las muestras paralelas, porque nunca quise competir con mis colegas.<br />
              M: Eso es lo mejor. Pero solamente puede hacerlo el que tiene asegurada la financiación de su próxima película. En mi caso, por ejemplo, no puedo darme ese lujo.<br />
              F: Pero también, no voy, porque si pierdo, lo pierdo todo. Me costó mucho ser Favio en este paisito. Por eso, para mí, las muestras paralelas.<br />
              M: Hay festivales que al no ser competitivos para mí son los mejores. Uno puede ver otras películas y no va a enfrentarse a una escala de valores determinada, sino a presentar lo que hizo. En cambio, Cannes es como en una riña de gallos. Es un festival en el que te pasás cuatro días encerrado en la habitación del hotel haciendo prensa y no, como imaginan algunos, con Benicio del Toro de copas por ahí… Para mí siempre fueron sorpresas inesperadas este tipo de convocatorias. Hay gente que cree que si una ha ido una vez al Festival de Cannes va a ir siempre. Como si tuviera una butaca alquilada. Pero a los franceses les encanta decidir sobre tu vida, si existís o no existís… Les encanta tener un poder de decisión sobre la cultura mundial, tiene que ver con cierta perversidad francesa. Entonces uno nunca sabe qué van a terminar haciendo, si les va a gustar o no. Yo pude vivirlo de cerca cuando fui jurado.<br />
              F: Y a veces es muy feo cómo deciden, ¿no? “dame ese voto para esa película y yo te doy el mío para tal otra”.<br />
              M: En realidad, dentro del jurado, el festival no puede meterse. No hay forma. Siempre es como una negociación en la que triunfa el placer que sintieron los que vieron tal película. Por ahí es un placer que hubiese preferido en muchos casos que no lo sintieran, por tratarse de películas inmundas. Increíblemente realizadas, pero inmundas ideológicamente. Pero si ellos son mayoría, ¿qué vas a hacer? Pero que manipulen al jurado es imposible. Por lo menos yo participé de los jurados en Sundance, en Berlín y en Cannes y nunca me pasó algo así. Imaginate que en general los jurados son todos gallitos, no les vas a venir a decir qué película querés que elijan. ¿Pero usted tuvo la suerte de nunca tener que mandar una película a competir?<br />
            F A San Sebastián, una vez. Me echaron como a un idiota.</p>
            <p>              M: ¿Por qué?<br />
              F: Por que estaba Franco en ese momento y a mí no se me ocurre mejor cosa que pedir un minuto de silencio por la muerte de Allende en Chile. Al otro día estaba con todas las valijas del otro lado de la frontera.<br />
              M: Pero bueno, valió la pena. ¿Y “El mantel de hule” ya está escrita?<br />
              F: Es raro lo de “El mantel de hule”. Estoy escribiendo primero los perfiles de los personajes. Personajes muy puntuales. Es la primera vez que trabajo un guión de esta manera.<br />
              M: ¿Cómo lo suele hacer?<br />
              F: Lo elaboro todo, a veces estoy inspirado y escribo el final. Después sigo con la mitad, por ejemplo. Pero acá no tengo una estructura. La iremos acomodando mientras caminamos. Creo que los personajes me van a ir llevando. Tengo claro los destinos de varios de ellos ya. Y además, te voy a robar una actriz: Graciela Borges.<br />
              M: Con todo gusto. Pero más bien la va a recuperar, ella ya hizo una película con usted. Ella también me contó un montón de anécdotas.<br />
              F: Nos conocemos de muy jóvenes.<br />
              M: ¿Hubo romance?<br />
              F: No… ¿No te contó de cuando me pegó una patada en el culo? Una vez yo estaba enojado con ella, y estábamos filmando sobre una escalera. En “Fin de fiesta”. Ella estaba hablando y decía “porque yo, que vivo en Barrio Norte”. Entonces me doy vuelta, ella estaba en la escalera, arribo mío, y le digo: “Pero qué Barrio Norte… Si siempre que nos vamos en taxi vos te bajás en Congreso”. Entonces ella pega un grito: “¡Negrito de mierda… Que hacés ruido con la sopa…! ¡Si serás pelotudo!” Y me da una patada en el culo que me manda debajo de la escalera. ¿Te das cuenta lo que es mi vida?… Qué bonita que era y que sigue siendo. Y además es una actriz enorme.<br />
              M: Para mí fue una lección de cine trabajar con ella.<br />
              HG: ¿Puedo preguntas por qué?<br />
              M: Es que uno tiene una imagen de ella como muy demagógica, que es a lo que ella juega en público. Pero cuando filma es otra cosa totalmente distinta. Es una gran profesional. En “La ciénaga” había una escena al borde de la pileta, en la que se tenía que tirar y había vidrios en el borde, los vidrios eran de verdad, no eran de caramelo…<br />
              F: ¡Sos loca! ¿En serio?<br />
              M: Sí, porque no teníamos falsos. Los únicos vidrios que eran de mentira eran los que tenía pegados en el cuerpo. Y había una lluvia que bombeábamos de la pileta, que tenía un agua bastante estancada y helada. Toda esa película se hizo en medio de un frío atroz… Cuando empezamos a bombear el agua comenzó a salir un olor terrible y yo sentí que ese escena no la filmábamos nunca más. Habíamos hecho una toma, habíamos hecho otra y todavía no estaba bien y le dio “Graciela, ¿no querés que sigamos mañana?” y me dijo: “¡Pero cómo se te ocurre!” Así que seguimos adelante. Y veía cómo tenía que calcular para no lastimarse, estaba helado y los vidrios ahí al lado, ella llevando las copas, que también eran de vidrio, caminando entre las sillas, después caerse con las copas. Fue peligroso.<br />
            F: Es hermosa esa escena, una secuencia muy fuerte…</p>
            <p>              M: En ese momento nadie del equipo tenía mucha experiencia, y cada vez que se prendía la cámara te dabas cuenta de que ella era la única de todos nosotros que sabía que ese ruido significaba “ahora todo se va por ese agujero”. Es el momento en el que todo debe suceder. Recuerdo que un solo día protestó por un camisón. Tenía razón, el camisón no le quedaba bien. Y entonces se puso incómoda. Era el último día de rodaje en esa casa y esa escena era fundamental, era imposible terminar la película sin esa escena. Entonces, como ya había tenido la experiencia de la pileta, le dije: “Bueno, Graciela, no hagamos esta escena, no vale la pena, no la hacemos”. Y ella enseguida dijo: “¡Pero cómo se te ocurre, traé la cámara!” Es así, es el amor por el cine.<br />
              HG: Ustedes dos, cada uno en su versión, son muy seductores. Me imagino que así lo deben ser también con sus actores. ¿Les ha pasado alguna vez que en plena película se dieran cuenta de que no podían seducir al actor?<br />
              M: Sí.<br />
              F: ¡Cómo sufrí!<br />
              M: Pero siguió adelante…<br />
              F: Sí. Porque no tenía más remedio. Ya estaba. Cuando él me miraba mantenía mi sonrisa a muerte, en esos casos me puede hacer pis en la cabeza que yo lo miro con los pulgares arriba y le digo: “bárbaro loco…”<br />
              M: Obvio: “inmejorable” (risas). A mi me parece que para estar seguro de un actor, uno tiene que desearlo. Pero realmente desearlo. Como si estuviera enamorado.<br />
              F: Qué bien que lo decís, es tal cual.<br />
              M: Es que si no, sucede que uno no sabe lo que mira a través de la cámara. Yo necesito, no digo tener un romance con los actores, pero sí que me gusten mucho. Que me encante mirarlos. Necesito eso. Si no, no sé ni dónde poner la cámara.<br />
              HG: No sé si estarán de acuerdo con esta afirmación, pero algunos dicen que uno debería llevar a la pantalla traumas que uno ya tiene resueltos y no los no resueltos. Primero quería saber si estaban de acuerdo con esto y, en segundo lugar, saber si se analizaron o se analizan.<br />
              F: Si no tenés cosas raras en la cabeza no podés hacer cine, creo yo.<br />
              M: Yo no me analicé pero porque soy católica. No creo que esté bien analizarse si uno es católico. Aunque sea una católica hereje. Me parece que la idea del trauma no sirve, si alguien resolvió algo, quiere decir que no era un verdadero problema. Porque las cosas se transforman pero no desaparecen. Encarar la búsqueda de uno mismo a través del concepto de trauma me parece un problema gravísimo. Esa idea de la descripción psicológica de los personajes tampoco, nunca la entendí.<br />
              F: No, yo nunca me metí en ese mundo porque no lo conozco. Es muy complejo para mí. Pero ojo, yo me psicoanalicé hace poco y me sirvió.<br />
              M: Últimamente he recibido mails en donde directamente me mandan el teléfono de la terapeuta, como diciendo “tenés que ir porque estás mal”. Pero bueno, hay a quien le sirve… Pero construir una película desde la idea de la psicología de los personajes y del trauma del director me parece un error.<br />
              HG: Pero hay muchos que pretenden, con lo que filman, llevar a la pantalla sus propios traumas.<br />
              M: Yo agradezco todos los traumas que tiene Cronenberg, por ejemplo, que nunca se psicoanalizó.<br />
            HG: Y cuando un actor les pregunta sobre la psicología de los personajes, que es una pregunta del actor bastante común, “¿de dónde vengo?, ¿cuál es mi historia pasada, mi motivación?”, etc…</p>
            <p>              M: Sinceramente, no lo sé. Lo que sí por ahí puedo saber es si están enfermos, alguna cosa puntual que se pensó para el personaje, peor no todo su pasado.<br />
              F: Yo le digo “mirá, no te hagas ningún problema. Yo tengo toda la película acá, en la cabeza, y yo sé cómo empieza y cómo termina. Vos hacé lo que te pida en cada toma. Para mí la película completa está en cada instante, en cada marcación. No preguntes nunca por qué, nada”.<br />
              M: Pero eso para algunos actores es como una falta de respeto.<br />
              F: Pero yo lo hablo mucho. No lo digo así a lo bestia. Ellos tienen su libro, ya saben de que se trata de una escena dramática, que lo van a matar, van a pelear, etc. Ahora, después, cada plano es mío, es como una arcilla, vos lo vas modelando en el primer plano: “tragá saliva, pestañeá”; en el plano conjunto, que es en donde el actor está más desprotegido, lo hago con las marcaciones.<br />
              HG: Lucrecia, supongo que también te reconocés en esa obsesión por la marcación al detalle.<br />
              M: Lo que sucede es que a veces hay tantos elementos que el actor desconoce que van a estar en la película… Sonidos, esas cosas que van se van a agregar poco después o cosas que están pasando por detrás, en otro plano visual o narrativo.<br />
              F: Exactamente.<br />
              M: El actor no está en todas las instancias de factura de la película, es imposible. Es como pasa con los chicos, lo único que se puede hacer es decirles: “ahora caminá así, da vuelta acá, a ver, vení para acá”. Salvo que haya una escena en donde un personaje tenga que construir algo en particular, entonces hay que explicarle un poco y soltarlo.
              <br />
            </p>
<p></p>
          </div>
        </div>
      </div>
      <div id="banners">              
        <?php include("inc/banners.php"); ?>
        <?php include("inc/archivo_entrevistas.php"); ?>
      </div>
    </div>
    <div class="push"></div>
  </div>
<?php
  include("inc/footer.php");
?>