<?php
  include ("inc/head.php");
  $GLOBALS['interna'] = true;
  include ("inc/header.php");
?>
    <div id="centro" class="arteliteratura">
      <div id="izquierda">
        <div id="arteliteratura">
          <div class="barra_titulo">
            <span></span>
            <h1>Arte &amp; Literatura</h1>
            <span class="tail"></span>
          </div>
          <div id="header_slider">
            <img src="uploads/lisandro.jpg" title="Header entrevista" alt="Torre de Babel" />          </div>
          <div id="texto_entrevista">
 <p><strong>de Juan Almada</strong></p>
 <p><strong>1. Introducción</strong></p>
<p>La vieja cuestión marxista de la ideología, se reaviva en los últimos años como una vertiente crítica para analizar al cine. Slavoj Žižek escribe en “El sublime objeto de la ideología”:</p>
 <p>“…tomemos el procedimiento clásico de la “crítica de la ideología”: este procedimiento “desenmascara” un edificio teórico, religioso u otro haciéndose posible “ver a través de él”, haciéndonos ver en él “sólo una apariencia ideológica “espontánea”, “no reflejada”, en su positividad dada-inmediata. Para llevar a cabo el pasaje de la reflexión postulativa a la externa, el movimiento de reflexión tiene que tomar nota de cómo está siempre vinculado a algunas presuposiciones dadas, externas, que de manera subsiguiente son mediadas- superadas a través de su actitud negativa. En suma, la actividad de postulación ha de tomar nota de sus presuposiciones – externas al movimiento de reflexión, aquellas que son precisamente sus presuposiciones.” </p>
 <p>Entendida como el principio que modula entre lo que vemos y lo que dejamos de ver, la ideología puede manifestarse materialmente de formas diferentes. Una de ellas consiste en internalizar un elemento problemático al horizonte discursivo como necesidad superior (integrándolo como resultado de un proceso); u otra consiste en externalizarlo a la distancia como forma de desligarse de sus causas (determinándolo como pura contingencia). Ya en el terreno de la ficción, las películas de género ejemplifican a ambos procedimientos con claridad. Del primero podemos dar cuenta a través de los motivos recurrentes del cine-catástrofe contemporáneo. Cuando se produce el tsunami, el huracán o el terremoto, sus razones de ser a menudo se deben a cierto impulso culposo que recae sobre los hombres, de tal forma que el trauma catastrófico se integra como el castigo que estos reciben por su repetida negligencia para con el medio ambiente (el viejo mantra ecologista). Y del segundo caso, se puede dar cuenta a través del fenómeno representativo de los westerns más convencionales. En ellos, los indios son presentados como unos bárbaros que amenazan a la civilización y a los buenos colonos que la encarnan. Percibirlos de esta forma, permite explicar su comportamiento violento como un fenómeno externo que no obedece a causas intrínsecas de la conquista (como una respuesta a ella).</p>
 <p>   La cuestión, en ambos casos, pasa por constatar que el verdadero significado no se esconde detrás de la forma del relato (significado oculto), sino que permanece cifrado  negativamente en la forma a través de la que ese relato se estructura.<br />
   Asimismo, en el nuevo panorama teórico (del en-sí al para-sí), se descarta la vieja oposición entre un argumento “sesgado por la ideología” y otro verdadero, que permanece próximo a cómo son las cosas en realidad. Siguiendo a Žižek, resulta claro que la veracidad o falsedad de una posición ideológica no la hace menos ideológica. De tal forma que la posibilidad de comprobar empíricamente alguna de las posiciones queda fuera de la órbita del análisis. Todos los discursos, independientemente de su capacidad de ser comprobados empíricamente, suponen un universo simbólico que es anterior, en la medida en que operan en el nivel del convencimiento o, por ponerlo en otros términos, del inconsciente. Como escribe Lacan: “nada falta en lo real, toda percepción de una falta o un exceso (“demasiado poco de esto”, “demasiado de aquello”) siempre su pone un universo simbólico [que lo atraviesa]” .<br />
   Ya en un plano más próximo a nuestra realidad, podemos pensar que la persistente recurrencia del nuevo cine argentino de posar su mirada sobre la marginalidad, impone la necesidad de una lectura ideológica acerca de los presupuestos sobre los que estas miradas se sustentan. Es decir, referente a la forma bajo las cuales la marginalidad es integrada discursivamente. Me gustaría ensayar una lectura crítica bajo este enfoque, en las películas de Lisandro Alonso.</p>
 <p><strong>2. Una aproximación</strong></p>
 <p>En el panorama del nuevo cine argentino, se impone la imagen de Lisandro Alonso como el artista bohemio por excelencia. No sólo los típicos procesos del cine de arte como la acentuación del efecto de realidad o los motivos narrativos que se repiten en su obra le sirven de sustento a esa imagen superficial, sino también la propia imagen extratextual que el director da al público en sus apariciones. Los lugares comunes de poeta elitista que despotrica contra el “bajo nivel cultural del espectador” o su repetida renuencia a salir de circuito marginal para no reducir sus películas a la venta de “pochochos y coca-cola” sirven de ejemplo bastante común. Casi podría resultar fácil confundirlo con un pequeño estudiante de cine que grita agitado contra un mundo que no lo comprende.<br />
   Reflexiones ingenuas que repite como la idea de “salir a filmar” parecieran asimismo ir en paralelo con las consideraciones anteriores, e intersectarse con las lecturas más convencionales que la crítica ha hecho de su obra. Pero plantear una lectura alternativa sobre ella conlleva hacerse la siguiente pregunta: ¿Qué si los motivos recurrentes en sus películas se estructuraran entorno a cierto atolladero, a cierta imposibilidad que – si bien oscura – persiste cifrada negativamente en su poética autoral?<br />
   Habría que abstraerse de una aproximación errada, consistente en retrotraer los motivos recurrentes de esa poética a la tentativa más o menos explícita de Alonso de establecer una mirada inocente, de tipo que sale a encontrarse con el mundo a expensas del ojo urbano demasiado sobrecargado, incapaz de mirar profundamente. La pregunta sería: ¿cuáles son los presupuestos teórico-formales que hacen posible la constitución de tal aproximación? Conforme con las tesis contemporáneas de la ideología, podríamos pensar que esos presupuestos tienen una existencia material y están presentes – aunque secretamente – en los procedimientos que sus películas adoptan. Intentaremos, a través de una lectura de estos procedimientos, rastrear aquellos presupuestos.<br />
   Nuestra hipótesis consiste en que detrás de esa imagen burda e ingenua de artista bohemio que rechaza superficialmente los mandatos del mercado, hay otra figura construida por sus películas que acarrea consecuencias mucho más profundas. Pesaremos algunas de las categorías que constituyen sus películas en relación con otras categorías del imaginario posmoderno.</p>
 <p><strong>3. Idea de naturaleza</strong></p>
 <p>Una de las tensiones principales que atraviesan la obra de Alonso es la tensión entre lo marginal y lo social, donde ambos contingentes son mediados de alguna forma por el nomadismo de los personajes. Principalmente en “La libertad” y “Los muertos” está presente la idea de la naturaleza como espacio de fuga ante las inconsistencias/ dificultades de lo social. En el primer caso se trata del campo pampeano y en el segundo de la selva misionera. <br />
   En “La libertad” la dicotomía se piensa a través de la marginalidad absoluta de un hachero en el medio del bosque, donde choca la intromisión de la radio y la presencia esporádica de marcas que el mismo consume (Fanta, YPF). Es decir que la modernidad llega a este espacio marginal de La Pampa en cuentagotas, y prima un contacto con lo originario que se materializa en el hecho de que el personaje extrae aquello que necesita (alimento, calor) del medio ambiente.<br />
   El rol que la naturaleza adquiere en películas como “La Libertad” puede pensarse en tensión con las ideas posmodernas que promueven una vuelta a ella para redimir algún aspecto legítimo originario, que se desprecia en la vida social contemporánea. La esencia de esa tensión podría problematizarse si se tiene en cuenta que el nombre del film podría sugerir un posicionamiento ingenuo a favor de lo primero (la libertad de vivir en la naturaleza) explicando la presencia de lo segundo (los retazos de modernidad) como un “mal necesario”. No obstante, habría que remitirse al hecho que el personaje se encuentra en esa posición porque debe vender su fuerza de trabajo, o sea la leña que extrae. El estar “fuera de lo social” no tiene una cualidad afirmativa sino más bien negativa (como una carencia o una falta) donde el contacto con lo orgánico obedece a causas sistémicas de lo social, es decir a la imposibilidad de ganarse la vida de otra forma. “La libertad” no es la vindicación de ese contacto primitivo (como el nombre pareciera indicar) sino que es la constitución de una ambigüedad, de un algo problemático entre el contacto y la necesidad persistente de vender la fuerza de trabajo. Finalmente el personaje vive aislado con ese único objetivo; es un residuo de lo social.<br />
   En “Los muertos” el caso es diferente. Se trata de un personaje, Argentino, que vive en lo social (una prisión) porque debe purgar un crimen. Y el relato no atañe a cómo la marginalidad se constituye como el remanente de lo social sino que implica a ésta en su propia particularidad. Aquí, la marginalidad de la naturaleza a la que Argentino retorna  (el viaje de vuelta que retrata el film) ya no se construye negativamente sino en apariencia como pura afirmatividad. Argentino es un marginal antes de haber matado a sus hermanos, y su experiencia en lo social no implica efectivamente a su marginalidad. El se relaciona con la naturaleza a través de unas habilidades de supervivencia anteriores a la prisión, y de carácter puramente instrumental. Su percepción está atravesada por esa funcionalidad y se expresa en el recorrido que realiza: visita a una prostituta para descargar su deseo sexual, mata un cabrito para alimentarse, y se acerca a un viejo conocido sólo para que lo ayude a cruzar el río. Podría pensarse que “los muertos” no sólo remiten al crimen pasado de Argentino, sino también a él mismo en la medida en que se relaciona de forma estéril e inanimada con el entorno. Ve en  las personas (así como en la naturaleza) no más que aquello que puede serle útil para sobrevivir. Por ello resulta difícil de asimilar la escena en la que mata al cabrito, dada la frialdad que se asocia al crimen del comienzo. En un sentido preciso, sus hermanos se reactualizan en el cabrito por medio de la instrumentalidad vacía del protagonista que asemeja a todos los objetos, el machete comete ambos “asesinatos”. Bajo esta clave también podemos leer el final del film, cuando Argentino llega a la casa de su hija y se encuentra con su nieto, observa su pequeño juguete extrañado durante un momento y luego lo arroje indiferente al piso. Es un objeto que carece de valor para Argentino porque excede a su percepción instrumental, no puede hacer ningún uso de él. <br />
   Es decir que el reverso negativo de la “vida en la naturaleza” de Argentino es una concepción de la naturaleza ligada a lo material con la que él se asocia por proximidad. Es una idea que trasciende a la calma con la que los hombres urbanos la describen, y que permanece relacionada a lo monstruoso. De esta forma, “Los muertos” es una película mucho más pesimista que “La libertad”. Mientras que en la segunda todavía podía decirse que el contacto con la naturaleza carecía de un sustento verdadero dado que estaba constituida negativamente por el personaje (era una deformación), en “Los muertos” el contacto del protagonista es tan cercano que asusta. Argentino es un muerto porque su comportamiento se identifica con la naturaleza de forma estricta, carece de humanidad. Y en esa naturaleza no hay nada positivo para reivindicar, por ello el posmodernismo organicista no encuentra aquí ninguna imagen a la cual aferrarse.</p>
 <p><strong>4. La identidad marginal</strong></p>
 <p>La tercer película de Lisandro Alonso, “Liverpool” trabaja sobre un trasfondo diferente. El protagonista escapó de lo social a partir de una dificultad (hacerse cargo de su hija), y vuelve con intenciones desconocidas. Mientras que en “La libertad” Misael huía de lo social por las propias consecuencias sistémicas, y en “Los muertos” Argentino retornaba a lo marginal por su propia naturaleza anterior, en “Liverpool” Farrell vuelve por consecuencia de un trauma originado en sus propias acciones (el abandono de una hija mentalmente discapacitada). Nunca queda claro si el personaje siente remordimiento o precisamente qué, pero esa indeterminación nos permite decir que contrariamente a las anteriores, esta es una película de los sentimientos más que de la materialidad. Y en este sentido reactualiza el problema de la tensión entre la mirada del director y la de sus personajes. Si en “La libertad” y “Los muertos” los personajes querían cosas precisas, en “Liverpool” Farrell emprende todo un viaje que nunca termina de llevar a cabo. Al arribar a su pueblo y constatar que su madre no lo reconoce y que no puede establecer ningún contacto con su hija, le hace un regalo y desaparece. Y ante esta imposibilidad de expresar, se retoma la importancia de los objetos como significantes extendidos. El llavero con el nombre de Liverpool que Farrell le regala a su hija adquiere la expresividad que él ya no puede manifestar. Es una función que puede pensarse en contradicción con el empleo narrativo que del  otro muñeco se hace, sobre el final de “Los muertos”. Mientras Argentino abandona al objeto porque no puede obtener ninguna funcionalidad de él, Farrell lo regala con el objetivo de comunicar afectivamente aquello que ciertas condiciones no le permiten comunicar en palabras. En el primer caso se trata de prescindir de una posesión por falta de funcionalidad, y en el segundo de prescindir de otra para que brote cierta funcionalidad afectiva que el personaje no está capacitado para expresar.<br />
   Los dos mundos entre los que se desplaza “Liverpool” son, por un lado el mundo de los containers, barcos y camiones del puerto donde embarca Farell, y por el otro el de el conjunto pobre y aislado de casas agrupadas en lo que llama su “pueblo”. Uno, el mundo de la mercancía y el otro, el de la afectividad. Pero no se trata de una afectividad construida por el recuerdo nostálgico de un tiempo anterior, y asociado a la felicidad de vivir cerca de la familia, sino a una imposibilidad de comunicar racionalmente. La madre, muy deteriorada, ya no recuerda a Farrell, y la hija, mentalmente incapacitada, tampoco lo reconoce; sólo pueden relacionarse a través de los afectos. Hay una inconmensurabilidad entre la instancia de donde procede el protagonista y a la que arriba. Un bache que no puede ser cerrado por el protagonista.<br />
   Es decir que a través de actitudes negativas diferentes, las tres películas de Lisandro Alonso expresan ciertas presuposiciones necesarias para emitir discurso sobre distintos tipos de marginalidad. En “La libertad” estas consisten en que el protagonista es el espejo inverso del sistema (correlato interior y necesario del mismo), en “Los muertos” porque subyace una concepción ligada asimismo a una idea particular de naturaleza, y en “Liverpool” porque es un vacío que consiste en la imposibilidad de conocer aquello que Farrell persigue, dada su incapacidad de hablar el lenguaje del lugar al que llega.</p>
 <p><strong>5. El problema de la mirada</strong></p>
 <p>A pesar de que las películas de Lisandro Alonso se construyen sobre un fuerte registro documentalizante haciendo énfasis en el efecto de realidad que pretenden imponer, subyace una tensión latente que se manifiesta en momentos precisos de recursos altamente trabajados que parecieran no corresponderse con las premisas iniciales. Se repiten movimientos de desplazamiento de naturaleza diferente. En primer lugar están aquellos travellings de alto virtuosismo técnico y movimientos de cámara de sofisticada realización, como el plano inaugural de “Los muertos”, la escena de la llegada del auto en “La libertad”, o bien aquella de “Liverpool” cuando Farrell es llevado al pueblo. El procedimiento tiende a ser más o menos uniforme: la cámara se despega de los personajes, como un “órgano sin cuerpo” y comienza a moverse caprichosamente por el medio sin un rumbo preciso. Se suman, como segundo nivel de anomalía, las miradas a cámara que se repiten a lo largo del primer film y que chocan con cierto grado cero documental, sugerido por un realismo excesivo que llega hasta filmar al hachero defecando en pantalla.<br />
   Aunque podrían leerse estos momentos como una excepción desequilibrada de su registro, o una deformación de sus supuestos, un análisis encaminado tendría que interpretarlos como el síntoma de una concepción estética autoral que subyace. Contrariamente a los films convencionales del realismo, que tienden a esconder las huellas del autor en beneficio de cierta transparencia de sentido, estos procedimientos rompen con el código representativo uniforme y establecen cierta ambigüedad del registro, que combina el realismo documentalizante con la personalidad del director. Podría pensársela como una concepción de autor que busca reconciliar a un sujeto determinado, productor de discurso, con aquel objeto que toma como referencia. Indica, a su vez, que la intervención del cineasta no consiste en una presentación “directa” del mundo narrado, sino que ésta resulta filtrada por sus propios presupuestos, sobre esta base podemos leer las consecuencias derivadas. Y es una concepción que explicita, finalmente, que la apropiación del mundo está hecha en beneficio del autor. De otra forma, concibe Alonso, no se podría hablar de semejante “otro” radical.</p>
 <p><strong>6. A modo de conclusiones</strong></p>
 <p>Retomando los estudios de Ernesto Laclau, Žižek escribe acerca del concepto de “punto nodal”:</p>
 <p>“¿Qué es lo que crea y sostiene la identidad de un terreno ideológico determinado más allá de todas las variaciones posibles de su contenido explícito? Hegemonía y estrategia socialista traza lo que tal vez sea la respuesta definitiva a esta pregunta crucial de la teoría de la ideología: el cúmulo de “significantes flotantes”, de elementos protoideológicos, se estructura en un campo unificado mediante la intevención de un determinado “punto nodal” (el “point de capiton” lacaniano) que los “acolcha”, detiene su deslizamiento y fija su significado.” </p>
 <p>En el tercer apartado de este trabajo hemos descripto dos movimientos ideológicos diferentes que están presentes en las primeras películas de Alonso. Describimos a “La libertad” como desplazamiento integrador de un tipo específico de marginalidad, cuyo objeto consiste en explicar a la misma como el reverso del sistema y correlato necesario del mismo, es decir como resultado de un proceso. Luego interpretamos a “Los muertos” como ejemplificadora de un proceso inverso, en la medida en que toma otro caso de marginalidad construido no como resultado de un desarrollo anterior, sino en su especificidad, es decir entendida como pura contingencia. Son dos variaciones posibles – sin duda diferentes – estructuradas en torno a un “punto nodal” que situamos como cierta concepción de la naturaleza. Se trata de rechazar la idea moderna ingenua (e ideológica por excelencia) de entrar en contacto con ella para redimir algún aspecto originario y legítimo del hombre que se pierde en la alienación de la vida moderna. En las películas de Alonso naturaleza se configura en retrospectiva como un lugar donde ese “algo” que los discursos organicistas posmodernos reivindican, todavía permanece ausente. <br />
   En el siguiente apartado, hemos abierto un poco más el foco y hemos integrado “Liverpool” a partir de cierta mirada de la marginalidad que comparte con las películas anteriores, pero que ya no tiende a fijarse en una concepción de la naturaleza sino que puede sintetizarse en la marginalidad como la idea de una falta o, por ponerlo en otros términos, en la imposibilidad de describir a la marginalidad afirmativamente. Y finalmente, en el quinto apartado, hemos intentado explicar cómo la perspectiva autoral que defiende Alonso está por definición imposibilitada de hablar en dichos términos afirmativos, porque reconoce que el único foco que tiene para ver el mundo es el de un sujeto que es ajeno a aquel otro que toma como referente. Las marcas que rompen con el registro “realista”, no son más que las manifestaciones de la presencia de ese sujeto externo. Se trata de toda una operación ideológica que no puede sino explicitarse en dicho procedimiento.<br />
 </p>
 <p> <br />
   Bibliografía<br />
   Žižek, Slavoj. “El sublime Objeto de la ideología”<br />
   Žižek, Slavoj “Ideología. Un mapa de la cuestión.”</p>
 <p>Nota por Juan Almada<br />
 </p>
          </div>
     
        </div>
      </div>
      <div id="banners">
        <?php include("inc/banners.php"); ?>
        <?php include("inc/archivo_arteyliteratura.php"); ?>
      </div>
    </div>
  </div>
<?php
  include("inc/footer.php");
?>