<?php
  include ("inc/head.php");
  $GLOBALS['interna'] = true;
  include ("inc/header.php");
?>  
    <div id="centro" class="entrevistas">
      <div id="izquierda">
        <div id="entrevistas">
          <div class="barra_titulo">
            <span></span>
            <h1>Entrevistas</h1>
            <span class="tail"></span>
          </div>
          <div id="header_slider">
            <img src="uploads/entrevistas/lisandro_alonso.jpg" title="Entrevista a Juan Minuj&#237;n" alt="Entrevista a Juan Minuj&#237;n" />          </div>
          <div id="texto_entrevista">
            <p><em>En su discurso, casi como un leitmotiv, el verbo “salir” se reitera obstinadamente. Sus películas, en efecto, se originan en la perseverancia en llevar la cámara más allá del lugar donde vive, en salir fuera de su círculo de pertenencia. Pero no se trata de la búsqueda de exotismos más o menos pintorescos y tampoco de la reivindicación pueril de otredades. En las imágenes de Alonso se cifran enigmas y extrañezas que definitivamente apartan su cine de esas fórmulas gastadas.<br />
            </em></p>
            <p><strong>En la primera nota que te hicieron en El Amante a propósito de La libertad, Quintín te definía como un “extraterrestre”, un “raro”. Y después, en ese mismo número, vos usabas ese adjetivo para referirte a Kiarostami: el “cine raro de Kiarostami”, decías.<br />
            </strong><br />
              Esa nota es de 2001, era la época de los primeros Bafici. Ahora no considero que mis películas sean raras. Habría que medir también raro en relación con qué. Si lo no raro es el cine más convencional, sí, soy rarísimo. En aquel momento debo haber mencionado a Kiarostami por El sabor de la cereza. Esa película me llamó mucho la atención porque el tipo había creado algo importante con muy pocos elementos: un hombre, una camioneta, una montaña y cuatro o cinco personajes más. Y el drama del suicidio, claro. Pero sacándole ese drama, yo descubrí que se podía hacer algo con muy pocos elementos, en escenarios naturales. Tomé El sabor de la cereza como ejemplo no para hacer algo similar, sino en el sentido de hacer una película con pocos elementos. Yo había estado trabajando mucho en La Pampa y descubrí a Misael en el medio del monte y dije: “Con este tipo se puede hacer una película”. Kiarostami me permitió además salir de Jarmusch, que de todos modos sigue siendo importante para mí, pero en aquellos momentos lo era mucho más. Recuerdo el impacto al ver Extraños en el paraíso.<br />
  <br />
              <strong>Sé que no sos cinéfilo y que tampoco ves películas obsesivamente. Pero más allá de eso, tu cine no es un cine que insinúe un director cinéfilo, un cine de citas, parodias o reescritura. Tu cine no surge del cine, sino de otro lado. Incluso de la literatura. En el caso de Los muertos te referiste a tus lecturas de Saer, Quiroga, Rulfo y Dostoievski.<br />
              </strong><br />
              Mis películas no surgen del interés que me haya provocado algún elemento de esta o aquella película. Surgen de la zona donde quiero filmar. Y de qué tipo de vidas generan esos lugares. Para mí los lugares son casi tan protagonistas de mis películas como las personas. Las películas salen del deseo de filmar en un lugar específico. La libertad nació de Misael y de su vida en el monte pampeano. En el caso de Los muertos, yo estaba leyendo La casa de los muertos de Dostoievski, y algunos cuentos de Quiroga. En medio de eso se me ocurrió lo de la cárcel y la selva. Viajé a Corrientes y empecé a unir cabos. Liverpool nació de ver en una revista unas fotos del aserradero. Vi esas fotos y me dije: “Ahí hay una película”. Agarré el auto, estuve tres días manejando y llegué al lugar.<br />
  <br />
              <strong>Pero sí hay algo de Herzog en tu cine. En un reportaje reciente decís: “Herzog es increíble”. Pero también, y eso resulta curiosísimo: “Herzog y los Lumière”. Vale decir, las primeras imágenes cinematográficas y el director que hizo un programa de la búsqueda de imágenes “puras”, “transparentes”. ¿Dónde radica tu interés por los Lumière y por Herzog?<br />
              </strong><br />
              Si me preguntan qué es el cine, respondo: los hermanos Lumière. Ante las imágenes de los Lumière uno se pregunta: ¿qué es esto?, ¿documental?, ¿ficción?, ¿entretenimiento? No lo sé. Era poner la cámara y sorprenderse con lo que pasaba adelante. En los Lumière hay algo espontáneo y natural, muy poco recreado, sin el artilugio que vendrá después con Griffith y el resto. Eso siempre me atrajo de los Lumière. Y después, de Herzog, me interesa la aventura de hacer cine, la aventura de salir a encontrar, de salirse de uno mismo y brindarse. En el caso de Herzog, un alemán que se va a filmar a Perú, o a la Antártida, brindarse al mundo. La idea es salir de donde están generalmente las cámaras y los micrófonos y ponerlos en otro lugar. Brindarse a la experiencia de salir. Yo trato de trabajar con eso; y eso me potencia mucho porque se trata de gente que no es paranoica de la cámara y no vive con un televisor; no tiene ese miedo. No se trata de gente más ingenua, porque no son ingenuos, pero, en relación con la cámara, es gente más fresca.<br />
  <br />
              <strong>Si hay algo que te emparienta con tus personajes, al menos durante la filmación, es la exposición a condiciones hostiles, con la diferencia de que son mucho más hostiles para vos porque, por caso, en la selva correntina o entre las nieves de Ushuaia sos un forastero.Fantasma, entre otras cosas, sería tu revancha sobre Misael y Argentino. En Fantasma el medio es hostil para ellos, mientras que la sala Lugones es el refugio de tus películas, de tu trabajo. La Lugones es para vos lo que el monte o la selva son para Misael o Argentino, el lugar donde sobreviven.<br />
              </strong><br />
              Coincido totalmente. Para el estreno de Los muertos en la sala Lugones lo invité a Misael, porque era un momento importante para mí y él había contribuido. Y entre todo ese conjunto de emociones y nerviosismos que implica un estreno, vi cómo, en un rincón, un poco alejados, se reconocían Argentino y Misael. Me imaginé qué le decía uno a otro. Después siguieron juntos todo el tiempo, porque se sabían sapos de otro pozo. Tuve entonces la idea de filmar en el San Martín con ellos y traducir un poco la emoción y la rareza que debían sentir en ese lugar.<br />
  <br />
              <strong>Fantasma tiene mucho de agradecimiento, entonces, pero también de amigable venganza…<br />
  <br />
              </strong>Cuando terminé Los muertos me di cuenta de que, cinematográficamente, el ciclo con ellos estaba concluido. Entonces pensé que un modo de agradecerles todo lo que Misael y Argentino le dieron a mi trabajo y a mi vida era filmar otra película con ellos. Pero ahora –me dije– vamos a filmarla en el lugar donde yo pasé parte de mi vida de estudiante. Yo me fui allá, ahora que vengan ellos acá… Si ves cómo en Fantasma Argentino sube y baja una escalera, te das cuenta de que nunca bajó y subió una escalera así en su vida. Para Argentino eso es casi tan raro como cuando yo estaba intentando, con otras diez personas, subir a un bote cargado de valijas. Él se moría de risa. Yo no me moría de risa, pero hubo algo de disfrute. Con Fantasma también me permití hablar del cine que a mí me gusta y de los problemas de distribución que tiene. Y además, al mismo tiempo, fue reírme de mí mismo, del tipo de películas que hago, de qué poca gente va a verlas…<br />
  <br />
              <strong>Hay ciertos aspectos de tu cine, o quizá más precisamente de tu posición ante el cine, que, sin usar el término peyorativamente, podrían llamarse “anacrónicos”. Por ejemplo, la reivindicación del 35 mm. Tengo la sensación de que no te interesa especialmente experimentar con la imagen digital, y que serías incapaz –por motivos éticos y estéticos– de manipular una imagen digitalmente. ¿Me equivoco?<br />
              </strong><br />
              Por un lado, mi insistencia en el 35 mm se debe a que soy, por decirlo de algún modo, un romántico o alguien de la vieja guardia: me gustan los fierros pesados, cargar, toda esa cosa física que implica filmar en 35 mm. Por otro lado, aceptar filmar en digital significaría aceptar una imagen mucho más posproducida, retocada. Inevitablemente vas a tentarte. Te va a tentar el hecho de estar editando y preguntar: “¿Esto se puede arreglar?”, y que te contesten: “Sí, acá se puede arreglar todo, si querés cambiarle la cara al actor se la cambiamos”. Yo no quiero eso. Voy a seguir filmando en 35 mm mientras Kodak siga haciendo película virgen y los laboratorios existan. Me gusta el 35 mm porque, por los costos elevados que tiene, no te permite retocar la imagen, te obliga a que la imagen no tenga tanto maquillaje y, además, a pensar mucho más qué vas a filmar. En el video es típico que se prenda la cámara y después de media hora les den las indicaciones a los actores.<br />
  <br />
              <strong>También dijiste que en tu caso la instancia del montaje consiste sólo en cortar las tomas adelante y atrás, y no mucho más.<br />
  <br />
              </strong>El tipo de plano que yo filmo me da poca amplitud para jugar en el montaje. Además, las mías son películas lineales, que cubren una o dos jornadas. En el montaje no puedo inventar flashbacks o flashforwards o inserts. La libertad tiene cincuenta y seis planos, no había mucha posibilidad de jugar. Lo único que descubro en el montaje es el tiempo de cada toma, hasta dónde generan ese extrañamiento sobre algo muy básico, como puede ser alguien caminando o comiendo, y cuándo ya pasan a evadirte de la película, a ser mera duración. Y soy yo quien tiene el ojo para decidir eso. Con La libertad me pasó que se la di a un montajista y me dijo: “Con este material te puedo hacer un buen cortometraje”. Yo le dije: “No, pará… acá hay una película”.<br />
  <br />
              <strong>Hablemos de Liverpool, que se estrenó a fines de 2008. Se habló de que había una apuesta por una narración más clásica, por narrar una historia. Pero eso no me parece decisivo para medir la diferencia con respecto a tus otras películas. Incluso podría decirse que Los muertos tiene más argumento que Liverpool.<br />
  <br />
              </strong>Yo creo que eso se debe en parte a que el protagonista de Liverpool, en contraste con los de las otras películas, tiene una historia heredada de toda la literatura y las leyendas sobre marineros: de los cientos de historias con personajes similares. En contraste con Misael o Argentino, Farrel carga con esa tradición de personajes de mar que puede encontrarse, por ejemplo, en Melville. En segundo lugar, este hombre viene a relacionarse con gente y la encuentra. En las otras películas los personajes siempre están solos. Farrel encuentra a su madre y a una supuesta hija. Encuentra a alguien que lo reconoce, que sabe quién es. Ese mínimo de relato, de gente que pertenece a un mismo círculo familiar y se reencuentra, genera ese efecto de suponer que se está contando más, que hay más historia que en las otras películas. Los elementos que manejo en Liverpool predisponen a pensar que hay más narración. Tampoco me importa mucho si hay más o menos narración. Sí es una película donde la gente tiene más elementos de dónde agarrarse: un marinero que regresa, que se reencuentra con la madre, que descubre a una supuesta hija que no sabe si él la va a aceptar o no... y entonces surge el interés por saber qué va a pasar con todo eso. Por eso me gusta el quiebre, lo que genera el hecho de sacar a Farrel de escena, el descolocamiento que eso produce. En el guión original se jugaba con una cosa medio incestuosa. El guión, cuando lo tenés que presentar a alguna fundación, si lo podés hacer un poco amarillo, mejor, siempre sirve. Después me di cuenta de que no me interesaba filmar eso.<br />
  <br />
              <strong>Como Misael o Argentino, Farrel es un solitario. Sin embargo, Farrel es alguien más huraño para el espectador. Es, además, menos exótico, o no es exótico en absoluto. No tiene destrezas vistosas, como las que poseen Misael o Argentino. Y, en ese punto, es un film más áspero que La libertad o Los muertos.<br />
              </strong><br />
              Farrel es un tipo más urbano. Eso me lo planteé en un comienzo: ¿puede este personaje tener características similares a las de Misael o Argentino? Quizá habría sido más atractivo, pero no hubiese sido honesto, porque Farrel vive en un barco, y los barcos paran en las ciudades, y en las ciudades hay restoranes, revistas, televisión. En el barco además convive con veintiocho tipos durante cuatro meses.<br />
  <br />
              <strong>En Liverpool se atenúa muchísimo aquello que en Los muertos y La libertad generaba la pregunta por el ingrediente documental de tus películas: la búsqueda del otro exótico.<br />
  <br />
              </strong>En las otras el efecto de lo documental también tenía que ver con lo que podría llamarse “salir a filmar más pelado”. En esta creo que se intuye más trabajo, más producción. Y la “producción” está más alejada del documental. Además, Farrel vive en un mundo civilizado. No es un tipo marginado que vive en las afueras del mundo. Es un tipo que recorre el mundo, que viaja de un lado al otro: sabe de tecnologías, conoce cosas. Está a años luz de la cabeza de Argentino o Misael. No es alguien que se perdería en la Lugones. En cuanto a la pregunta por lo documental de mis películas es una discusión que seguí en su momento, pero ya le perdí el rastro. Apuesto a filmar cosas que provengan de la realidad cruda y darles un extrañamiento manipulado, por llamarlo de algún modo, que les agregue una suerte de vuelo ficcional.<br />
  <br />
              <strong>A propósito de La libertad te referiste a la “inocencia” de Misael, y a raíz de eso decías que quizá ya nunca más ibas a poder encontrar esa inocencia. Se advierte una inocencia decreciente en los protagonistas de tus películas. Argentino es alguien menos inocente que Misael, empezando por el hecho de que es alguien que mató, cometió dos asesinatos. Y en el caso de Farrel…<br />
              </strong><br />
              Farrel es un poco mala persona, un poco cobarde. El mundo lo transformó en lo poco que es, pero él no puede cambiar, incluso cuando ve a dos mujeres frágiles que, a su modo, le piden ayuda.<br />
  <br />
              <strong>Frente a cierta característica etérea o incorpórea que tiene la cámara en La libertad y Los muertos, en Liverpool está más anclada a la tierra, es más rígida. Un poco como el personaje, que es alguien rígido, su presencia es incómoda, e incluso en un momento está literalmente duro de frío.<br />
              </strong><br />
              En esa mayor rigidez de la cámara se suman y capitalizan dos cosas. En principio, la personalidad de este hombre. Por otro, el entorno, que está congelado y lleva al estatismo de la cámara. En las dos primeras películas se trataba de una naturaleza más viva, con más sonidos, más verde. Esta es una naturaleza blanca, gélida, que suma a la personalidad de Farrel. El hecho de que la temperatura sea a veces de doce grados bajo cero obliga a que mucho de lo que pasa ocurra en interiores. Entre cuatro paredes es más complicado hacer ese juego de cámara aérea.<br />
  <br />
              <strong>En Liverpool proliferan los interiores. ¿Fantasma fue un entrenamiento para filmar en interiores?<br />
              </strong><br />
              Sí, antes de Fantasma había filmado muy poco en interiores. Con Fantasma nos propusimos generar el extrañamiento que la naturaleza nos había brindado en las películas previas a partir de los elementos que te ofrece un edificio. Desde el sonido, todo eso que antes habíamos hecho con pájaros, agua, monos, lograrlo con el sonido de faxes, de computadoras que se encienden y se apagan, de las cadenas de los ascensores. Desde lo visual, el desafío era cómo encuadrar para que un pasillo deje de ser un pasillo y se transforme en alguna otra cosa. Fue difícil. Seguramente hubo errores, pero hubo aciertos y los aciertos me los llevé para Liverpool. Liverpool no habría sido la misma película si no se hubiese hecho Fantasma.Liverpool, sin Fantasma, hubiera sido más de lo mismo en relación con las películas previas.<br />
  <br />
              <strong>Con respecto a los veinte minutos finales de Liverpool, creo que la desaparición de Farrel confirma algo que ya estaba en tus películas anteriores, pero de modo menos extremo: que tu cámara puede prescindir del personaje, que es autónoma.<br />
              </strong><br />
              La autonomía de la cámara con respecto al personaje obliga al espectador a estar más atento. Si no, el espectador puede relajarse y decir: “Ah, bueno, ahora va a seguir al hacherode pe a pa, hasta el final de la película”. Es un elemento que pone al espectador en alerta y no le permite acomodarse en la butaca. En Liverpool pude hacer algo que me había quedado picando de Los muertos. Luego de que Argentino mata al cabrito, la cámara corta a un chico que se trepa a un árbol. De la nada se corta a un chico, de quien luego se sabrá que es el nieto. Pero durante un tiempo no se sabe bien qué relación tiene eso con lo que se vio hasta ese momento. Siempre pensé qué bueno habría sido prolongar más esa escena, estirar la reaparición de Argentino. ¿Qué hubiera producido eso en el espectador? Hubiese sido como volver a cero. Eso me quedó picando y lo puse en práctica en Liverpool. Además, en este caso había más justificación porque Farrel ya había abandonado ese lugar veinte años atrás. Y la cámara decide quedarse con lo que él deja atrás.<br />
  <br />
              <strong>Si el punto de vista fuera el del personaje caerías en la subjetividad de esos personajes, y me parece que vos buscás lo contrario, ir de afuera hacia adentro, como quería Bresson con sus “modelos”.<br />
              </strong><br />
              Bresson decía algo así como que él apuntaba a buscar en personas reales la esencia, el hueso de los personajes que escribía. Eso es lo que me interesa a mí. Durante el rodaje casi no hablo con la gente que actúa. Ni siquiera saben qué va a pasar. No quiero que actúen, que traten de ser actores, que intenten saber quiénes son, o saber adónde van. Porque, además, como no son actores, no van a saber qué hacer con esa información. Por el contrario, yo elijo a esas personas porque hay algo externo en ellas que se vincula a la interioridad del personaje.<br />
  <br />
              <strong>En La libertad, Los muertos o Liverpool los protagonistas han cortado lazos con sus afectos inmediatos. Pero si en las dos primeras seguías a esas soledades, y el contacto con otros quedaba afuera o era exiguo, en el último tercio de Liverpool te quedás con lo que Farrel dejó atrás, con ese núcleo familiar mínimo. ¿Eso anuncia un cambio en tus intereses, el abandono de los personajes solitarios y el interés por el grupo, por las relaciones sociales o familiares?<br />
              </strong><br />
              Es que me tengo que dar el “lujo” de pensar que hay algo más allá de la soledad, por más que esté convencido de que todos estamos solos en nuestras decisiones y en nuestros últimos años. A nivel personal me tengo que atrever a creer que hay algo más. Además, en Liverpoolyo me preguntaba: Farrel ya está, ahora… ¿qué va a pasar con todos estos que se quedan acá? Quería quedarme ahí. Soy medio negativo en cuanto a lo que pasa con Farrel después de que abandona el aserradero. ¿Vuelve al barco? Para mí, no. Deliberadamente baja todo lo que tiene en el camarote. Si pensaba volver, ¿para qué baja todo? Además, ante la insistencia de la chica, él le da plata. Para mí le da toda la plata que tiene, todo su capital. Y después se va caminando en medio de la nada. El guión decía: “Farrel camina hacia el fondo del cuadro y por fin deja en paz el mundo”.<br />
  <br />
              <strong>¿Ese desprendimiento sería una forma de redención?<br />
              </strong><br />
              De lavar culpas. Él ya se propone lavar culpas cuando decide ir a ver a la madre. Él debía de tener un recuerdo oscuro y alguna culpa nublada. Tiene la necesidad de ir a ver lo que dejó. Una vez que lo ve se lava de toda culpa. Fue solo para eso, para sacarse algo de encima, para liberarse de crimen y pecado. Y después, por otro lado, el llavero genera un link nuevamente con Farrel. Después de veinte minutos volvés a preguntarte, gracias al llavero, qué habrá sido de él. También, volvés a pensar en lo que dejó atrás: una madre senil y moribunda y una chica con un leve retraso.<br />
  <br />
              <strong>Desde el título, Liverpool es la más urbana de tus películas. ¿Podríamos esperar una película tuya que suceda en la ciudad?<br />
              </strong><br />
              La ciudad, para mí, requiere más diálogos y menos imágenes. Hay ciento veinte tipos caminando por la misma calle. No me seduce como propuesta. Antes que filmar en la ciudad, hoy me interesa quizá volver a la pampa, retrotraerme a ciento veinte o doscientos años. Estoy leyendo a Hudson, viajo a la pampa. Esto se vincula a mi interés por salir del lugar donde vivo. Si llego a filmar alguna película más, quiero hacerlo en la pampa. Volver un poco a La libertad. Misael fue el único personaje con el que me identifiqué. Él tenía la misma inocencia que yo al hacer la película.</p>
            <p> <strong>Publicada en la revista Otra Parte.</strong></p>
          </div>
        </div>
      </div>
      <div id="banners">              
        <?php include("inc/banners.php"); ?>
        <?php include("inc/archivo_entrevistas.php"); ?>
      </div>
    </div>
    <div class="push"></div>
  </div>
<?php
  include("inc/footer.php");
?>