<?php
  include ("inc/head.php");
  $GLOBALS['interna'] = true;
  include ("inc/header.php");
?>
    <div id="centro" class="arteliteratura">
      <div id="izquierda">
        <div id="arteliteratura">
          <div class="barra_titulo">
            <span></span>
            <h1>Arte &amp; Literatura</h1>
            <span class="tail"></span>
          </div>
          <div id="header_slider">
            <img src="uploads/denver.jpg" title="Header entrevista" alt="Torre de Babel" />          </div>
          <div id="texto_entrevista">
 <p><em>&quot;La sociedad que reposa  sobre la industria moderna no es fortuita o superficialmente espectacular, sino  fundamentalmente espectaculista. En el espectáculo, imagen de la economía  reinante, el fin no existe, el desarrollo lo es todo. El espectáculo no quiere  llegar a nada más que a sí mismo.&rdquo;&nbsp;</em><em>Guy  Debord, </em></p>
 <p>Hay una especie  de lugar común que intenta explicar la tragedia del tirador de Denver, James  Holmes, como tantas otras en el pasado, como el resultado lineal de una  sociedad violenta. Quisiera postular radicalmente lo contrario.  La tragedia no esta vinculada a la violencia explicita  del universo simbólico, sino a la represión del lugar que ocupa la violencia en  la estructura.  A la negación de los  núcleos traumáticos de mercantilización sobre los cuales se erigen las  sociedades occidentales. No se trata de la violencia visible en el  entretenimiento de la industria cultural (cine, videojuegos, Internet, TV). Se  trata de la totalización del modelo cultural del capitalismo tardío enmascarada  por la posmodernidad que niega constantemente el núcleo univoco de  desgarramiento de nuestra configuración simbólica. </p>
 <p>Holmes no es el  resultado ajeno y enfermo de una sociedad violenta en la forma lineal que se  supone. Sino por el contrario es el regreso espectral sintomático de una  constante represión positiva. Holmes es el regreso psicótico, como negatividad  frente a un campo simbólico positivo de mercantilización y consumismo que  intenta dominarlo todo. No es hijo de la violencia directa. Por el contrario es  hijo de la banalidad de los suburbios americanos, de lo que la banalidad de las  mercancías e imágenes del espectáculo niegan.  Es hijo de aquella cultura que John Cheever  comprendió profundamente en sus relatos como una gran ficción que imponía la  cara del triunfo para ocultar el desgarramiento interno. El sueño americano  posmoderno multicultural y semióticamente ecléctico codificado para sostener la  política de la explotación de las almas, la cultura belicista, la explotación económica,  la miseria, la soledad, la muerte. La negación de la sustancia humana por el  remplazo de la mercancía cultural del espectáculo.  La acción de Holmes estalla repentinamente como  la psicosis de la sociedad del espectáculo. ¿Nadie parece entender por qué?  Todos se proclaman ajenos a la locura de Holmes. No se conocen responsables. No  aceptan la esquizofrenia colectiva posmoderna y el devenir de intensidades  mercantiles que desgarran al sujeto y lo convierten en una sucesión de estados  perceptivos sin capacidad de historización. Un sujeto inhabilitado para pensar  la incompatibilidad entre los distintos códigos y esferas culturales que lo  conforman. Esta organización simbólica como política del capitalismo tardío  permite ser un buen padre en el ámbito familiar, donador en acciones de caridad  social, un cínico delincuente agente de bolsa, un abogado feroz sin piedad, un  gran usuario del mercado comprador de tecnología, al mismo tiempo que  mercancía en si. La identidad está siempre  definida por el código que el sujeto transita y que lo conforma en su  subjetividad, no hace falta ni siquiera que crea que es alguna de estas cosas  sino que simplemente actúe porque cree que no hay posibilidad de actuar  distinto. O el mismo caso de James Holmes, un excelente estudiante de neurociencias,  licenciado con los mas altos honores, consejero de niños necesitados, un día  compra varias armas de fuego, entra en un cine y mata a doce personas, y hiere  a mas de sesenta. No es James Holmes el esquizofrénico. La esquizofrenia es la  hegemonía cultural dominante.</p>
 <p>Aquello que  marca Baudrillard sobre la perdida del referente a través de la imposición del  simulacro marca el paradigma clave para entender estos hechos. Como dice  Baudrillard <em>&ldquo;No se trata ya de imitación,  ni de reiteración, incluso ni de parodia, sino de una suplantación de lo real  por los signos de lo real, es decir, de una operación de disuasión de todo  proceso real por su doble operativo.&rdquo;<a href="#_ftn1" name="_ftnref1" title="" id="_ftnref1"> </a></em> Es evidente que  Baudrillard se adapta demasiado fácil al esquema de consumo del capital.  El problema no es solamente que la destrucción  del referente nos imposibilite construir una responsabilidad política sobre el  otro. Sino que nos desliga completamente de la pregunta sobre el otro. Lo grave  no es solamente que el simulacro se ha impuesto como dominante cultural según  la política de la posmodernidad definida por Baudrillard. Sino también que esta  reconfiguración del campo simbólico es parte de una política de implosión de  los sujetos a partir de una hegemonía de lo hiperreal.  La matanza de Holmes es hija directa de esta  forma de configurar el universo simbólico: una hiperrealidad en la que los  centros de referencia de la estructura han estallado, relativizando toda la  experiencia humana a meras configuraciones espectaculistas.  Dentro de la estructura simbólica todos los  signos tienen el mismo peso, la misma consistencia de mera superficie. La  construcción de una filosofía política productiva no puede darse el lujo de  licuar la &ldquo;materialidad&rdquo; como referente en su estrategia discursiva.  Las condiciones materiales de existencia y  las formas de producción, como referentes, son determinantes para poder articular  la posibilidad de liberación.   </p>
 <p>El asunto es mas  complejo de lo que propone el pensamiento posmoderno de Baudrillard, la  interpretación del simulacro no es absoluta, puesto que todavía funcionan  residuos de la modernidad que no nos permiten ver hasta que punto hemos sido  desgarrados.  Núcleos de identidad  idealistas &ldquo;verdaderos&rdquo; en su código, que enceguecen la posibilidad de ver el  desgarro que ha sufrido nuestra subjetivad.   Como explica Deleuze &ldquo;…<em>aquello que  había demostrado Nietzsche, que el ideal de lo verdadero era la ficción mas  profunda en el corazón de lo real,&rdquo;<a href="#_ftn2" name="_ftnref2" title="" id="_ftnref2"> </a></em>significaba  también que la fantasía ideológica del universo simbólico penetra la  materialidad y genera la relación determinante de poder de la &ldquo;realidad&rdquo; sobre  los sujetos.  Estos núcleos &ldquo;idealistas  verdaderos&rdquo; de los cuales habla Deleuze funcionan como una ficción  mistificadora, que enmascara el proceso esquizoide del capitalismo tardío  posmoderno.  Puesto que reinan como una  falsa totalidad que oculta el desgarramiento esquizoide presente en la  estructura. El mecanismo ideológico nos hace creer en una unidad aparente para  invisibilizar los desfasajes entre los distintos códigos que nos  conforman.  </p>
 <p>La matanza de  Holmes y la radicalidad del acto, apunta a gritos y con toda su fuerza a llegar  a un grado de cero de la esquizofrenia que logre dinamitar la indiferenciación  a través del horror. No es una imagen más, no es una mercancía. Es un grito de  muerte en el corazón del espectáculo. Un horror que nos compromete de otra  forma, que nos obliga a replantearnos. No podemos permitir que se le de a este  accionar el estatuto de discontinuidad respecto a su cultura. La operación de  aislamiento de esta acción es producida por las mismas estructuras hegemónicas  del capitalismo occidental que le otorgan a la matanza ese lugar de  indivualismo desaforado, de lapsus de locura trágico sin sentido o explicación.  Una discontinuidad dentro de la normalidad. </p>
 <p>  <br />
   Si esta matanza  nos dice algo claro, es la imposibilidad de distinguir entre algo más que  imágenes, cuando ya no quedan almas. Estructuralmente, las almas han sido  aniquiladas, mercantilizadas, mediatizadas en la hiperrealidad del capitalismo  tardío. Las almas han sido transformadas en productos predestinados por las  corrientes del esoterismo vendible. No hay diferencia entre el Yoga y un Ipod. Los  arquetipos de Jung o las corrientes milenarias místicas son reconvertidas,  homogenizadas a una pastiche rediseñadado para el consumo. Son puras  intensidades y superficies espirituales, que igualan a todos los dioses, a  todos los espíritus. Las escuelas místicas reprocesadas y convertidas en  productos para soportar la saturación del consumo material. Para mantener el  equilibrio.  Todo adquiere el mismo  estatuto. Todo esta codificado bajo el mismo código lógico, de autoconservación  de la vida como alimento de mercado a costa de negar la cultura de la muerte y  la guerra.</p>
 <p>Recuperar la  experiencia de lo Sagrado implica recuperar la soberanía política de lo Divino  como resultado de una experiencia de la responsabilidad con el otro. Sin duda  que es necesario que esta configuración conlleve un metalenguaje crítico que  atente contra los peligros del viejo idealismo de la antigua metafísica de  objetivación. No se trata de relativizar a través de la posmodernidad para  anular la culpa &ldquo;judeocristiana&rdquo;, sino de deconstruir las relaciones con la  poderosa simbología de la culpa para entrar a nuevos circuitos desconocidos e  inexplorados de liberación y responsabilidad. No se trata de desujetarse de la  fantasía ideológica, sino de dejarse atravesar por ella. Dejarse atravesar por la Fe, por la potencia de la  estructura para sentir el punto de negatividad.  Como explica Heidegger <em>&quot;Si el hombre debe encontrar de nuevo el camino hacia la  proximidad del ser, entonces tiene que primero aprender a existir en lo  innominado.&rdquo;</em> <a href="#_ftn3" name="_ftnref3" title="" id="_ftnref3"> </a>Recuperar la experiencia de  Dios, implica darle sustancia, establecer relación entre la metáfora de la  interioridad religiosa y la pregunta política de la responsabilidad hacia el  otro. </p>
 <p>Holmes es hijo  de la imposibilidad de enunciar toda esta serie de problemas económicos,  éticos, filosóficos.  Nacido de la  imposibilidad de comprender los fundamentos criminales de la lógica del  capitalismo. Él espero a disparar en el momento en que la película ocurría un  tiroteo. Los espectadores no tuvieron tiempo a distinguir entre los tiros  reales y los que provenían de la pantalla. Probablemente Holmes tampoco. La  falta de respuesta y de entendimiento sobre la tragedia de Denver, es también  la falta de preguntas sobre los fundamentos estructurales de nuestras formas de  producción simbólicas y económicas.  </p>
 <div>
   <div id="ftn1"><br />
       Jean Baudrillard,  &ldquo;Cultura y simulacro&rdquo;, 1978,  Editorial Kairos 2005 </div>
   <div id="ftn2">
     <p> Gilles Deleuze, &ldquo;La Imagen Tiempo&rdquo;,  1985, Paidos Comunicación 2007.</p>
   </div>
   <div id="ftn3">
     <p> Martin Heidegger, &ldquo;Carta  sobre el humanismo&rdquo;, Ediciones del 80.</p>
   </div>
 </div>
          </div>
     
        </div>
      </div>
      <div id="banners">
        <?php include("inc/banners.php"); ?>
        <?php include("inc/archivo_arteyliteratura.php"); ?>
      </div>
    </div>
  </div>
<?php
  include("inc/footer.php");
?>