<?php
  include ("inc/head.php");
  $GLOBALS['interna'] = true;
  include ("inc/header.php");
?>
    <div id="centro" class="arteliteratura">
      <div id="izquierda">
        <div id="arteliteratura">
          <div class="barra_titulo">
            <span></span>
            <h1>Arte &amp; Literatura</h1>
            <span class="tail"></span>
          </div>
          <div id="header_slider">
            <img src="uploads/puntosdevista.jpg" title="Header entrevista" alt="Torre de Babel" />          </div>
          <div id="texto_entrevista">
 <p><u>1. Observaciones.</u></p>
 <p>En los estudios académicos sobre cine, se ha convenido  tratar al problema del punto de vista como una cuestión del saber. Se trata de  diferenciarlo de un problema del ver, como si la identificación con un  personaje pasara por percibir visualmente lo mismo que él, es decir distinguirlo  de aquello que se conoce como la cámara subjetiva. En el cine, se considera que  la narración se identifica con el punto de vista de un personaje, cuando los  saberes que se transmiten son idénticos a los que éste posee.</p>
 <p>En un texto ya clásico, los autores Gaudreault y Jost  reconstruyeron las clasificaciones que de esta relación de saberes las  películas pueden hacer. Retomando a teóricos anteriores, llamaron a este  problema &lt;focalización&gt;, considerando el lugar desde el que el relato  hace foco. En primer lugar, nombraron &lt;focalización espectatorial&gt; al  narrador omnisciente convencional, es decir cuando el narrador sabe más que los  personajes. Luego llamaron &lt;focalización interna&gt; a la identificación con  el saber del personaje, o sea cuando el relato da a conocer los acontecimientos  como si estuviesen filtrados por la conciencia del mismo. Y finalmente,  nombraron &lt;focalización externa&gt;  a  aquel saber establecido cuando no se permite que el lector o espectador conozca  los pensamientos o los sentimientos del héroe.</p>
 <p>No es difícil inferir que la estrategia de focalización  elegida, se llevará a cabo considerando el objetivo dramático planteado.  Hitchcock comenta en sus conversaciones con Truffaut:</p>
 <p>&ldquo;Estamos hablando, tal vez haya una bomba debajo de esta  mesa y nuestra conversación es de lo más normal, no ocurre nada especial, y de  repente: bum, una explosión. El público está sorprendido, pero antes de que lo  estuviese se le ha mostrado una escena corriente, sin interés alguno. Ahora  examinemos el suspense. La bomba está debajo de la mesa y el público lo sabe,  probablemente porque ha visto al anarquista que la colocó. El público sabe que  la bomba explotará a la una y sabe también que es la una menos cuarto, hay un  reloj en el decorado; la misma insignificante conversación se convierte de  pronto en muy interesante porque el público participa en la escena. Tiene ganas  de decirle a los personajes que están en pantalla: &lt;No deberíais hablar de  cosas tan triviales, hay una bomba debajo de la mesa y pronto va a  estallar&gt;. En el primer caso, hemos ofrecido al público quince segundos de  sorpresa en el momento de la explosión. En el segundo caso, le ofrecemos quince  minutos de suspense&rdquo;.</p>
 <p>Ya en el plano de los efectos dramáticos, podríamos  identificar a grandes rasgos a la &lt;focalización espectatorial&gt; con la  tentativa de implantar &ldquo;suspense&rdquo; dándole al espectador más información de la  que poseen los personajes (como la bomba debajo de la mesa), y a la  &lt;focalización interna&gt;  con la  sorpresa, de tal forma que cuando por ejemplo la bomba estalla, el  desconocimiento de su existencia genera un efecto imprevisto de sobresalto.</p>
 <p>La repetición de la sorpresa como motivo resolutivo de un  film, ya instalado como recurso posible y frecuente, consigna la necesidad  pensar su relación con la estrategia de focalización elegida, vinculada a su  vez con las marcas de enunciación. </p>
 <p>Películas como &ldquo;Psicosis&rdquo;, &ldquo;The Usual Suspects&rdquo; o &ldquo;Sexto  Sentido&rdquo;, entre muchas otras, presentas variaciones consecuentes de este efecto  de la sorpresa. Los datos que lo posibilitan son de distinta naturaleza; en el  final de &ldquo;Psicosis&rdquo; se trata de la concluyente revelación de que la madre de  Norman Bates es él mismo, o en &ldquo;The Usual Suspects&rdquo; es el descubrimiento de que  el testimonio contado por el entrevistado es una mentira, mientras en &ldquo;Sexto  sentido&rdquo; es el hallazgo de que el protagonista es otro fantasma. </p>
 <p>Tomaremos estas películas como ejemplos de resoluciones  dramáticas satisfactorias en el siguiente apartado.</p>
 <p><u>2. El efecto sorpresa</u></p>
 <p>Se ha vuelto un efecto relativamente corriente el  encuentro con un final de este tipo. Las películas que recurren como dispositivo  narrativo a recursos del estilo de: &ldquo;al final era todo un sueño&rdquo;, o al  &ldquo;síndrome de la personalidad múltiple&rdquo; para anular pedazos, pegar fragmentos o  borrar líneas narrativas que acaban reduciendo personajes a dobles  imaginativos, generados en patologías del protagonista, se multiplican cada  día. Será para encontrar en ellos una vuelta de tuerca capaz de poner al film a  la altura del clímax narrativo, o  simplemente para que el efecto disimule otras  carencias.  El análisis de este aspecto,  poco considerado en los estudios académicos sobre el cine, resulta necesario  para el desglose de otra dimensión narrativa de las películas. Para ello hay  que examinar cómo estos finales disruptivos se componen con la focalización  trabajada. Es decir, analizar si se integran con ella en un plano de coherencia,  o si por el contrario la transgreden.</p>
 <p>Volviendo a Hitchcock, podemos comenzar con la  observación de &ldquo;Psicosis&rdquo;. Tal y como lo escriben Gaudreault y Jost, en el film  el desequilibrio cognitivo viene dado por el uso de una focalización externa, y  en el plano final lo que constituye la sorpresa es la armonización de ambos  saberes, el del espectador y el del personaje de Bates.  A pesar de que a lo largo de la película la  narración muda de perspectivas (desde la de Marion hasta la de su novio) debe  aclararse que la omnisciencia nunca se articula como posibilidad, dada la  repetida renuencia de la narración a mostrar al personaje de la madre. A partir  de esta negación, puede pensarse un vínculo de coherencia entre el efecto de  sorpresa final y el punto de vista.</p>
 <p>Son reiteradas las marcas indicativas que al espectador  le niegan el conocimiento sobre lo que en el final se revela. En cierto  sentido, la película ya está diciendo al espectador que no lo sabe todo.  Podemos pensar en el momento inmediatamente posterior a la llegada de Marion al  &ldquo;Bate&rsquo;s Motel&rdquo; cuando, forzando toda verosimilitud, se constata sonoramente una  discusión entre Norman y su madre, o en aquella otra que tiene lugar luego del  asesinato de Marion, negándole al espectador cualquier indicio de comprobación  visual. Pero sobretodo debe pensarse en el plano cenital en el momento en que  la &ldquo;madre&rdquo; asesina al detective, recurso de puesta en escena que le sirve de  máxima manifestación, evidenciando la voluntad de la cámara de evitar todo  encuentro con el rostro del personaje. Por ello, en retrospectiva, no podemos  sino justificar el efecto de sorpresa final, dada las marcas &ldquo;de ausencia&rdquo;  repetidamente materializadas en el film, que permiten anticipar un final de dichas  características. </p>
 <p>En algunos de estos paralelismos, podemos asemejar a una  película como &ldquo;Psicosis&rdquo; con otra más reciente como &ldquo;Fight Club&rdquo;; aquella que  se presenta como la perspectiva de un narrador sin nombre que inicia un club de  pelea con otro personaje amigo (Brad Pitt), y que eventualmente, apropiado por  éste, el club deviene célula revolucionaria. El efecto de sorpresa aquí, viene  garantizado por el descubrimiento final que consiste en que el amigo es en  realidad el propio narrador. La película se construye con una focalización interna,  que de hecho se enfatiza a partir de una narración explícita constituida por la  voz en off del narrador. No obstante, en este caso, el efecto resulta tramposo  porque no hay indicios a lo largo del film que permiten sospechar de aquello  que se ve. Su insomnio no llega a constituir, desde la narración, un indicio de  percepción errática de la realidad suficiente como para justificar toda una  dimensión de la historia que se nos ve negada. La película nos identifica con  el punto de vista de un personaje, sólo para luego decirnos que en realidad no  había tal identificación.</p>
 <p>No obstante, estos casos deben diferenciarse de otras  películas que se construyen sobre una superposición de puntos de vista. &ldquo;Citizen  Kane&rdquo; es un exponente de ello; durante la película subsiste una tensión, pero esa  tensión resulta eficiente justamente en la medida en que en lugar de ocultarse,  se evidencia. Está en todo momento al alcance del espectador la contradicción  de voces, es una focalización que es tanto espectatorial como interna y  externa. Los testimonios guían una reconstrucción, pero el film se despega de  ellos cuando pone en pantalla eventos que los testigos no podrían conocer, todo  ello sin alcanzar la omnisciencia dado que siempre hay un conocimiento al cual  no podemos acceder. En películas como &ldquo;Citizen Kane&rdquo; la relativa &ldquo;incoherencia&rdquo;  que podríamos atribuirle, puede ser defendida como estrategia enunciativa que  explícitamente asume. No se trata de que el film se proponga desde el inicio un  punto de vista que deba respetar, sino por el contrario de que desde el inicio  ese punto de vista se presenta como fracturado, y esa idea persiste en el  transcurrir narrativo.</p>
 <p>Como contrapunto, otro caso interesante es el de la  película argentina &ldquo;9 reinas&rdquo;. Creemos, durante sus dos horas de duración, que  estamos identificados con el saber de Juan, el protagonista interpretado por  Gastón Pauls, quién está haciendo un trabajo para vender unas estampitas a un  coleccionista español, junto con un estafador de nombre Marcos, interpretado  por Darín. El efecto sorpresa consiste en que sobre el final, nos enteramos que  en realidad todo el trabajo era una fábula inventada por Juan y otra serie de  personajes para estafar a Marcos. El problema, no obstante, resulta de la  contradicción que se genera en creer que sabemos lo mismo que Juan, sólo para  sobre el final constatar lo contrario. La película fracasa en cuanto carece de  marcas de esta negación. Hasta el final al espectador no se le da lugar para  dudar de aquello que ve, y en este sentido la relación de saber permanece  clausurada. Puede argumentarse que el personaje con el que nos identificamos es  un estafador, pero ese se construye como un problema interno del argumento más  que de la enunciación.</p>
 <p>Contrariamente al de &ldquo;9 reinas&rdquo;, un caso eficiente de un  efecto sorpresa basado en la focalización interna es el de la película &ldquo;Sexto  sentido&rdquo;, donde Bruce Willis interpreta a un psicólogo que trata a un niño que  ve gente muerta. Como no podría ser de otra forma, el final es el  descubrimiento de que el propio psicólogo - personaje sobre cuyo punto de vista  se construye la película - es otro fantasma. Pero aquí, la sorpresa del final  no es transgresión porque &ldquo;Sexto sentido&rdquo; nunca incurre en una vulneración de  sus propias reglas. Usa una focalización interna desde el principio, y el  efecto final viene dado por el desequilibrio entre el saber del personaje y su  entorno, que allí se corrige cuando se estabilizan ambos saberes. Y es  eficiente, justamente porque la diferencia cognitiva es la condición de salida  de la película más que una arbitrariedad del devenir de la narración. Las  marcas de ello pueden rastrearse en las primeras dos escenas. Durante la  primera vemos que el personaje de Bruce Willis es disparado, y en la segunda -  laguna mediante - constatamos su encuentro con un niño que ve gente muerta. Es  así como el efecto se ve doblemente justificado; el film juega con la suposición  de omnisciencia del personaje, y sutil pero frecuentemente incurre en marcas  que le susurran al oído del espectador que no lo sabe todo. Ahí radica su coherencia  dramática.</p>
 <p>Es decir que la impresión de sorpresa puede darse a  partir de relaciones de saber diferentes. Por un lado a través de la  focalización externa, basada en que la narración deje traslucir menos  conocimiento del que los personajes poseen, y por el otro a través de la  focalización interna, cuando al espectador se le da el mismo conocimiento que  el que posee el personaje. En el primer caso el efecto sorpresa se basa en el  alcance del conocimiento del espectador con el del personaje, y en el segundo  en el alcance del saber del personaje con el de su entorno. Pero más allá de  estas consideraciones, falta toda una dimensión de análisis en la teoría del  cine, en lo concerniente al vínculo entre las marcas de enunciación y las  decisiones narrativas efectivas que determinan a las películas. Dos esferas que  no pueden seguir siendo tomadas como autónomas, dado que están en diálogo  intrínseco.</p>
 <p><u>Por una ética del punto de vista.</u></p>
 <p>La conclusión que sacamos es la siguiente: no se puede  entablar una relación entre la narración y un personaje que sugiera una correspondencia  de saber de una naturaleza determinada, para después transgredirla en busca de  un efecto arbitrario. Podríamos decir que su no arbitrariedad se constata cuando  éste efecto sorpresa se integra coherentemente con las decisiones narrativas de  punto de vista tomadas desde el principio. Debemos considerar que sólo desde  este lugar pueden ser sujetas a juicio. </p>
 <p>Por ello, el problema no recae en la utilización del efecto  de sorpresa como resolución dramática, sino en el diálogo que este efecto  entabla con las marcas de enunciación. Unas marcas que sugieren una relación de  saber determinada, y que bajo ningún concepto debe verse transgredida en el  transcurso del devenir dramático.</p>
          </div>
     
        </div>
      </div>
      <div id="banners">
        <?php include("inc/banners.php"); ?>
        <?php include("inc/archivo_arteyliteratura.php"); ?>
      </div>
    </div>
  </div>
<?php
  include("inc/footer.php");
?>