<?php
  include ("inc/head.php");
  $GLOBALS['interna'] = true;
  include ("inc/header.php");
?>
    <div id="centro" class="arteliteratura">
      <div id="izquierda">
        <div id="arteliteratura">
          <div class="barra_titulo">
            <span></span>
            <h1>Arte &amp; Literatura</h1>
            <span class="tail"></span>
          </div>
          <div id="header_slider">
            <img src="uploads/reinaldo_arenas.jpg" title="Header entrevista" alt="Torre de Babel" />          </div>
          <div id="texto_entrevista">
 <p>Los  motivos  y  temas  que  abrazan  la  obra  de  Reinaldo  Arenas  nos  empujan  a  abordar  el  carácter  político  que  acompaña  su  escritura.  El  novelista,  dramaturgo  y  poeta  cubano,  nacido  en  1943,  expresó  en  su  adolescencia  un  manifiesto  enfrentamiento  contra  la  dictadura  de  Batista.  Colaboró  con  la  revolución  cubana  hasta  ser  excluido  y  optar  por  la  disidencia.  Arenas,  fue  pretendida  o  ineludiblemente,  un  escritor  de  la  revolución   cubana.  La  revolución  hizo  posible  que  se  formara  y  pudiera  escribir.  Su  obra  tiene  sentido  en,  contra  o  fuera  de  la  revolución. <br />
   Reinaldo  Arenas  sufrió  persecución  por  su  abierta  inclinación  homosexual  y  por  su  resuelta  oposición  al  régimen. Durante  los  años  setenta,  intentó  en  varias ocasiones  escapar  de  la  opresión  política,  pero  falló. Finalmente en 1980 salió del país  cuando  Fidel  Castro  autorizó  un  éxodo  masivo  de  disidentes  y  otras  personas  consideradas  indeseables.  A  causa  de  la  prohibición  que  pesaba  sobre  su  trabajo, Arenas se  vio  obligado  a  cambiar  su  nombre  por  Arinas  para  poder  exiliarse. El  único  libro  que  vio  luz  editorial  en  Cuba  fue  Celestino  antes  del  alba.  En  esta  obra  ya  se  gesta  uno  de  los  temas  principales  de  la  obra  de  Arenas,  la  reivindicación  de  la  diferencia  en  un  contexto  represivo;  a pesar,  que  aquí  sea  la  familia  y  no  el  régimen  cubano  el  sujeto  represor.  Un fragmento de Celestino antes del alba:</p>
 <p>La  mayoría  de  estas  lagartijas  me  conocen  y  me  odian.  Yo  sé  que  me  odian,  y  que  esperan  el  día... «¡Cabronas!»,  les  digo,  y  me  seco  los  ojos.  Entonces  cojo  un  palo  y  las  caigo  atrás. </p>
 <p>Al  fin  doy  con  una.  Le  descargo  el  palo,  y  la  trozo  en  dos.  Pero  se  queda  viva,  y  una  mitad  sale corriendo  y  la  otra  empieza  a  dar  brincos  delante  de  mí,  como  diciéndome:  no  creas,  verraco,  que  a  mí  se  me  mata  tan  fácil. </p>
 <p>En éstas líneas descubrimos el germen de un  profundo odio  político y  dualidad  afectiva  que  proliferan  en  Final  de  un  cuento.  El  odio  incondicional  que  exterioriza  Arenas  hacia  Cuba  es  atravesado  por  una  mirada  nostálgica  y  poética.  Es  su  exilio  a  Nueva  York  el  que  le  proporciona  una  profunda  visión  intelectual  de  la existencia  enmarcada  entre  la  expresión  poética  más  hermosa  y  la  más  amarga  derrota  del  desencanto.<br />
   En  una  primera  instancia,  aquella  porción  de  océano  atlántico  que  separa  Cayo  Hueso  de  la  ínsula  cubana  en  Final  de  un  cuento,  es  el  Mar  de  los  Sargazos.  Mar  caracterizado  por  la  formación  de  bosques  marinos  y   la  estratificación  del agua  por densidades,  formando  una  capa  de  aguas  cálidas  en  las  superficies  a  la  que  alcanza  la  luz  propicia  para  el  crecimiento  de  algas y  plancton;   y  aguas  frías  en  lo  profundo.  En  las  regiones  superiores  apenas  existe  vida  animal,  solo  una  gran  comunidad  de  anguilas  habita  entre  las  algas.  Las  características  singulares del  Mar  de  los  Sargazos,  ha  inspirado  innumerables  leyendas  y  mitos  sobre  las  que  posteriormente  se  crearon  obras  de  ficción. A  saber,  el  “mar  super  sargazo”  es  la  dimensión  dónde  van  las  cosas  perdidas,  según  propuso  Charles  Hoyt  Fort (1874-1932).  No es  casual  que  Arenas  lo describa  como  “el  océano  tenebroso”, dónde  “está  la  muerte  o, lo que  es  peor,  el infierno”.    En  estas  líneas  resuena  el  infierno  de  La  Divina  Comedia.  Arenas  finaliza  su  relato  con  una  plegaria:  “Mar  de  los  sargazos,  mar  tenebroso,  divino  mar,  acepta  mi tesoro (…)  llévatelo  ahora  a  él  a  la  otra  orilla”.   Las  descripciones  que  hace  Arenas  de  “allá abajo”,  resultan  abismales:  “túneles  estruendosos  y  helados”,  “calles  inhóspitas,  abatidas  por  vientos  infernales”,  “una  ciudad  con  todas  las calamidades  que  esas  calamidades  conllevan”.   Inclusive  dice  de  su  amigo muerto: “tu  alma  seguramente  había  seguido  allá  abajo”.  A  pesar  de  éstas  alusiones  directas  a  Cuba,  específicamente  al  régimen,  el  abajo  no  se  percibe  como  un  lugar  o  espacio  particular;  sino,  como  un  movimiento  que  el  personaje  padece  pero  a  la  vez  disfruta  a  través  de  la  confusión  y  homologación  de  Cuba  y  el  arriba  (Manhattan)  en  el  que  el texto  incurre,  saltando  de  un  espacio  a  otro,  de  una  urbanidad  voraz  a  un  clima  tropical.  El  descenso  del  que  habla  Arenas,  es  un  descenso  afectivo  que  se  traduce  a  la  materialidad.  La  isla,  tanto  Cuba  como  Manhattan,  representa  aquél  hogar  que  el personaje  no  tiene. Broadway  también  se  le  presenta  como  el  averno,  como  un  torbellino  dónde “pájaros  nublan  un  cielo  violeta”  y  habla  de  aquel  “mar  de  automóviles”  que  separan  a  su amigo  del  suicidio  como  el  mar  de  los  sargazos  lo  separan  de  la  muerte.  Tanto  el  elevador  que  ambos  toman  hacia  la  terraza  del  Empire  State  como  aquel  balcón  del  que  habla  Arenas,  son  la  clara  materialización  de  éste  movimiento  ascendente  y  descendente  a  partir  del  cual  se  estructura  el  relato. <br />
   El  personaje  de  Arenas  encuentra  su  centro,  su venganza,  su triunfo,  en Cayo  Hueso.  El  autor  pregunta:  “¿Cómo va  a  sobrevivir  una  persona  cuando  el  sitio  donde  más  sufrió  y  ya  no  existe  es  el  único  que  aún  lo  sostiene?”;  y,  declara:  “Nuestro  triunfo  está  en  resistir.  Nuestra  venganza  está  en  sobrevivir.”   El método:  el  olvido.  El  olvido  en  su  faz  positiva  y  negativa.  Aquella capacidad  de  olvido  de  la  que hablaba  Nietzsche  en el  Tratado  Segundo  de  Genealogía de  la  moral.  Arenas  afirma:  “…olvídate  del  español  y  de  todas  las  cosas  que  en  ese  idioma  nombraste,  escuchaste,  recuerdas.”  Un  olvido  que  implica  “… confundirte  entre  ellos,  de  olvidar  y  ser  ellos…”    El  odio  como  motor  del  olvido  y  la  lengua  como  pasaporte.  El  personaje  enfatiza  su aptitud  para  mezclarse,  para  fundirse  entre  otros  que  “también  son  de  otro  sitio (de  su  sitio)  al  que  tampoco  podrán  regresar.”  De  éste  modo  se  nos  presenta  la isla,  aquél  lugar  lejano,  utópico  e  inalcanzable.  Es  ésta  ansía  romántica  por  una  Cuba  perdida  la  que  colma  al  personaje  de  una  tristeza  nostálgica  “que  puede  ser  una  especie  de  consuelo,  un  dolor  dulce,  una  forma  de  ver  las  cosas  y  hasta  disfrutarlas.”  Sin  odio, sin  olvido,  sin  nostalgia,  el  último  consuelo  es  la  muerte,.  Aquél olvido  eterno  de  alguien  que  no  puede  vivir  en  Cuba  ni  fuera  de  ella. </p>
 <p>Reinaldo  Arenas  vio  en  la  narrativa  el  género  ideal  para  organizar  y  exponer  su  credo  ideo-estético y  su  propio  mundo  individual.  Arenas  fue  encarcelado  y  torturado  por  el  régimen  (1974-1976).  Ello  provocó  un  arrepentimiento  y  un  odio  que  fue  más  allá  de  los  muros  de  la  prisión  El  Morro.  Este  sentimiento  se  encuentra  claramente  explicitado  en  Final  de  un  cuento.  Arenas  declara:  “nunca  voy a  volver,  ni  aunque  la  existencia  del  mundo  dependa  de  mi  regreso”.  Aquél  lugar  dónde  mirar  es  un  delito, “donde  hasta  la  misma  soledad  se  persigue  y  te  puede  llevar  a  la  cárcel  por  antisocial”.   La  escritura  de   Arenas,  está  cargada  de  un  fuerte  componente  autobiográfico,  que  más  allá  de  expresar  una  posición  política,  implica  un  canto  desesperado,  un lamento  que  tiene la  necesidad  de  ser oído. </p>
 <p>Volviendo  al  fragmento  de  Celestino  antes  del  alba  citado  con  anterioridad, Arenas  huye  de  la isla  aferrado  a  una  tabla,  como  huye  la  lagartija  que  sufrió  los  palazos  del  régimen,  a  causa  del  odio,  la  opresión  y  la  diferencia,  abandona  la  isla;  pero,  ésta   continúa  presente,  mostrándole  la  cara,  impidiéndole  ignorar.  Lo  único  que  le  queda  al  personaje  es  combatir  la  isla  con  sus  propias  armas,  con  el  odio,  con  el  olvido,  con la  aceptación  romántica  de  un  sin  hogar  que  lleva  la  carga  nostálgica  de  saber  que  lo  único  que  le  queda  es  sobrevivir.  Cómo  último  comentario,  un  fragmento  de  Mi  amante  el  mar: </p>
 <p><i> Sólo el afán de un náufrago podría<br />
   remontar este infierno que aborrezco.<br />
   Crece mi furia y ante mi furia crezco<br />
   y solo junto al mar espero el día. </i></p>
</div>
     
        </div>
      </div>
      <div id="banners">
        <?php include("inc/banners.php"); ?>
        <?php include("inc/archivo_arteyliteratura.php"); ?>
      </div>
    </div>
  </div>
<?php
  include("inc/footer.php");
?>