<?php
  include ("inc/head.php");
  $GLOBALS['interna'] = true;
  include ("inc/header.php");
?>
    <div id="centro" class="arteliteratura">
      <div id="izquierda">
        <div id="arteliteratura">
          <div class="barra_titulo">
            <span></span>
            <h1>Arte &amp; Literatura</h1>
            <span class="tail"></span>
          </div>
          <div id="header_slider">
            <img src="uploads/thewall.jpg" title="Header entrevista" alt="Torre de Babel" />          </div>
          <div id="texto_entrevista">
 <p>La película The Wall (1982) de Alan Parker y Roger Waters es uno de los iconos ingleses contemporáneos que puso en el eje de la cultura popular discusiones sobre la forma en que el sistema educativo funcionaba como un mecanismo de reproducción ideológica y de standardización masiva de los individuos.  Resulto un film paradigmático en la cultura popular que develo sin duda la fantasía oculta reprimida que manifestaba el deseo de incendiar la escuela. La fantasía del niño Pink de destruir el sistema educativo ingles de forma integra era la fantasía de liberación de toda estructura simbólica. Así Roger Waters quien fue niño en la segunda guerra mundial construyo una serie de viñetas narrativas que expresaban la humillación, la violencia y la represión de los maestros escolares hacia a los alumnos. Sin duda lo que The Wall refleja son las huellas psicológicas y sociales de una época en donde las presiones al sujeto de la modernidad desgarraban los espíritus insurrectos. Los mecanismos de aprisionamiento de las subjetividades estaban arraigados en la fortaleza logocéntrica que funcionaba como cohesión de las naciones modernas.  Las estructuras simbólicas de las grandes naciones industrializadas europeas estaban marcadas por dios, el nacionalismo, la represión y la dureza como una forma de sujetación del sujeto, eran el eje central de coacción.</p>
 <p>A partir de este ejemplo retomar el pensamiento de Lev Vigotsky puede ser productivo para reconfigurar la trayectoria de las relaciones de saber y poder. Reconsiderar las tácticas de poder sobre los individuos y comprender hasta que punto el pensamiento de Vigotsky y la influencia del estructuralismo y la dialéctica constructivista produjo una revolución en las formas de concepción de una pedagogía colectiva y no individual. A partir de una dialéctica que concibe al sujeto inmerso y transformado por la estructura simbólica. Nuestra hipótesis justamente consiste en retomar el pensamiento de Vigotsky y las descripciones de los mecanismos instrumentales en el desarrollo educativo para análizar The Wall y realizar un juicio crítico del pensamiento de Vigotsky y The Wall.</p>
 <p>En una de las escenas emblemáticas de The Wall se muestra al profesor humillando al alumno Pink y acusándolo de “poeta sensible”. El sistema educativo canalizado a través del maestro, agente ideológico, marca la necesidad de reestructurar simbólicamente al alumno descarriado. Se busca objetivar al alumno  afirmando el carácter que va determinar su subjetivad.  Es la búsqueda de la delimitación del campo subjetivo exigiéndole presencia como agente racional. En el contexto de la película Pink no debe caer en la fantasía de la poesía puesto que la fantasía resulta para la modernidad signo de debilitamiento de la producción industrial. Así es como el profesor carga contra la falla de desatención en el alumno que no sigue las clases de matemática. El cortocircuito educativo es visto en el nivel de una subjetividad aislada que no responde.  La teoría vigotskiana muestra hasta que punto esta distinción fallida no comprende las relaciones de continuidad y ruptura que se ejecutan constantemente entre el alumno y el profesor.  Podríamos decir que la enunciación de The Wall es vigotskiana en el sentido que se comprende la relación estructural del alumno y su entorno. La relación crece en potencia y se desarrolla a partir de la dialéctica entre sus elementos que se vuelven mas productivos a medida que se retroalimentan.  La obra de Vigotsky enfoco el trabajo pedagógico en la Zona Proximal de Desarrollo a partir de la compresión de los fenómenos psicológicos de los individuos en relación a las transformaciones que este efectúa de sus funciones cognoscitivas por el trabajo colectivo. </p>
 <p>   El relato de Alan Parker y Roger Waters lo que muestra es justamente hasta que punto el sistema educativo de la primera mitad del siglo XX era la negación absoluta de este concepto vigotskiano. Es evidente en el relato el innegable desprecio por el concepto de un crecimiento educativo a partir de un desarrollo colectivo.  El paradigma burgués de la modernidad debía responder a un desarrollo individual que ganase su lugar de pertenencia en el paradigma cultural de la nación, la religión, la patria, la familia y el trabajo.  El precio a pagar de fallar era la expiación a través de la exposición brutal y humillante de la “falla”, del “pecado” cometido contra la efectividad de la familia, de la patria y de la industria. </p>
 <p>Tal vez una de las características importantes de la constitución de los estatutos de los personajes de The Wall sea la relación de los elementos que marcan el acompañamiento de la violencia psíquica y la violencia física. Como un correlato de distintas tácticas de inscripción del poder en los cuerpos y las voluntades. Aquello que alguna vez marco Foucault acerca de que el concepto de alma tenía una penetración material decisiva es clave para comprender lo siguiente. Los golpes con la varilla del profesor y las humillaciones verbales de The Wall son dos formas de ejercicio de coacción que responden a una matriz central, pero de dos formas diferenciadas. Puesto que una utiliza la violencia directa mientras que la otra se reduce a una violencia ideológica de humillación. Lo importante es comprender es que las dos formas tienen un efecto material decisivo sobre los cuerpos y las voluntades. </p>
<p>Acaso una de las criticas a Vigotsky es tener una visión filosóficamente positiva del campo simbólico que solamente marca las relaciones entre la estructura y el sujeto como una dialéctica pero no como una forma también de difusión ideológica. Si bien las descripciones de Vigotsky han sido claves para mostrar hasta que punto en la Zona Proximal de Desarrollo el andamiaje permite una respuesta mayorante del individuo, lo que Vigotsky no concibió fue la idea de que el andamiaje y la ZPD fueran no necesariamente una relación dialéctica sino por el contrario una falsa dialéctica de un orden establecido por la estructura. Aquello que marcaba Althusser respecto a los AIE (Aparatos Ideológicos de Estado) es perfectamente aplicable en este caso. El individuo solo puede determinar al símbolo en tanto es primero determinado por el significante (soporte material). En términos lacanianos es el significante quien determina el inconsciente. Por ende la visión de Vigotsky acerca de cómo los medios y los instrumentos sociales transforman la capacidades cognoscitivas de los individuos adolece de ingenuidad respecto a los efectos ideológicos. La ZPD comprende una gran utilidad acerca de la comprensión del desarrollo a partir del individuo interactuando en relación con su entorno. Muestra hasta que punto todos los elementos estructurales de coyuntura pueden transformar las funciones cognoscitivas y psíquicas de los sujetos pero no establece sus limitaciones políticas. No da cuenta de los peligros de comprender que funcionamiento pedagógico es parte de las tácticas y estrategias que establecen las relaciones de poder. Foucault mostró como el poder no tenia que actuar necesariamente en forma represiva sino a partir de una construcción de poderes y saberes inscriptos como micropolíticas en los sujetos. </p>
 <p>En el caso The Wall es evidente que el retrato de Alan Parker remarca que la concepción de la represión educativa en la modernidad estaba sin duda vinculada a la industrialización y a la guerra como forma de expansión económica. La alienación del sujeto a partir de un acercamiento represivo del espacio simbólico ocupado por la educación, la madre y el matrimonio. Todos estos elementos llevan a Pink a la locura.  De alguna manera la visión represiva de The Wall mostró hasta que punto estaban obsoletas las pedagogías de represión. La posmodernidad dio lugar a nuevas pedagogías que comprenden la subjetividad cambiante en relación a su estructura debilitada. Por eso consideramos al film relacionado a la visión teórica de Vigotsky.  No se trata de que la película exija el andamiaje de la ZPD. Por el contrario el leit motiv es el anárquico “No queremos mas educación. Ey maestros dejen a los chicos en paz”.  Pero es evidente que el relato comprende los mismos preceptos analíticos de interacción primordial del individuo en torno a su esfera social. No solo de la escuela, sino de todas las instituciones que lo rodean y lo transforman. </p>
 <p>Lo que posibilito que The Wall fuese una película con tanto impacto en la cultura popular fue también su crítica retroactiva a prácticas pedagógicas que ya no tienen lugar en la posmodernidad europea. El decaimiento de las prácticas de la educación occidental de la primera parte del siglo XX ha permitido nuevas pedagogías inclusivas.  Sin duda el pensamiento de Vigotsky es actual en muchas de las nuevas prácticas pedagógicas en donde se intenta construir a partir de lo colectivo y no de lo individual. Se intenta interpretar las características sociales que determinan al individuo para articular técnicas instrumentales que enfrenten los contextos particulares que obstaculizan al individuo.  Los preceptos trabajados por el pedagogo Paulo Freire marcan este concepto en el cual educando responde con un constante crecimiento de su capacidad crítica de las estructuras sociales, económicas y culturales.</p>
<p>Como reconocimos previamente la influencia del pensamiento vigotiskiano a la ahora de comprender la transformación de las funciones cognitivas a partir del trabajo colectivo y de estrategias de cooperación entre los individuos mostraron nuevos herramientas que revolucionaron teóricamente la psicología y la pedagogía. Esta conceptualización comprendió la importancia de los elementos culturales en una relación de continuidad, ruptura y dialéctica con los sujetos. Por ende la única forma de revolucionar el campo epistemológico era realizar un nuevo recorte del sujeto de estudio que no tomase solamente la conciencia o la psicología a nivel individual sino que comprendiese la pregnancia estructural. La elección de The Wall nos permite sin lugar a duda ver esa influencia estructural en tanto los núcleos narrativos de la película centran el sujeto en el medio de variadas dinastías de poderes y saberes que lo van encerrando, condicionando al punto de partirlo que lo terminar por alienarlo completamente. </p>
 <p>Sin embargo queremos marcar la necesidad de ir más allá de estas interpretaciones de poder negativas.  Tal cual lo expresa Foucault no se trata simplemente de expresar el poder en términos negativos. De alguna manera esa es la falla del relato de Alan Parker.  La posmodernidad ha traído una contextualización en donde la muerte del logocentrismo marca que el enemigo ya no esta dado en la antigua hegemonía de las instituciones de la modernidad. El remplazo del elemento de simulacro por el elemento real como lo marca Baudrillard, aniquila las referencias de la modernidad. El debilitamiento de las referencias políticas de la modernidad afecta también las teorías pedagógicas de Vigotsky que pueden ser instrumentalizadas como nuevas estrategias de poder.  El trabajo colectivo en pos de una producción mas eficaz en las empresas multinacionales y el desarrollo del análisis del contexto social que el mismo marketing realiza sobre sus empleados es un ejemplo de esto.</p>
<p><strong>Bibliografía</strong></p>
 <p>- Louis Althusser, Ideología y Aparatos ideológicos de Estado, Nueva Visión, Buenos Aires 1988. <br />
   - 
   Michel Foucault, Vigilar y Castigar, Fondo de Cultura Económica, Buenos Aires, 2009<br />
   - 
   Lev Vigotsky, Pensamiento y Lenguaje, Paidos, Barcelona, 2005.<br />
   - 
El desarrollo Cognoscitivo según Lev Vigotsky  http://www.monografias.com/trabajos15/lev-vigotsky/lev-vigotsky.shtml</p>
 <p><br />
 </p>
          </div>
     
        </div>
      </div>
      <div id="banners">
        <?php include("inc/banners.php"); ?>
        <?php include("inc/archivo_arteyliteratura.php"); ?>
      </div>
    </div>
  </div>
<?php
  include("inc/footer.php");
?>